### ISSUE TITLE
9 - WebEx on Fisheries survey series metadata reccomandations

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#10]
WebEx to discuss and recommend fisheries survey series metadata approach, examining established practises, and what is available in ICES

**Comment by neil-ices-dk** [comment]
no response from RCG chairs on the follow-up on the suggestion, and may be superceded by the work on standardised survey coding and associated meta information.
@davidcurrie2001 to follow-up at RCG-technical meeting at the end of May;
