### ISSUE TITLE
Update all external manage lists automatically 

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#101]
Please update all external manage lists automatically like SpecWoRMS, EDMO, ISO_8601 and upcomming EDMERP, P01,P06, L05, L22 etc.

Either fully synchronised 1:1 or needed codes added automatically when requested from the different portals i.e. either synchronised fully every nigth or whenever a code not in RECO then request (programmatically) the extenal system if the code is valid i.e. existing and valid/accepted and then if so, add to RECO.

**Comment by HjalteParner** [comment]
... Also look into to handled depricated / deleted codes - migth be different approach depending on external vocab.

**Comment by neil-ices-dk** [comment]
@mehdiabbasi can you join the next code management meeting, so we can discuss please

**Comment by Osanna123** [comment]
We conceptually agree with the proposal. Implementation of the auto-sync with the external reference lists is to be taken in devops
