### ISSUE TITLE
RDBES RS_DurationSource new code type/list

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#103]
New code		Description
Independent		Duration recorded by independent staff deployed onboard (observers, control)
Crew	        	Duration reported by the crew of the boat
Data	        	Duration estimated from logbooks or other data
Expert Judgement	Duration determined by expert judgement (e.g., the most usual duration observed in the fishery)
Other	        	Fishing duration obtained by some other method

**Comment by cekv** [comment]
Implemented the 9/6 - 2021
