### ISSUE TITLE
RDBES: RS_StateOfProcessing new code list

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#108]
Please see the attached list of codes and descriptions for the new RS_StateOfProcessing 
[RS_StateOfProcessing new code list.xlsx](https://github.com/ices-eg/DIG/files/6604737/RS_StateOfProcessing.new.code.list.xlsx)

**Comment by cekv** [comment]
could we expand this vocab instead? https://vocab.ices.dk/?ref=200

**Comment by cekv** [comment]
implemented 9/6-21
changed code Unknown to UNK to better fit the rest of the codes
