### ISSUE TITLE
Create new CodeType for Mixed Fisheries assessment areas

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/DIG#110]
Mixed Fisheries assessment areas are no defined in a vocabulary but it would be very useful to have.  They would follow the same model as the ecoregions:
https://vocab.ices.dk/?ref=1414

If we get the goahead @sarahlmillar will provide a list of Codes and descriptions.

There is also scope to link these codes with ICES areas vocabularies

**Comment by Osanna123** [comment]
@colinpmillar @sarahlmillar please provide the list so we could accept it and create the references

**Comment by pcrjoana** [comment]
@colinpmillar @sarahlmillar can you provide us the list, please?

**Comment by colinpmillar** [comment]
have created a document on the WGMIXFISH repo. we should have a list of definitions soon. I am also providing code relations. Can you let me know if the format I am ising is ok? or if there is a prefered format for providing this information?

https://github.com/ices-eg/wg_WGMIXFISH/blob/main/Secretariat/mixed_fisheries_areas.json

**Comment by Osanna123** [comment]
@odontaster please have a look at this

**Comment by Osanna123** [comment]
@colinpmillar 
area definition for the Baltic Sea have errors. Please check https://vocab.ices.dk/?ref=358 for more info
 "Code": "BtS",
    "Description": "Baltic Sea",
    "Related": {
      "Ecoregion": [{ "Code": "BtS", "Description": "Baltic Sea" }],
      "ICES_Area": ["27.3.c.22", "27.3.c.23", "27.3.c.24", "27.3.c.25", "27.3.c.26", "27.3.c.27", "27.3.c.28", "27.3.c.29", "27.3.c.30", "27.3.c.31", "27.3.c.32"]

**Comment by Osanna123** [comment]
@odontaster ok to create a new CodeType for the Mixed Fisheries assessment areas (Areas_ICES_MIXFISH or ICES_Area_MIXFISH...).
Ok to implement codes and mappings after you hear from Colin

**Comment by odontaster** [comment]
Codes corrected and implemented
[//vocab.ices.dk/?ref=1731](https://vocab.ices.dk/?ref=1731)

**Comment by odontaster** [comment]
There is an issue due to the fact that the Celtic Sea assessment area has code CS, the same as the ecoregion CS, while they do not represent the same. @lucalamoni  requests to change it so they are two different codes. 
I would suggest creating CeS and deprecating CS

**Comment by odontaster** [comment]
Add info on the change in the new code and als in the old one.

**Comment by odontaster** [comment]
@lucalamoni this is now implemented. Please inform the groups/experts as needed

**Comment by lucalamoni** [comment]
Thank you @odontaster !!!
