### ISSUE TITLE
Adding new strata codes to TS_DepthStratum

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#111]
Hi Guys,
I'm working my way through uploading the Canadian survey data, and so far, I have focused on our longest-running "Summer Survey". For this survey, all of our data lands in the strata you have listed here (http://vocab.ices.dk/?CodeTypeRelID=99&CodeID=201797).  

 Could you please add the following as additional valid Canadian Maritimes strata?
'396','397','398','399','400','401','402','403','404','405','406','407','408','409','410','411',
'516','517','518','519','520','521','522',
'551','552','553','554','555','556','557',
'5Z3','5Z4','5Z5','5Z6','5Z7','5Z8'

**Comment by Osanna123** [comment]
Need confirmation from the requester if he actually needs the codes

**Comment by odontaster** [comment]
@cekv I hadn't seen this one, what is the status? should I take it?

**Comment by cekv** [comment]
@odontaster I think we should close this issue, since this is something the Canadiens requested long ago, but then said they did not need them anyways. I think it ended here just in case they changed their minds, but it seems like they have not - so it should be closed I think. 
You could contact Mike McMahon to make sure he does not need them - only if you want :)
