### ISSUE TITLE
new test stock codes for general use

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#112]
to facilitate exploratory stock splits and scenarios i.e. for benchmarks, we need to include generic stock test codes to allow these codes to be used in ICES data systems. 

Proposal is to include in  [ICES_StockCode]( //vocab.ices.dk/?ref=357) a list of codes with the '**invisible**' flag ticked

Suggested format of codes:
001.xx.test
002.xx.test

Suggest we start with 8 codes.

**Comment by Osanna123** [comment]
001.27.test
002.27.test...
008.27.test
will be created with Visibility 0.
@HjalteParner do you need any mapping to other CodeTypes?
![image](https://user-images.githubusercontent.com/17157764/122224295-427f3480-ceb4-11eb-813c-35933a2cc52c.png)
