### ISSUE TITLE
Improvement of datasets on data.ices.dk

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#118]
Identify down-loadable datasets in data.ices.dk and relevant governance groups responsible for those products to provide recom-mendations to the Governance groups to look into how their products can be improved as part of data.ices.dk

-- lead: ICES data manager

**Comment by HjalteParner** [comment]
https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/21

**Comment by sjurl** [comment]
Planed to be discussed during DATRAS governance group in the following weeks

**Comment by HjalteParner** [comment]
Ocean is happy as it is now - no governance group

**Comment by sjurl** [comment]
Reconvene intersessionaly or during the 2022 DIG meeting
