### ISSUE TITLE
11 - Finalize Best Practise Handbook V1.1

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#12]
Finalise edits to Best Practises Handbook Version 1.1
@jensr to edit and finalise;

**Comment by neil-ices-dk** [comment]
> 
> 
> Finalise edits to Best Practises Handbook Version 1.1
> @jensr to edit and finalise;

to do still

**Comment by Ingeborg1312** [comment]
Jens & Ingeborg: version 1.1 will only serve as a source for version 2 and won't be published as it is already outdated and it is more efficient to start working on version 2 as soon as possible.
this issue closed, continuation in https://github.com/ices-eg/DIG/issues/13
