### ISSUE TITLE
New code "Pseudo-category sampling"

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#123]
IBTSWG: Proposal to create a new Datatype ‘P’ (pseudocategory sampling) for HH records

Documentation and background information:
https://community.ices.dk/ExpertGroups/ibtswg/2021%20Meeting%20Documents/04.%20Working%20documents/WD_MSS%20Pseudocategory%20Sampling%20and%20DATRAS%20datatype%20P.pdf

**Comment by Osanna123** [comment]
The new code might be prone to misreporting, but ok to create.
