### ISSUE TITLE
ESAS: SamplingMethod

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#125]
Sampling method:
https://github.com/ices-tools-dev/esas/issues/18
1 Full ship-based transect method with snapshot for flying birds
2 Full ship-based transect method, no snapshot for flying birds
3 All observations, but no transect operated
4 Presence/absence data
5 Full ship-based transect method with snapshot for flying birds, but no scan data for outside the transect
6 Ship-based strip transect, no snapshot, no distance estimation
7 Ship-based strip transect, with snapshot, no distance estimation
8 Visual aerial line transect method with distance sampling
9 Visual aerial strip transect, no distance estimation
10 Visual aerial total counts
11 Digital aerial – video
12 Digital aerial – stills

**Comment by pcrjoana** [comment]
This is also relevant for the JCDP. Though they might need additional codes: 

Single platform, line transect, distance sampling (SPLT:DS);

Single platform, line transect, (SPLT);

Double platform, line transect, distance sampling (DPLT:DS);

Aerial digital stills (ADS);

Aerial digital video (ADV);

Aerial digital stills and video (ADSV);

Aerial observer, distance sampling (AODS)

Aerial observer, non-distance sampling (AO)

Other (OTHER

**Comment by Osanna123** [comment]
see https://vocab.ices.dk/?ref=1440
