### ISSUE TITLE
ESAS: SpeciesCounted / TargetTaxa

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#127]
https://github.com/ices-tools-dev/esas/issues/19
SpeciesCounted *	
Species (groups) that were counted during sampling:

1 All species recorded (standard)
2 All species except Larus gulls
3 All species except fulmars
4 All species except Larus gulls, fulmars and kittiwakes
5 Auks only
6 Auks and seaduck only
7 All species except eiders and gulls
8 All species except gannets
9 Auks and unusual seabirds only
10 All species except auks and divers
11 All species except small gulls (Little, Black-headed & Common Gull/Black-legged Kittiwake)
12 All species except Lesser Black-backed Gulls
13 All species except seaduck and divers
14 All species except gannets, fulmars and kittiwakes
15 All species except fulmars and gannets
16 Cetaceans only
17 Auks, divers, grebes and seaduck only
18 Cetaceans and rare birds only
99 Other

**Comment by Osanna123** [comment]
New CodeType SpeciesRecorded.
for ESAS to clarify what 'all species' means

**Comment by pcrjoana** [comment]
Could the description of code 16 be more generalised? Eg. "cetaceans focused" or just "cetaceans". The reasoning for this is that in the JCDP format, even if a survey is targeting cetaceans, other things might be recorded.

**Comment by pcrjoana** [comment]
CodeType name should not be SpeciesRecorded nor SpeciesCounted. We will instead call TargetTaxa.

**Comment by pcrjoana** [comment]
After agreement between the data managers, a code for "cetaceans as secondary target taxa" was added.
