### ISSUE TITLE
ESAS: BehaviourRecording

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#129]
https://github.com/ices-tools-dev/esas/issues/21
BehaviourRecording	
Whether and how behaviour was recorded:

0 Behaviour not recorded
1 Typical detailed ship-based behaviour recording (see behaviour field)
2 Typical aeroplane-based activity recording (see activity field)
3 Other (only selected types of behaviour recorded, include more details in Notes)

**Comment by pcrjoana** [comment]
Anna will make the descriptions more generic.

**Comment by Osanna123** [comment]
To be reviewed by ESAS

**Comment by Osanna123** [comment]
Request is cancelled, the field is removed from the format model
