### ISSUE TITLE
12 - Best practise handbook V2

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#13]
Incorporate relevant content and sections in Best Practises Handbook version 2 to reflect update to draft data policy. Note Action expected to collaborate with Action 1 & 2;
Ingeborg is lead; to be continued in May DIG; realistically this will not be complete until the end of 2021 when the data policy/licencing is formally approved

**Comment by neil-ices-dk** [comment]
Ingeborg and Jens to discuss and elaborate a timeframe for the production of v2

**Comment by Ingeborg1312** [comment]
Jens & Ingeborg: version 1.1 will be the current version taking into account all comments made in the past year, version 2 should become a fully restructured version in line with current documentation. 
Timeline for version 1.1 is end June 2021.
Version 2 needs a new discussion -- and a new issue and volunteers.

**Comment by sjurl** [comment]
Participants: Wim Allegaert, Neil Holdsworth, Laura Hanley, Clare Postlethwaite, David Currie, Jens Rasmussen, Sjur Ringheim Lid

**Comment by sjurl** [comment]
Official link: [https://www.ices.dk/sites/pub/Publication%20Reports/Forms/DispForm.aspx?ID=35196](https://www.ices.dk/sites/pub/Publication%20Reports/Forms/DispForm.aspx?ID=35196)

**Comment by sjurl** [comment]
@neil-ices-dk follow up with Ocean Best Practices regarding worng link in the "Resource URL" [https://repository.oceanbestpractices.org/handle/11329/1330.2](https://repository.oceanbestpractices.org/handle/11329/1330.2)

**Comment by sjurl** [comment]
Also include Clare in this work

**Comment by sjurl** [comment]
Version 2:
- restructuring of headings to reflect DPT
- inclusion of new Data licencing and policy
- inclusion of DPT

Aim to have draft ready end of January 2023

**Comment by sjurl** [comment]
subgroup DIG 2023 comment (close action #94 and incorporate following aspects in v2 if still relevant. NB WKDSG has looked at v1 Jan 2019, and not at v1.2 end 2021, so actions may have been overtaken): 
Update data management handbook

to reflect /make it easier to identify how to contribute data to ICES (nice graphics)
Who to talk to / contact your WG etc
Look at annex 6 from WKDSG

Suggestion: let v2 be reviewed by chair(s) of WKDSG and chair(s) of WKEnsure, and governance groups.

**Comment by sjurl** [comment]
Intersessional group: Cecilia, Malin, Diana, Clare,
Lead: Ingeborg

**Comment by Ingeborg1312** [comment]
subgroup meeting dates 2023:
27 June
28 September
13 November

**Comment by Ingeborg1312** [comment]
Input for first subgroup meeting: http://community.ices.dk/Committees/DIG/Master%20documents/Best%20practices%20document/Data-UserHandbook-v2.0_20230623.docx

**Comment by Ingeborg1312** [comment]
2023-06-27: plenary gone through the document, all to review the full document (readability and content) before next meeting. Comments mentioned in the document.
Specific actions
@cekv to check options for adding governance group links to data portal web pages

second meeting postponed from 28 Sep to 2 Oct

**Comment by Ingeborg1312** [comment]
Version 2.0 sent to @sjurl and @jensr for review

**Comment by sjurl** [comment]
Contact ICES publications for next steps for publishing

**Comment by davidcurrie2001** [comment]
Version 2.0 of Best Practices for Data Management is now available via https://doi.org/10.17895/ices.pub.25435903.v1
