### ISSUE TITLE
ESAS: Visibility

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#131]
https://github.com/ices-tools-dev/esas/issues/26
Visibility	
Visibility in kilometer:

0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1
1.5
2
2.5
3
3.5
4
5
6
7
8
9
10 Visibility of >= 10 km
Or as a range (historical codes, avoid use):

A Poor (< 1 km)
B Fair/moderate (1 – 5 km)
C Good/very good (5 – 10 km)
D Excellent/infinity (> 10 km)

**Comment by pcrjoana** [comment]
Also useful for cetaceans. Could we add a "Very poor - <500m" though?

**Comment by pcrjoana** [comment]
These are the codes asked for visibility by the cetaceans people:
Not recorded
Excellent (>10km)
Good (5-10km)
Moderate (1-5km)
Poor (1-0.5km)
Very poor (<0.5km)

**Comment by Osanna123** [comment]
Please add Very poor as code A1 and Poor (0.5-1km) as A2, leaving Poor (0-1km) as another valid code.
