### ISSUE TITLE
ESAS: Glare

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#132]
https://github.com/ices-tools-dev/esas/issues/27
Glare	
Glare that could be affecting the observation quality:

none No glare
weak Weak glare (no major effect on the counting)
medium Medium glare (a part of the viewing area is affected by glare)
strong Strong glare (the whole viewing area is affected)

**Comment by pcrjoana** [comment]
This will be useful for cetaceans, but we might need different codes (in percentage).
