### ISSUE TITLE
ESAS: CloudCover

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#133]
https://github.com/ices-tools-dev/esas/issues/28
CloudCover	
Cloud cover expressed as x/8 (octas) (0 – 8).
https://en.wikipedia.org/wiki/Okta

**Comment by pcrjoana** [comment]
Also useful for cetaceans. They use both oktas and percentages, so we will have to add cloud percentage as options for JCDP. :-)

**Comment by pcrjoana** [comment]
Codes needed for cetaceans:
Not recorded
1-20% 
21-40% 
41-60% 
61-80% 
81-100%

**Comment by Osanna123** [comment]
Make project-specific
