### ISSUE TITLE
ESAS: Precipitation

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#134]
https://github.com/ices-tools-dev/esas/issues/29
Precipitation	
none
rain
snow
fog

**Comment by pcrjoana** [comment]
Another one that will be useful for cetaceans, with the added code "hail"

**Comment by cekv** [comment]
Anna will add hail

**Comment by pcrjoana** [comment]
For cetaceans we will also need "Not recorded" added to this CodeType. Is that OK?

**Comment by pcrjoana** [comment]
First letters used as code (eg F - Fog, H - Hail).
