### ISSUE TITLE
ESAS: RLIST new value

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#136]
Add EURING to RLIST
https://vocab.ices.dk/?ref=44

**Comment by cekv** [comment]
Anna, make it not valid for environmental data :)

**Comment by Osanna123** [comment]
EURING was cancelled. ESAS species list is needed instead

**Comment by Osanna123** [comment]
code is created, QC in DATSU are out of scope of this board. issue is closed

**Comment by Osanna123** [comment]
ESAS RLIST values are linked to the related DatasetVer
