### ISSUE TITLE
ESAS: ObservationDistance

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#138]
ObservationDistance	
Distance at which the birds or marine mammals were observed.

In case of the standard 300 m transect used for ship-based sampling of marine mammals and birds in contact with the water:

A In contact with the water, 0 - 50 m
B In contact with the water, 50 - 100 m
C In contact with the water, 100 - 200 m
D In contact with the water, 200 - 300 m
E In contact with the water, >300 m, beyond transect
F Flying, no contact with water
W In contact with the water, but distance not recorded
For any other type of distance bin classification, the distance is an integer indicating the distance (m) to middle point of one the distance bins specified in the DistanceBins. Observations outside this transect are indicated by a > sign (e.g. >1000).

**Comment by cekv** [comment]
Anna will check with Carlos regarding the codes

**Comment by Osanna123** [comment]
codes are created. numeric values will be handled separately
