### ISSUE TITLE
ESAS: LifeStage

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#139]
LifeStage	
Age class:

A Adult
I Immature (not specified)
1 1st calendar year
2 2nd calendar year
3 3rd calendar year
4 4th calendar year
5 5th calendar year

**Comment by cekv** [comment]
Possible of changing immature to juvenile? Anna will ask.

**Comment by Osanna123** [comment]
ESAS meeting: change the CodeType description to 'life stage based on plumage'
juvenile - specific to 1st year (add in brackets)
immature (sub-adult) relates to 1-5 years (add in brackets)
https://ices-tools-dev.github.io/esas/tables/#lifestage

**Comment by cekv** [comment]
Lifestage based on plumage
Juvenile 1st yr
Immature 1-5 yr

**Comment by Osanna123** [comment]
codes are created
