### ISSUE TITLE
ESAS: Behaviour

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#146]
Behaviour	
Indicates what the species was doing when observed:

0 Unknown
4 Unknown
8 Unknown
10 Unknown
15 Unknown
20 Unknown
29 Unknown
30 Holding fish
31 Without fish
32 Feeding young at sea
33 Feeding, method unspecified
34 Wading, filtering or probing
35 Scooping prey from surface
36 Aerial pursuit
37 Skimming
38 Hydroplaning
39 Pattering
40 Scavenging
41 Scavenging at fishing vessel
42 Dipping
43 Surface seizing
44 Surface pecking
45 Deep plunging
46 Shallow plunging
47 Pursuit plunging
48 Pursuit diving, or bottom feeding
49 Actively searching
55 Unknown
60 Resting or apparently asleep
61 Courtship display
62 Courtship feeding
63 Copulating
64 Carrying nest material
65 Guarding chick
66 Preening or bathing
67 Colony rafts
68 Kleptoparasitising
69 Circling high
70 Wheeling or swimming slowly
71 Escape from ship (rooster tail)
72 Swimming fast, not avoiding ship
73 Breaching clear out of the water
74 At the bow of the ship
75 Apparently feeding: herding behaviour
76 Apparently feeding: other behaviour
77 Calf at the tail of adult
78 Calf swimming freely in herd
79 Basking, afloat
80 Spy-hopping
81 Lob-tailing
82 Tail/flipper slapping
83 Approaching ship
84 Only blow visible (whales)
85 Only splashes visible (dolphins)
86 Acrobatic leaps
87 Sexual behaviour
88 Play
89 Haul-out
90 Under attack by kleptoparasite
91 Under attack (as prey) by bird
92 Under attack (as prey) by mar. mammal
93 Escape diving
94 Flushed (disturbance)
95 Injured
96 Entangled in fishing gear or rope
97 Oiled
98 Sick, unwell
99 Dead
100 Carousel feeding (orca)
101 Pod splitting
102 Pod formation
103 Source avoiding behaviour
111 Not foraging
112 Diving (no specification)
113 Active migration
114 Flying off (no specification)
116 Distraction behaviour
121 Milling (ungerichtetes Verhalten mit Richtungswechsel)
122 Tauchend (marine Säuger)
123 Kopf aus dem Wasser steckend (Robben)

Linked to https://github.com/ices-tools-dev/esas/issues/40

**Comment by Osanna123** [comment]
* we can not keep 'Unknown' with many codes
* we need info on the codes 121-123
* additional description is needed, including relevance to species groups

**Comment by Osanna123** [comment]
121 Milling / Non-directional behaviour
122 Diving (marine mammals)
123 Head out of water (seals)

All unknowns were removed

**Comment by pcrjoana** [comment]
Additional descriptions still needed for 38, 39 and 89 (does haul-out refer to seals?).
These codes will only be implemented when issue #145 is resolved.

**Comment by pcrjoana** [comment]
Cetaceans behaviour to be combined into this one.
Codes needed for cetaceans:
Not recorded
Surfacing
Submerged
Travelling
Milling
Breaching
Feeding
Foraging
Cooperative foraging
Logging/Resting
Vessel Avoidance
Spy Hopping
Attracted to ship
Bowriding
Other (NOT APPROVED)

Note that there are duplicated codes - don't add those ones.

**Comment by pcrjoana** [comment]
Should we use the numbers given by ESAS as codes and start at 30?

**Comment by pcrjoana** [comment]
0 should be unknown, and then start at 30.

**Comment by pcrjoana** [comment]
Foraging changed to Feeding/foraging, as it can be difficult to discern when it comes to cetaceans. 
Just FYI.

**Comment by Osanna123** [comment]
@Osanna123 and @pcrjoana have a look at the list together

**Comment by Osanna123** [comment]
delete 134 Diving

**Comment by Osanna123** [comment]
![image](https://user-images.githubusercontent.com/17157764/150758301-b08ab5ff-94fb-4f7f-b3e5-98b33c8bd9a7.png)
flushing was identified (nearly) same as flying off (114). It was ok to use skipped codes
