### ISSUE TITLE
RDBES: RS_RegDisCategory creation of new code list

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#147]
Code                          Description
'DeMinimis'              'De minimis'
'HighSurvivability'     'High survivability'
'DamagedFish'          'Damaged fish'
'NotApplicable'        'Not applicable'
'NotKnown'              'Not known'

**Comment by Osanna123** [comment]
@HenrikK-N 
please provide the description of this new CodeType, also better description is needed for 'DeMinimis' to not be misinterpreted

**Comment by HenrikK-N** [comment]
The description of RS_RegDisCategory: Logbook registered discard category.

**Comment by HenrikK-N** [comment]
The description for Code 'DeMinimis' should be: 'Discards allowed under a ‘de minimis’ exemption from the EU Landing Obligation'

**Comment by cekv** [comment]
Changes done
