### ISSUE TITLE
DOME: new METCX code request

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#154]
French requester needs a new METCX code https://vocab.ices.dk/?ref=202 
Code needed : MW-HX-ACE Extraction in microwave with hexane and acetone 
Matrix : SEDtot Parameter group : O-PAH

MNA-SPE-SPE (Solid Phase Extraction with methanol and NaOH and Solid phase extraction) or, if possible, linking MNA existing code with SPE-SPE (that doesn't exist) for total sediment.

**Comment by cekv** [comment]
SPE-MNA-SPE

**Comment by Osanna123** [comment]
Codes MW-HX-ACE and SPE-MNA-SPE added to METCX
