### ISSUE TITLE
RDBES: RS_Sampler update of codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#158]
Please see attached spreadsheet for the 4 code updates.

[RS_Sampler updates.xlsx](https://github.com/ices-eg/DIG/files/6930873/RS_Sampler.updates.xlsx)

**Comment by cekv** [comment]
@HenrikK-N  Sampled by Control needs clarification. Imagery to Imaging or Digital imaging.

**Comment by Osanna123** [comment]
CodeType description needs to be embellished

**Comment by cekv** [comment]
RDBES core group: Needs to discuss the EM/Imagery debacle and see if they are both needed. 

Control	-  Sampled by control agency
ElectronicMonitoring  -  Sampled by electronic monitoring
Imagery	-   Sampled using images
Observer	-  Sampled by scientific observer
Self-Sampling	-  Sampled through self-sampling

**Comment by odontaster** [comment]
Wrote to David Currie for update

**Comment by odontaster** [comment]
@HenrikK-N  can we also add this CodeType to the Core group meeting agenda? thanks

**Comment by odontaster** [comment]
ElectronicMonitoring to be removed, 
Imagery stays, update with WGTIFD 2019 report description, and reference it in the Long description.
Self-Sampling to be updated to SelfSampling. Description to be updated to: Sampled by the fisher.

**Comment by odontaster** [comment]
Done
