### ISSUE TITLE
RDBES: RS_incidentialByCatchMitigateDev update of codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#159]
Please see attached spreadsheet for the 22 code updates.

[RS_incidentialByCatchMitigateDev updates.xlsx](https://github.com/ices-eg/DIG/files/6931075/RS_incidentialByCatchMitigateDev.updates.xlsx)

**Comment by cekv** [comment]
Existing codetype : https://vocab.ices.dk/?ref=1613

**Comment by HenrikK-N** [comment]
Please write one sentence of why you give the reference the existing codes. I think the reference is because there is an issue with 2 of the referred existing codes in the requested spreadsheet, that are not exactly the same, existing: FuncADD (referred: Funcping) and existing: Excl (referred: Sealexcl). Please see the updated spreadsheet.

[RS_incidentialByCatchMitigateDev updates 159.xlsx](https://github.com/ices-eg/DIG/files/6959419/RS_incidentialByCatchMitigateDev.updates.159.xlsx)

**Comment by cekv** [comment]
Duplicate of #107

**Comment by HenrikK-N** [comment]
It is not a duplicate of #107 RS_IncidentalByCatchMitigationDevTarget
107 are the '...Target'
Codes are e.g. 

---
SmallCetaceans
LargeCetaceans
ProtectedElasmobranchs
Birds
Turtles
---
This #159 is the device '....Dev' codes like ModHook, AttAltProf...

**Comment by cekv** [comment]
As suggested in issue #107 naming it BycatchMitigationDevice
