### ISSUE TITLE
15 - Governance group WebEX

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#16]
Governance Group WebEx with DIG and Data Centre

**Comment by neil-ices-dk** [comment]
We held a meeting 9th November, [notes and outcome](https://community.ices.dk/Committees/DIG/DIG%202020/04.%20Working%20documents/notes-data-gov-cross-cutting-09112020%20(1).docx) 

Publication of manifesto’s
•	(ACTION) To discuss with ICES pubs (Ruth) to find the best home for these in the ICES public facing library;

@jensr if you have no comments to the summary, will send this out to the GOV chairs

**Comment by neil-ices-dk** [comment]
> Publication of manifesto’s
• (ACTION) To discuss with ICES pubs (Ruth) to find the best home for these in the ICES public facing library;

these will be 'user handbooks'
