### ISSUE TITLE
RDBES: RS_ObservationType update of codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#162]
Please see attached spreadsheet for the 3 code updates.

[RS_ObservationType updates.xlsx](https://github.com/ices-eg/DIG/files/6931273/RS_ObservationType.updates.xlsx)

**Comment by cekv** [comment]
@HenrikK-N 
Suggestion to change the CodeType to ObservationMethod, also better description is needed. RMG not sure about Imagery as correct wording for observation (refering to BD_CountMethod for inspiration)

**Comment by HenrikK-N** [comment]
@cekv okay we can change the CodeType to ObservationMethod. I suggest a new issue for the request of changing descriptions, so we keep this request going.

**Comment by cekv** [comment]
RDBES core group: Imagery is a wording used according to them, and will not be changed.
