### ISSUE TITLE
RDBES: RS_SpecimensState update of codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#164]
Please see attached spreadsheet for the 8 code updates.

[RS_SpecimensState updates.xlsx](https://github.com/ices-eg/DIG/files/6931334/RS_SpecimensState.updates.xlsx)

**Comment by Osanna123** [comment]
we already have ASTSA: http://vocab.ices.dk/?ref=64

**Comment by cekv** [comment]
@HenrikK-N RMG suggest a new CodeType SurvivalProbability and then use ASTSA instead of SpecimenState and adding the codes that are not already there. 
Unknown and NotDetermined should swap descriptions. 
Term Depredated might not be correct - RMG suggest Pred and also if specimen alive in description - Do you want Injured as code as well?

**Comment by HenrikK-N** [comment]
We will not add a new field in the data model for a new code type SurvivalProbability. Potentially ASTSA could be used if missing codes are added from the RS_SpecimensState, which are not in the ASTSA now. But that has to be discussed at the core group. At this point there is not a problem in using RS_SpecimensState and make the requests the core group have to RS_SpecimensState. If the core group later decide to use ASTSA, we can always do that. So for now I suggest to add the one new requested code and update the descriptions for the requested existing codes.

**Comment by cekv** [comment]
RDBES core group: ASTSA scaled to individual species, not large box catches (multiple species), Need to run the CodeType by WGBYC/discard groups for confirmation, before any changes will be made. DM will encourage RDBES core group to do this

**Comment by odontaster** [comment]
Wrote to David Currie for update

**Comment by odontaster** [comment]
@HenrikK-N  can we add this CodeType to the RDBES core group agenda? thanks

**Comment by odontaster** [comment]
Remove ElectronicMonitoring for the time being.
Imagery: The use of one or more cameras to collect single-images or video: (Reference to the WGTIFD 2019 report on the long description of Imagery)

**Comment by odontaster** [comment]
They now remember this code list has been reviewed by Bycatch people in a subgroup, and hence ASTSA code type is not accepted as an alternative, as it is viewed as more focused on preparation procedures of animals, rather than the status of the animal when found.

**Comment by odontaster** [comment]
Please review code AliveAliveHighProbSurvival.

**Comment by odontaster** [comment]
Implemented as described.
