### ISSUE TITLE
RDBES: RS_Presentation update of codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#165]
Please see attached spreadsheet for the 29 code updates.

[RS_Presentation updates.xlsx](https://github.com/ices-eg/DIG/files/6943382/RS_Presentation.updates.xlsx)

**Comment by cekv** [comment]
Could maybe add the full NFAO list of product form presentation at a later date
[fcdoc11-25.pdf](https://github.com/ices-eg/DIG/files/6982251/fcdoc11-25.pdf)

**Comment by cekv** [comment]
https://www.eumofa.eu/documents/20178/24415/Metadata+2+-+DM+-+Annex+5+ERS+present_preserv+to+EUMOFA's.pdf/373b764b-b7cd-4a62-b7a0-98e788d6d65e

**Comment by pcrjoana** [comment]
The code type name should be changed ProductPresentation with extended description explaining this is how the animals are presented in the market.

**Comment by cekv** [comment]
RDBES Core group: some discussion whether to keep Presentation as this is how it is mentioned in logbooks - 
David found this https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:02011R0404-20151120&rid=1, that mentions 3-alpha product
Core group were then ok, by changing this CodeType if necessary

**Comment by cekv** [comment]
Will change CodeType to "ProductPresentation"
