### ISSUE TITLE
RDBES: RS_ReasonForNotSampling update of codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#166]
Please see attached spreadsheet for the 11 code updates.

[RS_ReasonForNotSampling updates.xlsx](https://github.com/ices-eg/DIG/files/6943518/RS_ReasonForNotSampling.updates.xlsx)

**Comment by cekv** [comment]
@HenrikK-N  Explain the difference between No Answer and Unknown - since they mean the same thing (looking at the description for unknown) - Also RMG would like a clarification of Not Available also. 
RMG suggest to have refusal in the description instead of decline e.g Industry refusal.

**Comment by pcrjoana** [comment]
Another question here is if "Other" is necessary. Could "Other" be covered by "NoAnswer" or "Unknown"? An alternative is also to add new codes to the vocabulary if necessary. The reason why the RMG is bringing this up is because in other systems we avoid the code "Other", and instead prefer to add codes if necessary, since "Other" is not informative.

**Comment by jvigneau** [comment]
Agree with spelling out refusal when it is so, like Industry_refusal; we have a case not seen here in the file when a vessel master cannot embark an observer for security reason (vessel too small, no authorisation to embark a special staff, ...); this case is interesting to evaluate the target or sampled population; for your consideration.

**Comment by odontaster** [comment]
-To modify to IndustryDecline, as Refusal sounds too harsh. Industry declines to allow sampling of fish or to allow an observer on board, e.g. for logistical reasons.
-ObserverDecline, Observer declines to collect the sample or go onboard the vessel e.g. for logistic reasons.
-Unknown- Not recorded in the paper work
-No answer- Contact attempted but no answer received.
-Other: required for the time being as many other codes might be needed- Covers all other reasons

**Comment by HenrikK-N** [comment]
I promised to write the list of codes for which the ‘, ref. SGPIDS report 2013’ should be added to the description (not long description). The codes are: NotAvailible, NoContactDetails, ObserverDecline and IndustryDecline. The codes for 'ObserverDecline' and 'IndustryDecline' should be updated with a 'd' and the end to 'ObserverDeclined'.
