### ISSUE TITLE
Surveys codes

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#173]
There is a comprehensive list of survey codes with description here
https://icesit.sharepoint.com/sites/DCTeam/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120006D5FF1C28157A04AA26465202873524C&viewid=d9a26d0c%2D1f7b%2D4a66%2D81a1%2D4729632b9d82&id=%2Fsites%2FDCTeam%2FShared%20Documents%2FGeneral%2FICES%20SurveyCodes%20docs

Only the green ones are in RECO (not visible).

Could we send out to Ruth to review it and import all the list to RECO, hoping that some codes will be edited in the future

**Comment by pcrjoana** [comment]
See issue #37

**Comment by odontaster** [comment]
Asked an update to Ruth, she will consult with Lotte whether this task can be closed and whenever new codes are needed those will be new issues. Answer by next week's RMG

**Comment by odontaster** [comment]
@cekv  can you give a resume of the meeting with Lotte?

**Comment by cekv** [comment]
@odontaster Basically, I will present Lotte with the surveys that have not been checked and those where the more crucial information is missing and she will then get the assessment people to look through the surveys relevant for their stock to retrieve this. We will use the community to get information on the un-resorted codes.
