### ISSUE TITLE
RDBES: SampleType updates 

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#174]
Please see attached spreadsheet for insert of 6 new codes.

[SampleType updates 6 new codes.xlsx](https://github.com/ices-eg/DIG/files/7013126/SampleType.updates.6.new.codes.xlsx)

**Comment by pcrjoana** [comment]
These are not sample types, and thus these codes cannot stay in SampleType. These codes also mix measurement type (linear vs curved length) and the type of rounding. These codes will be moved to a new CodeType: MeasurementRoundingType.
Cecilia will delete the codes requested here from SampleType.

@neil-ices-dk has given his input and agreed with this course of action.

**Comment by HenrikK-N** [comment]
The core group request to have the following two codes added to the SampleType:
Code                  Description
LinearLength      Linear measurement (along body axis) 
CurvedLength	   Length taken over body surface integer

**Comment by Osanna123** [comment]
CodeType is renamed to MeasurementRoundingType
ok for adding 2 new codes

**Comment by cekv** [comment]
RDBES core group: not adverse to add "CurvedLength" and LiniearLength" to a more generic Length measurement CodeType (i.e TS_LenMeasType/AC_LengthMeasurementType) - Data manager to put this forward  to GOV groups to join these two CodeTypes and adding the two RDBES codes

**Comment by odontaster** [comment]
Should be a new issue to combine Code Types describing Length Measurements.

**Comment by odontaster** [comment]
1 Total length
2 Standard length
3 Pre-supra-caudal fin length
4 Pre-anal fin length
5 Mantle length
6 Carapace length
7 Carapace width
8 Second dorsal fin length
9 Shell height
10 Shell width
11 Wing width
-9 Not known

Should Linear length and Curved length be types of Total length?
Will put this in 2nd WGDG agenda

**Comment by odontaster** [comment]
1 Total length, unspecified
2 Standard length
3 Pre-supra-caudal fin length
4 Pre-anal fin length
5 Mantle length
6 Carapace length
7 Carapace width
8 Second dorsal fin length
9 Shell height
10 Shell width
11 Wing width
12 Total length, linear
13 Total length, curved
-9 Not known

And then link relevant codes to each dataset.
Need to check with WGDG @odontaster

**Comment by odontaster** [comment]
Feedback fro WGDG:
-No need for 12
-1 should be Total length, linear
-All codes linked to DATRAS Dataset
-Missing: Pinched tail length (in Long description: only used for mackerel)

**Comment by odontaster** [comment]
Updated TS_LenMeasType and AC_LengthMeasurementType
