### ISSUE TITLE
RDBES: METOA update of codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#175]
Please see attached spreadsheet for the insert of 13 new codes.

[METOA updates new codes.xlsx](https://github.com/ices-eg/DIG/files/7013157/METOA.updates.new.codes.xlsx)

**Comment by cekv** [comment]
[METOA.updates.new.codes_RMG.xlsx](https://github.com/ices-eg/DIG/files/7013882/METOA.updates.new.codes_RMG.xlsx)
Codes need to reflect the METOA codes - the list are suggestions

**Comment by cekv** [comment]
Anna has made changes to the codes so they can be accepted
[Copy of METOA.updates.new.codes.xlsx](https://github.com/ices-eg/DIG/files/7014012/Copy.of.METOA.updates.new.codes.xlsx)

**Comment by HenrikK-N** [comment]
That is good please proceed.

**Comment by pcrjoana** [comment]
The codes should be linked to the specific dataset/dataset version.
