### ISSUE TITLE
RDBES code review: RS_AggregationLevel

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#177]
RS_AggregationLevel: https://vocab.ices.dk/?ref=1607
Could this be implemeted to AGTYP (https://vocab.ices.dk/?ref=178) ?

**Comment by pcrjoana** [comment]
A more elaborated CodeType description is needed, and the code descriptions should be changed to "By haul" and "By trip".
The RS should be removed.

**Comment by pcrjoana** [comment]
Do not merge with AGTYP.
