### ISSUE TITLE
RDBES code review: RS_CatchFraction and RS_CatchRegistration

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#178]
RS_CatchFraction:  https://vocab.ices.dk/?ref=1611
RS_CatchRegistration: https://vocab.ices.dk/?ref=1604 

Possible duplicates
Could be merged into one codetype

**Comment by pcrjoana** [comment]
Better descriptions for the codes are definitely needed.
A solution would be to duplicate the code type IC_CatchCategory (https://vocab.ices.dk/?ref=259) to a new generic code type CatchCategory and then deprecate "IC_CatchCategory" when Intercatch is discontinued. RS_CatchCategory (https://vocab.ices.dk/?ref=1610) would also be merged into the new generic CatchCategory code type.

Cecilia to bring this for discussion in the RDBES core group.

**Comment by pcrjoana** [comment]
Linked to #179 and #45

**Comment by cekv** [comment]
RDBES core group: These 3 CodeTypes ("RS_CatchCategory", RS_CatchRegistration" and "RS_CatchFraction") are needed to be able to verify codes across multiple checks in the data - it is not possible to do this with one generic code type - the descriptions will be updated for all, but the CodeTypes needs to stay

**Comment by odontaster** [comment]
Will close this for the time being. @cekv have the descriptions been updated?

**Comment by odontaster** [comment]
Improved CatchRegistration and CatchFraction descriptions following Core group meeting 23/03/2022
