### ISSUE TITLE
17 - SMARTDOTS framework description

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#18]
Review and finalise SMARTDOTS framework description with WGSMARTGOV

**Comment by neil-ices-dk** [comment]
the final draft is ready - sent to ICES publications...

**Comment by wimallegaert** [comment]
[WGSMART Governance Framework 2019_final.docx](https://github.com/ices-eg/DIG/files/6507231/WGSMART.Governance.Framework.2019_final.docx)

The most recent version is attached, although it says 2019 it was actually updated in June 2020.

The alignment of Framework docs across governance groups was discussed when this topic was taken up at a meeting in Nov 2020 for “Data Governance Cross-cutting Issues”.  At this meeting it was decided that WGSMART should not continue working on this document until ICES had an agreed document to use broad. 

An action of the meeting was to discuss with ICES pubs (Ruth) to find the best home for the Framework docs in the ICES public facing library.

**Comment by neil-ices-dk** [comment]
> 
> 
> [WGSMART Governance Framework 2019_final.docx](https://github.com/ices-eg/DIG/files/6507231/WGSMART.Governance.Framework.2019_final.docx)
> 
> The most recent version is attached, although it says 2019 it was actually updated in June 2020.
> 
> The alignment of Framework docs across governance groups was discussed when this topic was taken up at a meeting in Nov 2020 for “Data Governance Cross-cutting Issues”. At this meeting it was decided that WGSMART should not continue working on this document until ICES had an agreed document to use broad.
> 
> An action of the meeting was to discuss with ICES pubs (Ruth) to find the best home for the Framework docs in the ICES public facing library.

@RuthAnders can you confirm that we agreed that these would sit in the 'user handbooks' library section - thanks :)

**Comment by sjurl** [comment]
Waiting on feedback on publication.

**Comment by RuthAnders** [comment]
Hi! Yes, this should go into User Handbooks. Sorry for the delay in answering. We discussed this internally back in the day together with another discussion on giving the User Handbooks a bit of a higher profile, with a new template, but then completely dropped the ball at passing this information on. I´m checking that everything is ready with the new template, and then we can finalize this.

**Comment by neil-ices-dk** [comment]
[https://community.ices.dk/Publications/UserHanbooks](https://community.ices.dk/Publications/UserHanbooks)

**Comment by sjurl** [comment]
@sjurl followup status on this task with @wimallegaert

**Comment by sjurl** [comment]
Ready for integration in the ICES user handbook section

**Comment by wimallegaert** [comment]
The WGSMART governance doc has been published. You can find it here: [https://doi.org/10.17895/ices.pub.19948607.v1 ](url)
This action can be closed.

**Comment by sjurl** [comment]
[https://doi.org/10.17895/ices.pub.19948607.v1](https://doi.org/10.17895/ices.pub.19948607.v1)
