### ISSUE TITLE
RDBES code review: RS_CommercialSizeCategory

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#182]
RS_CommercialSizeCategory: https://vocab.ices.dk/?ref=1623 

Detailed description needed

**Comment by pcrjoana** [comment]
Code type needs better description.
Cecilia to discuss with the core group whether a vocabulary is needed at all.

**Comment by cekv** [comment]
RDBES core group: 1-99 are arbitrary codes, codes b-XS are national codes - need to add EU codes 0-7(8) Nuno will provide documentation for these.

**Comment by odontaster** [comment]
Asked Nuno for an update on this

**Comment by odontaster** [comment]
@HenrikK-N can we add this to the Core Group agenda, as a reminder for Nuno? thanks

**Comment by odontaster** [comment]
@cekv  need some help with this

**Comment by cekv** [comment]
@odontaster I will help, just let me know what you need :)

**Comment by odontaster** [comment]
Included Size categories, according to Council Regulation (EC) No 2406/96
Contacted Ana Claudia Fernandes for some info on descriptions from portugal
