### ISSUE TITLE
RDBES code review: RS_FishingTechnique

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#190]
https://vocab.ices.dk/?ref=1612

seems to copy the metier 4 - GearType but with small differences https://vocab.ices.dk/?ref=1653

**Comment by cekv** [comment]
Mix of concepts of codes, needs to be reviewed. These are not fishing techniques in itself, mix of vessel type, metier4 and others. 
Is this code type used in the data model?

**Comment by cekv** [comment]
RDBES core group: FDI data call uses the same terminology and it needs to be compatible with their codes - look at EU fleet segmentation EU map table 8

**Comment by cekv** [comment]
RMG recommend this CodeType to be named "FDIFishingTechnique" and reference to FDI data call
https://datacollection.jrc.ec.europa.eu/documents/10213/1385040/FDI2021-annex.pdf/6bb0a9b7-166c-48c8-ad12-48ea59a29ffe
Annex 3

**Comment by Osanna123** [comment]
@odontaster please communicate this one

**Comment by odontaster** [comment]
Hi @HenrikK-N can you review this reccomendation on the CodeType name? maybe we can talk about it in our next team sprint if needed. Cheers!

**Comment by odontaster** [comment]
RDBES code group prefers not to have accronyms in the CodeType, I agree.
The reference to FDI and AER is added in the description.
