### ISSUE TITLE
RDBES code review: RS_LandingCategory

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#194]
https://vocab.ices.dk/?ref=1609

Needs some editing:  uppercase letters in description

**Comment by Osanna123** [comment]
This CodeType is nearly a duplicate of https://vocab.ices.dk/?ref=264 (IC_Usage) and https://vocab.ices.dk/?ref=314 (IC_FleetType)
RS_LandingCategory is greatly misleading name. Please consider a better option. WGCATCH can be consulted.
@cekv please communicate with the RDBES core group

//making the uppercase letters in description is ok

**Comment by cekv** [comment]
Will be communicated with RDBES coregroup in December

**Comment by cekv** [comment]
RDBES core group: Has been used for 15+ yrs well known term - will not be changed

**Comment by odontaster** [comment]
https://stecf.jrc.ec.europa.eu/ewg2016

**Comment by odontaster** [comment]
will close for the moment
