### ISSUE TITLE
RDBES code review: RS_LEfullTripAvailable

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#195]
https://vocab.ices.dk/?ref=1600 

Flag like YesNoField?

**Comment by Osanna123** [comment]
The CodeType RS_LEfullTripAvailable looks redundant considering the existence of the https://vocab.ices.dk/?ref=316 (YesNoFields).
For RDBES core group: please consider using NULL for the 'unknown option, and using the YesNoFields CodeType.

**Comment by cekv** [comment]
Consensus from Ejaz and Henrik was that, adding NULL/NA to the YesNoFields CodeType could possibly create potential error in the other systems that use this CodeType and Have done so for many yrs (breaking the logic behind it) - this has to be investigated.
They suggest a CodeType called YesNoNA/YesNoUnknown to circumvent such potential errors.

**Comment by pcrjoana** [comment]
@HenrikK-N we are curious to know why the "unknown" option is relevant? Is the field mandatory? If it's optional, a non reported value could serve as "unknown", couldn't it?

**Comment by cekv** [comment]
There is an agreement to use a CodeType in according to this issue #264

**Comment by Osanna123** [comment]
@odontaster have a chat with Ejaz

**Comment by odontaster** [comment]
Waiting for @EjazAtIces to move this to implemented.
