### ISSUE TITLE
RDBES code review: RS_LowerHierarchy

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#197]
https://vocab.ices.dk/?ref=1598

Personally, no comment

**Comment by Osanna123** [comment]
Please drop the RS_ from the CodeType name.
Provide better description of what 'lower hierarchies' are, al least in the Long Description for the CodeType.
What do FM and BV and None refer to? Drop them or give better description.

**Comment by cekv** [comment]
Waiting for improvement on the CodeType description from Henrik
