### ISSUE TITLE
Stock code and stock code description change?

### ISSUE THREAD

**Issue by JetteFredslund** [ices-eg/DIG#199]
Stock coordinator wish to change the description and code for the raj.27.67a-ce-h stock. Current stock description: "Other rays and skates (Rajidae) in Subarea 6 and divisions 7.a-c and 7.e-h (Rockall and West of Scotland, southern Celtic Seas, western English Channel)". This should change to "Other skates and rays (Rajiformes) in Subarea 6 and divisions 7.a-c and 7.e-k (Rockall, West of Scotland, Celtic Sea and western English Channel)". The rationale behind this proposed change is explained by the stock coordinator like this:  Change from ‘Rajidae’ to ‘Rajiformes’ because (i) there are some (usually deeper-water) skates that are in a separate family (Arhynchobatidae) that technically would be included here if taken in fisheries, (ii) the TACs apply to the Rajiformes, and this "stock" would include skates being reported from all of 6-7 (except 7.d). Unsure why 7.j-k were omitted last time this stock description changed. 6, 7.a-c and 7.e-k would be better. The change from 'rays and skates' to 'skates and rays' is simply to align it with similiar stock descriptions in other areas.

**Comment by odontaster** [comment]
We were surprised to note that there is no division 7.i so actually 7e-k is not fully right, but already like this in  valid stock code ldb.27.7b-k8abd.

**Comment by odontaster** [comment]
@JetteFredslund  I can only find stock codes with Other rays and skates and none with Other skates and rays.
Can you double check this and let me know here?

**Comment by JetteFredslund** [comment]
@odontaster I think the confusing for the stock coordinator stems from the fact that the advice sheets (the pdfs) have not been consistent in their titles over the years and have been titled both "Other rays and skates" and "Other skates and rays" - however, in the vocab this is not the case - here they are named consistently. Sorry for this confusion!

**Comment by Osanna123** [comment]
@odontaster please check with Inigo about this request.
For Intercatch, renaming should be ok.
ICES_StockCode would need a new stock reference.

**Comment by odontaster** [comment]
@inigomartinez

**Comment by martinezinigo** [comment]
On this: i seem to remember that by convention (FAO?) we (nobody) use the i as it was confounded by 1, by l or subordinated designations like ii) .... anyway Soren the Elder may have known and i've discussed the case with Simon now.

The case raised by the SCoord is valid and I do not see the reason to exclude 7.j-k. AND I support the change to  6, 7.a-c and 7.e-k. 

The change in Order is however more academic and strictly speaking he is right, the Order contains several Families that potentially could be caught (but they will never be or will never be reported and this may be only noise). I don't think I am the authority to decide on this BUT i will also go for the change and use the Order, Rajiformes, on the grounds to align it with the TAC documents.

**Comment by odontaster** [comment]
Pending to deprecate the old stocks in both ICES_StockCode and in IC_Stock, and inform HK-N. Will do early 2022, already wrote a calendar note, so shouldnt forget.

**Comment by odontaster** [comment]
Created ICES_stockcode and IC_STock, in IC_sstock deprecated the old name. Informed @HenrikK-N.

**Comment by JetteFredslund** [comment]
@odontaster @martinezinigo Sorry to get back to this one - but did we agree to also change the stock ID for this? I can't really tell from the messages above? The stock code was/is raj.27.67a-ce-h but with the mention of 7.k in the description, should the stock ID not change to raj.27.67a-ce-k
Sorry if this has already been done and I'm just not up to date :)

**Comment by JetteFredslund** [comment]
HI @odontaster , yes, sorry, I mean code. I am in touch with Mike about this, since I was of the impression that SID would update automatically the changed stock code and the stock description. But this has not happened yet. So will ask Mike to check it out.
