### ISSUE TITLE
1 - Revise ICES Data Policy to separate out licensing conditions, focussing on the handling and processing of all data in ICES instead

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#2]
chris moulton is the lead;

**Comment by neil-ices-dk** [comment]
@neil-ices-dk to setup a meeting with Chris and Sjur to run -through the distillation of the data policy as we need to complete this by mid-Feb

**Comment by ospar-odims** [comment]
@neil-ices-dk @sjurl let me know when you'd like to meet so we can get this underway- preferrably next week (beginning 18 Jan)

**Comment by neil-ices-dk** [comment]
> 
> 
> @neil-ices-dk @sjurl let me know when you'd like to meet so we can get this underway- preferrably next week (beginning 18 Jan)

oh you are keen ⏩ reckon we start with a 1 hour session, DK timeslots:
- Tues 19th, 12:00-14:00
- Thurs 21st, until 12:30

**Comment by sjurl** [comment]
@neil-ices-dk @ospar-odims Tues 19, 12-14 and Thrus 21, 9-11 is possible for me

**Comment by neil-ices-dk** [comment]
Word version of existing 2016 (latest) policy is here 
[Data Policy](https://community.ices.dk/Committees/DIG/Master%20documents/Data-Policy-and-licences/ICES-Data-policy.docx )
________________________________________________________________________________

**Comment by neil-ices-dk** [comment]
For next meeting (3rd Feb)
-	Restricted licence references tidy up
-	Change log add
-	Website check language
-	Check CC-BY reference (@ospar-odims Chris check)

[working version here](https://community.ices.dk/Committees/DIG/Master%20documents/Data-Policy-and-licences/ICES-Data-policy-2021-POLICY.docx )

**Comment by neil-ices-dk** [comment]
finalised version ready for SCICOM 🐐 
[ICES data policy 2021](http://community.ices.dk/Committees/DIG/Master%20documents/Data-Policy-and-licences/ICES-Data-policy-2021-POLICY.docx)

**Comment by neil-ices-dk** [comment]
@sjurl just confirmed with Vivian that for SCICOM we will need a document from DIG in order to have a recommendation from them (for ICES Council). The deadline is the 8th of March for the document. So suggest we need to crack on with this, we have the text i believe in the 2020 DIG report for the context and background, and then we just need to explain the 'package' that is now being presented for recommendation for adoption at Council. Once you have got your head into this, let me know if you want to have a meeting to review a draft

**Comment by sjurl** [comment]
@neil-ices-dk I have started writing and will hopefully have something by wednesday. Would thursday afternoon work for you, otherwise all of friday is currently free for me

**Comment by neil-ices-dk** [comment]
thanks @sjurl Thursday afternoon is perfect - will send an invite for an hour and feel free to adjust 📆

**Comment by neil-ices-dk** [comment]
[final package](https://community.ices.dk/Committees/SCICOM/2021%20March/02.%20Background%20documents/Data%20policy%20and%20licences) delivered to SCICOM, the supporting document to SCICOM [is here](https://community.ices.dk/Committees/SCICOM/2021%20March/01.%20Working%20documents/Doc%2019.3-1%20ICES%20Data%20Policy%20and%20Licensing.pdf)
