### ISSUE TITLE
RDBES code review: RS_QualitativeBias

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#204]
https://vocab.ices.dk/?ref=1616 
needs consistency in large/small letters in description

**Comment by Osanna123** [comment]
- Change the CodeType description
- Capitalize first letters of code descriptions
- For RDBES core group: 'little under/overestimate' raises concerns. Slight, marginal, great or other synonyms could be more fitting. Are the terms from Hyder et al. 2017?

**Comment by cekv** [comment]
RDBES core group: agreed to the changes so it is consistent with the article Hyder et al 2017.

**Comment by cekv** [comment]
Changes according to article applied and it will be referenced in the long desc.
