### ISSUE TITLE
RDBES code review: RS_Region

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#205]
https://vocab.ices.dk/?ref=1640

delete and replaced by ecoregion?

**Comment by Osanna123** [comment]
For the RDBES core group to provide area references (documentation)
Can ICES Ecoregions be applied instead?

**Comment by cekv** [comment]
RDBES core group: suggest RCGRegion for CodeType - DM need to clarify if they wanted to use already RCG list or make their own RCGregion - reference to EU map region/workplan master table - NA (North Atlantic) as code not good when working with R

**Comment by cekv** [comment]
Will need to be discussed with Neil in the new year.

**Comment by odontaster** [comment]
I will ask Colin if this is the best way to handle this NA issue in R or there is an easier work around it commonly used for similar situations.

**Comment by odontaster** [comment]
Just found this:
https://www.fisheries-rcg.eu/
@cekv

**Comment by cekv** [comment]
We already have this code type: https://vocab.ices.dk/?ref=1503 - We should make them use a subset of that or the ecoregion one (https://vocab.ices.dk/?ref=1414) otherwise maybe it should be free-text

**Comment by odontaster** [comment]
Right! will put this up in the next core group, but I saw we are missing one RCG econ in our vocab, I guess we should update it? @cekv 
Let's discuss it in the next rmg

**Comment by odontaster** [comment]
Add RCG Econ to the list.
