### ISSUE TITLE
RDBES code review: RS_SamplingScheme

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#206]
https://vocab.ices.dk/?ref=1664

Better more concise codes, description acronyms needs to be spelled out

**Comment by Osanna123** [comment]
Descriptions and codes need reviewing, RDBES core group
Avoid ' ' and '()' in the codes

**Comment by cekv** [comment]
RDBES core group: The SWE test codes are Nuno's codes and can be made invisible at the time being and deleted when more permanent codes are taking their place in the future. In the future it is up to the Data manager to make codes more unifiable - the codes now are national and cannot be changed.

**Comment by cekv** [comment]
ask if we can put National in the Codetype desc. and check spelling in CT
