### ISSUE TITLE
RS_RDBES code review: RS_SamplingType

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#207]
https://vocab.ices.dk/?ref=1667 

better description - maybe adding this to another codetype? SMTYP?

**Comment by Osanna123** [comment]
RMG suggests to RDBES Core Group to rename to SamplingLocation as Sampling type (methodology) is not relevant to the codes.

**Comment by cekv** [comment]
RDBES core group: CodeType name change to suggested SamplingLocation was rejected , Location for them is something different, they will try and think of a better name - Data manager to keep them to their promise.

**Comment by cekv** [comment]
"done" should be changed to "performed"
CodeType naming needs to be discussed further with @neil-ices-dk , @EjazAtIces , @HenrikK-N

**Comment by pcrjoana** [comment]
The following suggestions will be brought to the RDBES core group: "SamplingPlacement" and "SamplingContext". The RDBES core group are to come back with a choice between those two.

**Comment by pcrjoana** [comment]
We should also fix the typo in one of the codes ("at" instead of "ar").
