### ISSUE TITLE
RDBES code review: RS_Subpolygon

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#208]
https://vocab.ices.dk/?ref=1626

delete? Only one code more as a flag

**Comment by Osanna123** [comment]
If there are no real codes, but there is a plan to add some in the future, make the CodeType invisible. Otherwise - delete.
Improve the code description, if the codetype stays.

**Comment by cekv** [comment]
Henrik agreed this to be deleted

**Comment by cekv** [comment]
Deleted 21/12-2021
