### ISSUE TITLE
RDBES code review: RS_UpperHierarchy

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#214]
We kind of already looked at this when we looked at RS_LowerHierachy
https://vocab.ices.dk/?ref=1627

Does the description needs to be specific? Or is it ok to leave as is

**Comment by cekv** [comment]
Please explain the codetype, by providing better descriptions for codetype and codes.

**Comment by cekv** [comment]
Will be made invisible until better description is provided by RDBES group

**Comment by cekv** [comment]
Code descriptions are updated, waiting for Henrik regarding improvement on CodeType description

**Comment by odontaster** [comment]
@cekv  can you confirm thi shas also been implemented as #268? thanks
