### ISSUE TITLE
WGBIOP: PreparationMethod and SampleType request changes to CodeType values

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#22]
The request form can be found at:
https://forms.office.com/Pages/DesignPage.aspx#Analysis=true&FormId=ziCy4DVXaESR3wXK5f8f3BWA1fNSx4tPsQVXsp2REGRUQkZWSTBTVVZDVVVSWUxMNVBXSkUxSk1NWCQlQCN0PWcu&Token=96ff5a3d226c4a92a1a2159cb052a615&TopView=SurveyResults

modified text:

ID | 1
-- | --
Start time | 11/27/20 8:29:11
Completion time | 11/27/20 8:36:14
Email | anonymous
Name |  
Requested by | WGBIOP
Request entered by | Joana Ribeiro
Requester email | joana.ribeiro@ices.dk
vocabulary type change | Code type (new);Code value (new);
vocabulary reference | http://vocab.ices.dk/?ref=1511     http://vocab.ices.dk/?ref=1507
Reason for change | Recommendation from expert group. To enhance SmartDots, WGBIOP would like   to have additional values for both **PreparationMethod** and **SampleType**, and they   would also like to create a new codetype called **ObservationMethod**: Observation methods are proposed by WGBIOP for two reasons. Firstly, the methods used across age reading and maturity staging laboratories are different and SmartDots is the database where this information should be stored and secondly, this is important information to include in the readers/stagers expertise when comparing readers in calibration events
Impact of change | Low
Does the proposed change exist in another   ICES vocabulary code type or an external code standard | No
If yes, please specify |  
Proposed   time when the change should take affect from

**Comment by neil-ices-dk** [comment]
@pcrjoana we will need to have some additional information on the new CodeType 'ObservationMethod' can you provide details please

**Comment by pcrjoana** [comment]
@neil-ices-dk it turns out that observation method was proposed by WGBIOP to be included in SmartDots, and not by WGSMART. It's difficult to follow this, as both have Julie as chair.

This is what Julie wrote about ObservationMethod:
Observation methods are proposed by WGBIOP for two reasons. Firstly, the methods used across age reading and maturity staging laboratories are different and SmartDots is the database where this information should be stored and secondly, this is important information to include in the readers/stagers expertise when comparing readers in calibration events

**Comment by neil-ices-dk** [comment]
@pcrjoana i have modified title and text appropriately, see top of issue;
We need more information - do you have a list or reference to the proposed labels that will constitute 'ObservationMethod'?

**Comment by pcrjoana** [comment]
@neil-ices-dk Please find the proposed codes and code type attached.
[SmartDots_PreparationMethods_FINAL (5).xlsx](https://github.com/ices-eg/DIG/files/5653339/SmartDots_PreparationMethods_FINAL.5.xlsx)

**Comment by cmspinto** [comment]
Looks good and this should be implemented before next WGSMART meeting

**Comment by neil-ices-dk** [comment]
**For ObservationMethod:**
@cmspinto and @pcrjoana is there a compelling argument to not include this in the existing METOA codtype  //vocab.ices.dk/?ref=173 which includes similar concepts?:


MIC-EM | Microscope - electron microscope | METOA | False | 2006-10-23 | 2006-10-23
-- | -- | -- | -- | -- | --
MIC-FL | Microscope - fluorescence microscope | METOA | False | 2013-05-06 | 2013-05-06
MIC-LM | Microscope - light microscope | METOA
IMA | Image analysis - manual | METOA | False | 2006-10-23 | 2011-08-01
-- | -- | -- | -- | -- | --
IMA-SW | Image analysis - software | METOA | False | 2014-07-07 | 2014-07-07

**Comment by Osanna123** [comment]
There are quite a few references running in parallel with the Env. format. Previously, a decision was made (by me) to not re-use the existing vocabs to avoid interfering with the Env. DATSU checks, and for the Env.submitters not to use the codes that might not apply to them. 
The vocabs are:  
SampleType vs. MATRX
PreparationMethod vs. METPT

PreservationMethod and ObservationMethod should also be considered towards the existing METST, METFP, and METOA

**Comment by neil-ices-dk** [comment]
is the solution to include the code relation in vocab so it is easy for SMARTDOTS to reference/see the valid codes from a larger list i.e METOA?

**Comment by neil-ices-dk** [comment]
@Osanna123 and @pcrjoana to discuss how to implement

**Comment by neil-ices-dk** [comment]
Agreed to follow-approach

> is the solution to include the code relation in vocab so it is easy for SMARTDOTS to reference/see the valid codes from a larger list i.e METOA?

**Comment by pcrjoana** [comment]
The new PreparationMethod codes were added. The codes that are no longer to be used in SmartDots were unlinked from the dataset, but they were not deprecated, since these are used in DATRAS.
The new SampleType codes had already been added.

Julie from WGSMART has been updated in regards to using METOA instead of creating ObservationMethod, and METST and METFP instead of PreservationMethod. She was positively impressed regarding the flexibility of the system!

Not all codes requested for ObservationMethod fit the codes existing in METOA. 
@Osanna123 should I use a particular system for creating the codes? Also, please take a look to the code by code questions below.

Image-based (Zooscan, zoomcam, other setups) - this seems to be a slightly more generic version of IMA-ZS (Image analysis - ZooSCAN). Would it be a problem to change the description to include "and other similar systems"?

The codes below are at a more detailed level, should they be coded IMA-ZS-TL (for transmitted light in this case), etc?
Image-based,   transmitted light
Image-based, reflected light
Image-based,  polarized light
Image-based, dark-field illumination

The codes below seem to be at a more detailed level than MIC-LM (Light microscope). Are you OK with me using a system similar to the one proposed above? 
Microscope-based,  mixed light
Microscope-based, transmitted   light
Microscope-based, reflected   light
Microscope based,  polarized light
Microscop-based, dark-field illumination

Finally, I think "De visu" fits VISO (Visual observation/identification).
Thank you in advance!
