### ISSUE TITLE
Review of ODV for ocean.ices.dk purposes

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#23]
also for @HjalteParner

**Comment by neil-ices-dk** [comment]
the notice and background information is now published on the ICES website and we are in the process of writing to regular data providers with the same message
[format change page](http://ices.dk/data/data-portals/Pages/ocean-format.aspx) 
![image](https://user-images.githubusercontent.com/23527005/101357946-77258a00-389a-11eb-975c-ba419ce2f4e9.png)

**Comment by sjurl** [comment]
I have compiled a list of people who have shown interest in participating in reviewing the list. The list of people is available at the [DIG sharepoint ](https://community.ices.dk/Committees/DIG/DIG%20Intersessional%20Meeting%2028%20September/01.%20Meeting%20documents/ICES%20Ocean%20format%20review.docx)

**Comment by HjalteParner** [comment]
Thanks @sjurl, I will send out a doodle by the of today or Monday at latest.

**Comment by neil-ices-dk** [comment]
@HjalteParner is there an update on this issue/supporting document to add in? thanks :)

**Comment by neil-ices-dk** [comment]
> 
> 
> @HjalteParner is there an update on this issue/supporting document to add in? thanks :)

Hi Hjalte, Sjur and i are organising the DIG agenda and we will need to know if you will have a document to present, and whether you will need a slot for discussion feedback in connection with a general presentation of it in the Wednesday afternoon Data Centre slot.

**Comment by HjalteParner** [comment]
Hi Neil and Sjur,

Thanks and yes, I think it might be appropiate to present the format in plenum, as it will concern most people in the room either direct or indirectly. Based on comments we will know if the subgroup establish need to meet again or if we are ready to rock and roll.

FYI we had our subgroup meeting a while ago and I guess the new ICES ODV format presented was recieved well overall despite a few unresolved decisions to be made on vocabularies L05, L22 and data roles to be used for acknowlegdement.

For the later Neil put my attention to the ISO 19115 Role codes which seems perfect. Now we just need to decide which ones to include as mandatory and optional - we already enabled multiple roles in the data model made.

I will add another issue on how to handle CSR's

**Comment by sjurl** [comment]
New dataformat in effect as of 1. july. 

A few submissions using the new format already. ICES facilitating data transformation for a while but this will be disconitnued.
