### ISSUE TITLE
Biodiv Cetaceans - PositionFix

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#232]
Handheld GPS
Mobile phone location
Platform onboard system
Manual position

# This needs a better name. It's basically what they used to take the coordinates.

**Comment by Osanna123** [comment]
Suggested new CodeType name PositioningDevice
Need definition of the 'Manual position'.

**Comment by pcrjoana** [comment]
'Manual position' is reading the position from a chart. Usually used if all other instruments fail.
