### ISSUE TITLE
Continuous underwater noise

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#240]
Submitters for CUWN need multiple codes added to different code types.

- [x] To CalibrationProcedure (https://vocab.ices.dk/?ref=1591) they need Closed pressure chamber/pistonphone (125 Hz) added.
- [x] To ProcessingAlgorithm (https://vocab.ices.dk/?ref=1590) they need JOM (reference: Crawford, N., Robinson, S. and Wang, L. (2018) Standard procedure for equipment performance,calibration and deployment. Report of the EU INTERREG Joint Monitoring Programme for AmbientNoise North Sea (Jomopans), August 2018) added.
- [x] To HydrophoneType (https://vocab.ices.dk/?ref=1584) they need Neptune D/707H added.
- [ ] To RecorderType (https://vocab.ices.dk/?ref=1585) they need "other" or "cabled to computer" added - I'm waiting for feedback on this one.

**Comment by pcrjoana** [comment]
The checked codes are approved.

**Comment by Osanna123** [comment]
This is up for a discussion at EN NOISE, a new issue can be opened if necessary
