### ISSUE TITLE
RDBES: Sampler (code type) added new code 'Electronic Monitoring' description 'Electronic Monitoring' 

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#247]
Sampler (code type) added new code: 'Electronic Monitoring', description. 'Electronic Monitoring'

**Comment by Osanna123** [comment]
#158

**Comment by Osanna123** [comment]
ok, but better description would help.
@cekv consider a shorter code, definitely without a space.

**Comment by cekv** [comment]
RDBES core group: Needs to discuss the EM/Imagery debacle and see if they are both needed.
