### ISSUE TITLE
Large request of ASFIS codes to FAO. Criteria for prioritization required.

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#25]
Henrik K-N has requested for new ASFIS codes for 380 different taxa, most of them invertebrates, but also algae etc, probably bycatch species. I believe this is required for RDBES where both ASFIS and AphiaID are needed.

FAO has replied positively but they ask for some kind of prioritization. We have to posibilities:

- Ask for ASFIS codes for higher taxonomical levels, maybe family or order, that could be used more widely. 
- If HKN could provide some estimate of the amount of data received for the required taxa, we could prioritize the most reported.

Any ideas are welcome. Best regards.

**Comment by odontaster** [comment]
[Species list AphiaId mapping to ASFIS.xlsx](https://github.com/ices-eg/DIG/files/5701224/Species.list.AphiaId.mapping.to.ASFIS.xlsx)

It would be good to have @pcrjoana @Osanna123 @neil-ices-dk feedback. What is Henrik K-N user in github?

**Comment by neil-ices-dk** [comment]
it's Henrik Kjems-Nielsen

**Comment by neil-ices-dk** [comment]
@odontaster in terms of prioritization, i don't think abstracting to the higher taxonomic level is the way to go; seeing as RDBES isn't a production system, it must be possible to take this in chunks of species according to what is likely to be submitted in the test data; as you say HKN should prioritise that

**Comment by neil-ices-dk** [comment]
@HenrikK-N to prioritise list of species; see above

**Comment by HenrikK-N** [comment]
I will return soon with a prioritised list.

**Comment by pcrjoana** [comment]
@HenrikK-N FYI, the new version of ASFIS list is going to be published in April. :-)

**Comment by HenrikK-N** [comment]
The prioritised list is attached.
[Species AphiaId mapped to ASFIS prioritised.xlsx](https://github.com/ices-eg/DIG/files/6205280/Species.AphiaId.mapped.to.ASFIS.prioritised.xlsx)

**Comment by pcrjoana** [comment]
The prioritised list was sent to the FAO contact.

**Comment by pcrjoana** [comment]
Cecilia to look at the list when she has the time.

**Comment by HenrikK-N** [comment]
Data submitter/core group are asking if the missing FAO codes are inserted in the SpecASFIS list. Have you heard back from FAO?

**Comment by HenrikK-N** [comment]
What is status on the missing FAO codes? Have you heard back from FAO?

**Comment by odontaster** [comment]
@odontaster will send a catch up email on this to Stefania Savore. 
From the original list at least 70 codes already have an ASFIS code.

**Comment by odontaster** [comment]
@HenrikK-N  Just got repky from FAO. The commit to have the first 50 codes in priority order by week 7
[species for asfis checked_final.xlsx](https://github.com/ices-eg/DIG/files/7934733/species.for.asfis.checked_final.xlsx)
.

**Comment by odontaster** [comment]
this list has been added to reco and linked to AphiaI
[Species for asfis checked_final_codes_220217.xlsx](https://github.com/ices-eg/DIG/files/8213562/Species.for.asfis.checked_final_codes_220217.xlsx)
D

**Comment by neil-ices-dk** [comment]
@odontaster to also look at new version of released ASFIS codes (August)

**Comment by odontaster** [comment]
I checked SpecASFIS against the new list and there are huge differences. 12838 more codes in FAO list.
Also, detected a few codes in SpecASFIS that do not exist in FAO list:
"BWP" "IHU" "KIJ"
Links between ICES Aphia and Asfis are around 537 species (matching with Description, so could be some more).
Links between ICES Aphia and FAO asfis are around 1045.
Should we import all Asfis and link to as many aphia as possible?

**Comment by Osanna123** [comment]
@odontaster to have a look at the SpecASFIS not in the ASFIS list
@odontaster bulk upload of the ASFIS codes needed to map to the SpecWorms is ok.

**Comment by odontaster** [comment]
Found correspondence in June informing about IHU changing to KSP. Will change now.

**Comment by odontaster** [comment]
Sent request to Stefania Savore about the other two codes.

**Comment by odontaster** [comment]
No answer so far from Stefania Savore. Compared RECO SepcASFIS with last ASFIS list, from the ones not in reco, checked which ones have the same description as codes in SpecWoRMS.
This way, 507 new SpecASFIS were added to RECO. They all have links to their SpecWoRMS and to RDBES dataset.

**Comment by odontaster** [comment]
Resend email to FAO using general fish stats mailbox.

**Comment by odontaster** [comment]
Reply from Stefania Savore:
One is BWP, which now shows up as QDQ, but according to the email below it did not change. I confirm the code remains BWP.
The other mismatch is KIJ, Kajikia audax which shows up now as MLS. The code to be used is MLS as it is a change of scientific name from Tetrapturus audax (already MLS) to Kajikia audax

**Comment by odontaster** [comment]
Created new issue for remaining species.
