### ISSUE TITLE
Create Year 2022

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#251]
In order to implement #199 I would rather link the new code to year 2022, so we don't have issues with SID or maybe elsewhere.

**Comment by odontaster** [comment]
I create Year 2022 in RECO but keep it invisible until the time comes.

**Comment by odontaster** [comment]
Pending to link the year to StockCode and Surveys, is there an easier way to do this?

**Comment by cekv** [comment]
First part is done
@odontaster After new year, updates will be needed to RECO (all relevant code relations) + SID Mike
