### ISSUE TITLE
RDBES: Deprecate code '<8' and add '<6' and '6-<8'

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#252]
The following is requested for code type 'RS_VesselLengthCategory':
Deprecate code '<8' 
Add code: '<6', description 'Vessel length less than 6 meter'
Add code:  '6-<8', description 'Vessel length between 6 meter and less than 8 meter'.

**Comment by cekv** [comment]
For RMG:
RS_VesselLenghtCategory: https://vocab.ices.dk/?ref=1633 
It should be suggested that all code descriptions needs to be descriptive (written not code copy)
Question is if this code type and this BYC_VesselLRange ( https://vocab.ices.dk/?ref=1502) can be made into one code type (eg VesselLRange or VesselLengthCategory)?

**Comment by cekv** [comment]
RMG: yes to comments

**Comment by cekv** [comment]
After discussing this with Henrik, I will contact the BYC chairs and Carlos to see if it would be possible for them shift to (RS_)VesselLengthCategory, instead of the other way around. Since future bycatch data submissions are supposed to go through RDBES.

**Comment by odontaster** [comment]
@cekv  this is linked to issue #263 right? maybe we can close this one?
