### ISSUE TITLE
RDBES Code Review: RS_FishingValidity

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#256]
RS_ FishingValidity https://vocab.ices.dk/?ref=1602

I suggested to Henrik  and Ejaz to make this into a ValidityFlag, they agreed - to be used by other DBs (DATRAS, Acoustic, etc.).

**Comment by pcrjoana** [comment]
@cekv and @odontaster  to talk with @vaishav and @HjalteParner about whether they can apply a generalised code type ValidityFlag to their datasets/historical data, to replace the project specific code types with the same purpose.

**Comment by pcrjoana** [comment]
@HenrikK-N and the rest of the RDBES team have agreed on a generalised ValidityFlag. The data managers suggest renaming RS_FishingValidity to ValidityFlag.

**Comment by cekv** [comment]
ValidityFlag CodeType created and RS_FishingValidity will be deleted
