### ISSUE TITLE
STAGE new code for spat

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#26]
We were requested to create a new code for the mollusk dev.stage spat in http://vocab.ices.dk/?ref=52. Suggested code 'SPAT'. More info is in the form
https://forms.office.com/Pages/DesignPage.aspx#Analysis=true&FormId=ziCy4DVXaESR3wXK5f8f3BWA1fNSx4tPsQVXsp2REGRUQkZWSTBTVVZDVVVSWUxMNVBXSkUxSk1NWCQlQCN0PWcu&Token=96ff5a3d226c4a92a1a2159cb052a615&TopView=SurveyResults

**Comment by neil-ices-dk** [comment]
approved
