### ISSUE TITLE
Request to add the CECAF Divisions:

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/DIG#262]
In fact, they are not an ICES but FAO/CECAF area. We've named these samples with code 34 (Atlantic, Eastern Central), but they are specifically included in the CECAF Division 34.1.2 (https://www.fao.org/fishery/area/Area34/en). It would be the same if we'd included Moroccan, Mauritanian (or from the other riparian countries) samples: that Major Area 34 is too general. Maybe, the subdivision could be added to the list.

About the skype, no problem. But I'll be busy during the next week. When would you be available?

Many many thanks again for managing all the issues so quick!

Regards,

Alba

**Comment by cmspinto** [comment]
Some of the CECAF areas are in EU waters like Madeira and Canarias:

https://datacollection.jrc.ec.europa.eu/wordef/fishing-area

**Comment by Osanna123** [comment]
@pcrjoana to add the codes to https://vocab.ices.dk/?ref=358 with references from https://www.fao.org/fishery/area/Area34/en

**Comment by pcrjoana** [comment]
Joana to do this.

**Comment by pcrjoana** [comment]
@cmspinto We now have codes for 34.1.1, 34.1.2, and 34.1.3.
