### ISSUE TITLE
Aphia codes - bulk import

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#266]
This is for backwards approval.

We added a plethora of Aphia ID to SpecWoRmS in the scope of the cetaceans project. 

There are the codes:

2688	Cetacea
148723	Odontoceti
148724	Mysticeti
136980	Delphinidae
136984	Phocoenidae
136979	Balaenopteridae 
136983	Monodontidae
136986	Ziphiidae
136978	Balaenidae
159022	Eubalaena
137017	Globicephala 
137026	Tursiops 
137094	Delphinus delphis
137111	Tursiops truncatus
137107	Stenella coeruleoalba
137098	Grampus griseus
137100	Lagenorhynchus acutus
137101	Lagenorhynchus albirostris
137108	Stenella frontalis
137105	Stenella attenuata
137102	Orcinus orca
137096	Globicephala macrorhynchus
137097	Globicephala melas
137104	Pseudorca crassidens
137087	Balaenoptera acutorostrata
137089	Balaenoptera edeni
137088	Balaenoptera borealis
137090	Balaenoptera musculus
137091	Balaenoptera physalus
137092	Megaptera novaeangliae
137116	Monodon monoceros
137119	Physeter macrocephalus
343899	Hyperoodon ampullatus
137121	Mesoplodon bidens
137126	Mesoplodon mirus
137127	Ziphius cavirostris
137122	Mesoplodon densirostris
137123	Mesoplodon europaeus
137086	Balaena mysticetus
159023	Eubalaena glacialis
137095	Feresa attenuata
136982	Kogia 
137113	Kogia breviceps
159025	Kogia sima
137115	Delphinapterus leucas
220222	Eubalaena australis
254974	Eubalaena japonica
231405	Balaenoptera bonaerensis
343896	Balaenoptera omurai
137112	Eschrichtius robustus
231424	Caperea marginata
254976	Cephalorhynchus commersonii
254977	Cephalorhynchus eutropia
254978	Cephalorhynchus heavisidii
254979	Cephalorhynchus hectori
137099	Lagenodelphis hosei
254980	Lagenorhynchus australis
383563	Lagenorhynchus cruciger
254981	Lagenorhynchus obliquidens
231434	Lagenorhynchus obscurus
254975	Lissodelphis borealis
231414	Lissodelphis peronii
148732	Orcaella brevirostris
137103	Peponocephala electra
344009	Sotalia guianensis
204528	Sousa
220226	Sousa chinensis
383586	Sousa plumbea
816452	Sousa sahulensis
254970	Sousa teuszii
137106	Stenella clymene
137109	Stenella longirostris
137110	Steno bredanensis
254983	Tursiops aduncus
446125	Neophocaena asiaeorientalis
254985	Neophocaena phocaenoides
254971	Phocoena dioptrica
343897	Phocoena sinus
343898	Phocoena spinipinnis
254987	Phocoenoides dalli
254964	Pontoporia blainvillei
242606	Berardius arnuxii
242608	Berardius bairdii
343900	Hyperoodon planifrons
231418	Indopacetus pacificus
231430	Mesoplodon bowdoini
254990	Mesoplodon carlhubbsi
231407	Mesoplodon ginkgodens
137124	Mesoplodon grayi
137125	Mesoplodon hectori 
384422	Mesoplodon hotaula
231429	Mesoplodon layardii
254992	Mesoplodon perrini
231409	Mesoplodon peruvianus
254991	Mesoplodon stejnegeri
254993	Mesoplodon traversii
231433	Tasmacetus shepherdi

**Comment by cekv** [comment]
This list was bulk imported by Mehdi.
