### ISSUE TITLE
RDBES: Codetype RS_LowerHierarchy update of the 4 descriptions 

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#267]
The description of all the codes for codetype RS_LowerHierarchy should be updated according to the following:

Description for code A: 
From: Length stratified biological samples, Frequency Measure (FM) and Biological Variable (BV)
To: Length or weight stratified biological samples, which require both Frequency Measure (FM) and Biological Variable (BV) RDBES tables

Description for code B: 
From: Only length frequency data is taken from sample(s)/subsample(s) (Frequency Measure (FM)) 
To: Only length or weight frequency data is taken from samples/subsamples, which require only the Frequency Measure (FM) RDBES table

Description for code C:
From: All individuals in the sample/subsample are biologically analysed (Biological Variable (BV)) 
To: Only biological data is taken from samples/subsamples, which require only the Biological Variable (BV) RDBES table

Description for code D: 
From: No length measurements or biological analyses of samples
To: No length measurements or biological analyses of samples, neither Frequency Measure (FM) or Biological Variable (BV) RDBES tables required

**Comment by cekv** [comment]
#197

**Comment by cekv** [comment]
Spell check, singular /plural

**Comment by cekv** [comment]
Implemented 22/12-2021
