### ISSUE TITLE
RDBES: Codetype RS_UpperHierarchy update descriptions and codetype

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#268]
The Core Group suggest to change code type name to 'RDBESupperHierarchy'. Because this code type is so specific that it should indicated in the name.

All the descriptions should be updated from:

Fisheries sampling according to hierarchy X

To the following:

Commercial fisheries sampling according to RDBES hierarchy X, see RDBES documentation for further details

**Comment by cekv** [comment]
#214

**Comment by cekv** [comment]
Upper will be capitalised. "See documentation" will be on the level of CodeType

**Comment by odontaster** [comment]
@odontaster check again with Henrik. Maybe Ejaz knows.
