### ISSUE TITLE
RLABO new codes

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#27]
requests for 5 new RLABO codes:
DE:
EDMO code: 5326
ICES code proposal: WMHG
Description: Werkstätten Materialhof, Rendsburg

EDMO code: 5327
ICES code proposal: KFOG
Description: KÜFOG GmbH, Bremen

EDMO code: 5328
ICES code proposal: BASG
Description: Biologische Arbeiten Steuwer

IE: 
IFIE Inland Fisheries Ireland, Dublin

PT:
IPMA Instituto Português do Mar e da Atmosfera, I.P.

**Comment by neil-ices-dk** [comment]
for reference EDMO mappings:
IPMA https://edmo.seadatanet.org/report/3288
IFIE https://edmo.seadatanet.org/report/980

Approved
