### ISSUE TITLE
New CodeType (Cetaceans database)

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#271]
The Cetaceans format has a field called PlatformInstance, that is used to identify which platform (Primary or Secondary) was used to sample data. This is to be used in the cases where a double platform vessel (two stories) was used for the survey.
The reason why it's relevant to identify is that there are data that will be different between primary and secondary platforms (as for example platform height).

The codes needed would be:
- Primary
- Secondary

**Comment by Osanna123** [comment]
new CodeType 'Order'
codes can be 1 and 2
