### ISSUE TITLE
DATRAS new code for TS_AgeSource

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#272]
WGDG requests to add Length Based code for seeded ages

**Comment by odontaster** [comment]
LB - Based on length for seeded ages

Get more information on what seeded ages are (for long description maybe) and proceed

**Comment by odontaster** [comment]
Seeded ages are Ages infered from length measurements.

**Comment by odontaster** [comment]
We should use the same terminology as in AC_AgeSource
//vocab.ices.dk/?ref=1482

Also, they ask for a code for Winter or growth rings, please see
https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/1

**Comment by pcrjoana** [comment]
Winter rings are a unit rather than an age source. The age source would be Otolith or Scale.

**Comment by pcrjoana** [comment]
We accept LB.
