### ISSUE TITLE
Vocabulary search engine - making it more user friendly

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#274]
The search engine at vocab.ices.dk seems to search for the specific combination of words inserted and not for each word individually or in combination. This makes it hard to search for some vocabularies.

An example is ObservationMethod. It doesn't appear if you search "observation method", but it does appear if you search "method of observation", since the latter is the vocabulary's description.

**Comment by odontaster** [comment]
Move this to TFS and communicate with Mehdi.
