### ISSUE TITLE
Update code ‘InfoWeights’ under code type 'BiologicalMeasurementType'

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#275]
Update code ‘InfoWeights’ under code type 'BiologicalMeasurementType' from ‘InfoWeights’ to ‘InfoConversionfactor’.

**Comment by HenrikK-N** [comment]
Looking at the suggestion above from the Core Group, I think another possible update could be from ‘InfoWeights’ to ‘InfoWeightConversionfactor’ or ‘InfoWeightConversion’.
Since the following two also are description updates under code type 'BiologicalMeasurementType' I add them here:
For the two codes 'InfoGonad' and 'InfoLiver' the descriptions should be more general, therefore the two following are suggested: 
For code 'InfoGonad' updated desc. from ‘Gonad weight for the specimen is available’ to ‘Gonad information for the specimen is available’.
For code 'InfoLiver' updated desc. from ‘Liver weight for the specimen is available’ to ‘Liver information for the specimen is available’.

**Comment by odontaster** [comment]
Code should be InfoConversionFactor.

**Comment by odontaster** [comment]
Done
