### ISSUE TITLE
Behaviour codes' descriptions

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#277]
Some of the codes in Behaviour (https://vocab.ices.dk/?ref=1709) have a "Cetaceans:" prefix. This is quite confusing, because not all codes used in JCDP have this prefix. 
Can ESAS agree to revert the codes to having (cetaceans) at the end?

**Comment by neil-ices-dk** [comment]
> Some of the codes in Behaviour (https://vocab.ices.dk/?ref=1709) have a "Cetaceans:" prefix. This is quite confusing, because not all codes used in JCDP have this prefix. Can ESAS agree to revert the codes to having (cetaceans) at the end?

agree, this is confusing and contradicts our edict that we would not use prefixes in code types/code labels

**Comment by pcrjoana** [comment]
The "Cetaceans:" will be moved to long description.
Joana to do this.

**Comment by Osanna123** [comment]
done
