### ISSUE TITLE
Two new stock codes - split of her.27.6a.7bc

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#279]
A result of the recent benchmark for the herring stocks her.27.6a7bc is that the stock will now be two stocks.

Suggested codes:
her.27.6aS7bc and her.27.6aN.

**Comment by odontaster** [comment]
@sarahlmillar  and @JetteFredslund  could we get some good descriptions of the stocks, mostly related to the North South division?
Old stock wont be linked to year from now on in IC. Details will be in long description of old and new.
Need to check SID is updated, that is manual.

**Comment by cekv** [comment]
Reply from Sarah:
"Sorry but just be aware we need ACOM to sign off on the findings of the benchmark before we can commit to the split, so its good to have it all in place and I am 99% sure it will go through but lets be ready for all eventualities".

**Comment by odontaster** [comment]
Created the stocks yesterday as they were needed to upload to SAG. Details on location of the north-south split provided by the stock assessors.
Temporarily they are:
Code: her.27.6aN
Description: Herring (Clupea harengus) in Division 6.a North (North of 56°00’N and East of 07°00’W), autumn spawners (West of Scotland)
Long Description: Split from her.27.6a7bc in 2022

Code: her.27.6aS7bc
Description: Herring (Clupea harengus) in Division 6.a South (South of 56°00’N and West of 07°00’W) and 7.b-c (northwest and west of Ireland)
Long Description: Split from her.27.6a7bc in 2022
Already linked to year 2022, and unlinked the previous code of year 2022.
Stock assessors also informed on the surveys to be linked to these stocks. The old survey was linked to 4 surveys
![image](https://user-images.githubusercontent.com/18613829/168026206-8adfe080-5e45-4f5c-8c75-c83dd155d3fd.png)

However they suggest some error on this, as they only use data form Malin Shelf Herring Acoustic Survey.

**Comment by Osanna123** [comment]
@odontaster pls check the Benchmark stock assessment annexes for area and survey referencing.
Implementation in IC is pending.

**Comment by odontaster** [comment]
implementation in IC is done.
Pending review of Benchmark and Stock annexes

**Comment by odontaster** [comment]
Stock Annexes explain well the area and surveys used (only Malin Shelf), but they are still unpublished. Unless we want the link to them, we can close this issue.
