### ISSUE TITLE
DATRAS User Handbook

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#280]
All documents in DATRAS web will be reviewed this year by both survey groups and DATRAS team at the secretariat.

https://www.ices.dk/data/data-portals/Pages/DATRAS-Docs.aspx

Most documents are not published in the library, so we (DATRAS team) think a User Handbook would be the right place to publish all procedures and specifications.

DATRAS governance group believes this topic should be discussed in DIG as it applies to all ICES databases.

We ask DIG for feedback on the need to publish these documents in a different form and if so, some guidance on how to better proceed.

**Comment by sjurl** [comment]
To be presented during the May/June DIG meeting

**Comment by sjurl** [comment]
DIG thinks there is a need to publish these documents. The work should start with an inventory of needs collected in DSTSG @jensr

**Comment by sjurl** [comment]
Closed for DIG
