### ISSUE TITLE
New CodeType for the VME data format

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#283]
WGDEC made changes to the VME reporting format at the last meeting (Annex 5, 2021 WGDEC report). They need these to be implemented before we can send out the data call. 

They are asking for a CodeType called "VMEQuantMethod" with the codes:
Presence
Count
Weight
Density
PercentCover
SACFOR
[Working Group on Deep-water Ecology (WGDEC).pdf](https://github.com/ices-eg/DIG/files/8175748/Working.Group.on.Deep-water.Ecology.WGDEC.pdf)

Link to data format: http://www.ices.dk/data/Documents/VME/VME_Reporting_Format.zip

**Comment by odontaster** [comment]
RMG suggest CodeType to be QuantificationMethod and include reference to VME in the description.
We suggest Codes to be shorter, kind PR, DN, CN... so the descriptions can be changed if needed without having to necesarily change the codes.
