### ISSUE TITLE
new MATRX code for EEA ETC/EMODnet

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#29]
Template with details is filled out. New code for rhizome is needed. Suggestive code is 'RHIZOME', which fits the max field width of 7 char.
[req.form7.pdf](https://github.com/ices-eg/DIG/files/5724498/req.form7.pdf)

**Comment by neil-ices-dk** [comment]
thanks @Osanna123 for clarity, which concept(s) is this equivalent to in SeaDataNet (S26/P01/P02)?

**Comment by HansMJ** [comment]
@neil-ices-dk @Osanna123 
Rhizome is a 'sub component' S12 (see [Rhizomes](http://vocab.nerc.ac.uk/collection/S12/current/S1251/)) of the Biological Entity S25

**Comment by Osanna123** [comment]
@HansMJ MATRX code RHIZOME is now added. Please note that presently BODC vocab points to the wrong MATRX code BC (something for them to fix)

**Comment by HansMJ** [comment]
Thanks Anna. Strange with the wrong link at BODC, I had not noticed that before. I will write Gwen
