### ISSUE TITLE
ENV2022-04-06 new SMTYP

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#290]
https://vocab.ices.dk/?ref=152
request for a new entry
BTS-AB - Bürkle TeleScoop with angular beaker
See here for details: https://www.buerkle.de/en/telescoop

**Comment by pcrjoana** [comment]
The description will be changed slightly so that the brand isn't the focus.

**Comment by Osanna123** [comment]
![image](https://user-images.githubusercontent.com/17157764/162763858-d2b023c5-a9ac-4c7f-9bc7-73d0b8892c16.png)
