### ISSUE TITLE
Add FAO areas to vocab:

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/DIG#293]
Project: SmartDots

How to add the AreaCode of samples from the area FAO 34.1.2 (Canary Islands) and 34.1.1 (Morocco)? It is only possible to put area 34. Can't we distinguish between these areas?

**Comment by Osanna123** [comment]
see #262 for 34.1.2
add also 34.1.1 and 34.1.3, check with the requester if this is enough

**Comment by Osanna123** [comment]
@pcrjoana i can see the codes are created. Can we close this issue?
