### ISSUE TITLE
Bycatch: Subset of SpecWorms linked to Dataset, Ecoregion and Year

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#296]
For WGBYC 2022 data call, a list of species to be reported by ecoregion will be available. For the time being is just informative, no checks will be associated to it. However, we have been asked to flag in the database those species not in the list. 
The list has 230 species in all.
We will check whether they are already in SpecWorms and if not will be introduced.
We will link the SpecWorms code to Dataset Bycatch.
We will link the SpecWorms code to one or several ecoregions. Not so sure about this last point. Please suggestions.

**Comment by Osanna123** [comment]
Need more info on the suggested mapping to Ecoregions
