### ISSUE TITLE
2 - Draft common template for limited data usage licenses and apply to existing examples in ICES

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#3]

**Comment by neil-ices-dk** [comment]
there have been regular meetings of the sub-group led by @davidcurrie2001;
the latest status is that we have 3 drafts:
RDB/RDBES
VMS
Biodiversity (covering VME's, Seals and Birds)

Timeline:
- complete templated drafts by end of January;
- WGDEC to review in February
- Submit to SCICOM mid-term as part of the overall package of licence/policy change

**Comment by neil-ices-dk** [comment]
from meeting notes:
ICES Restricted Data License Template
11/1/2021
Present: David Currie, Christian Dorrien, Neil Holdsworth, Chris Moulton
Apologies: Ingeborg de Boois, Laura Hanley, Taco de Bruin
•	Previous actions
o	**ACTION**: NH to add change-log to biodiversity draft 
 - Carried forward
 - There are ICES guidelines for change logs – NH reviewed and said the main thing we were missing is a column describing the importance of the change (e.g. minor / major) – this should be added
o	**ACTION**: CD to make agreed changes to draft VMS license and re-circulate
- Carried forward 
o	**ACTION**: NH to check VMS Conditions against biodiversity license to see if anything can be added
 - Carried forward
•	RDBES
o	The draft RDBES data license was reviewed for consistency with the VMS and Biodiversity data licenses.
o	Changes were agreed to bring it closer in alignment with the other documents
 **ACTION**: DC to make changes and circulate document before next meeting
•	Next meeting: 11:00 CET Wednesday 27th Jan
o	Final drafts of all documents should be ready for final review/comments

**Comment by neil-ices-dk** [comment]
Biodiversity templated and reorganised (see comments in margin); 
[Biodiversity-License](https://community.ices.dk/Committees/DIG/Master%20documents/Data-Policy-and-licences/ICES-Data-Licence-Biodiversity.docx)

**Comment by neil-ices-dk** [comment]
all templates are now in final draft; a cover message is to be formulated, so that the governance groups can be informed of this (planned message by 29/01)
This will allow time ahead of SCICOM for adjustments, if need be

**Comment by neil-ices-dk** [comment]
[final package](https://community.ices.dk/Committees/SCICOM/2021%20March/02.%20Background%20documents/Data%20policy%20and%20licences) delivered to SCICOM
