### ISSUE TITLE
Codes for legacy data conversion to ERF3.2

### ISSUE THREAD

**Issue by MarilynnatICES** [ices-eg/DIG#30]
Codes are needed to flag legacy data and to enter legacy values in a DATSU/DOME approved manner
Vocab 
code type      Code added
DCFLG           10-MUNIT-1

**Comment by MarilynnatICES** [comment]
File location: 
P:\DP1\projects\DOME\Conversions\Format mapping to ERF3.2.5\ERF22 to ERF3.2.5\New codes for legacy conversion.xlsx

**Comment by Osanna123** [comment]
Could the METOA SFA be tracked to a data submitter who can provide any additional information? It could also be that the SFA stands for the same as CFA-SPM.
No comments for other codes

**Comment by MarilynnatICES** [comment]
There was a different system for method reporting for legacy data. Countries were to report "National Comments" every year to ICES and to the OSPAR Secretariat. Methods were to be reported in detail in the National Comments and user-defined codes used in the method fields in the data file were explained. If the data file comment records (type 13) explain the code, I add the related RECO code. If not, and I can conclude that the code is most likely an identifiable method, I add the code in the appropriate code list and deprecate it. This allows tracking and linking to the National Comments. These data are mostly from the 80's and more primitive versions of methods and equipment were used back then. CFA-SPM is from a later data and is most likely using more modern equipment and procedures.
National Comments are stored in the grey filing cabinet in the "DOME" office at HC. Andersen Boulevard. Keep track of this cabinet when ICES moves.

**Comment by MarilynnatICES** [comment]
The file with new legacy data codes is now stored in Microsoft TEAMs/ICES Data Centre/DOME/Files/New codes for legacy conversion.xlsx

**Comment by pcrjoana** [comment]
Following Marilynn's end of contract, we are closing this issue.
