### ISSUE TITLE
Unifying ICES vocabs - the way forward or not?

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#303]
Currently there is a movement in ICES RMG to unify all the vocabs in ICES as much as possible.

However I think we need to discuss if this is the best way to move forward.

As a user wanting to submit a given data format using any number of vocabs, I simply want to know which codes are valid.

In RECO this can be done two ways;

1) Either you have a specific list for each dataset for vocabs which might looks simelar but isn't because some codes doesn't make sense for all datasets or because the definition might not be the same even though the naming might be.

2) You could have a shared vocab with a mapping to each dataset which define which code are valid for each dataset sharing the vocabs.

The issue with 2) is:

2a) The definition of a code from two original vocabs might not be completely the same even though they share the same name. 
2b) The reco user interface needs to be modified in order to always only show the codes for a given dataset when vieving a given vocab. Currently the default is to show all codes in a given vocab no matter for which dataset the individual codes are valid. You will need to choose a theme (dataset) in order to see that filtering which then behind the scene needs to be setup and managed.
2c) All applications (internal and external) needs to change from the current situation to handled / be able to filter a given vocab only for the relevant codes for the given dataset.
2d) All formats using the current vocabs needs to change and especially the external ones can be a longer process.

For above reasons I think above is a dangerous exersise which doesn't bring any benefit incl. better interopabilities which I beleave is what started this initiative.

By using solution 1).

1a) One vocab for a given dataset always only have the valid codes for that dataset
1b) In case a code definition is the same in multiple dataset vocabs, a link could be established between the code enabling desired interopability.

3) We could also change the fundamental design of RECO to establish a possible many to many relationship between vocabs (codetypes) and codes. This would enable us to have multiple vocabs using the same code, if that happens to make sense.

I currently belieave that is too many pitfalls with 2) and will vote for 1) going towards 3) of that helps!

**Comment by odontaster** [comment]
Had a chat with @HjalteParner and we agreed that not in all cases is a priority but in some cases it might be.
I think we can close this by now.
