### ISSUE TITLE
ShinyApp hosting: guidance and criteria

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#306]
for discussion and input at DIG22 May/June meeting

Draft of [guidance here](https://community.ices.dk/Committees/DIG/DIG%202022/02.%20Background%20documents/ShinyApps%20guidance-2.docx)

**Comment by neil-ices-dk** [comment]
DIG sub-group (Neil, Jens, Ingeborg, Christian, Colin, Luca) met on Weds 01 June to further develop the guidance on publication of apps. Follow-up
## actions before September 2022
@neil-ices-dk to discuss with SCICOM chair the 'fit' of using the resolution path to first start the workflow and evaluate the business case for hosting of the specific app
@neil-ices-dk to ask SIPG for a review of this document, thinking of this as a ‘publication’ and any steps/measures we should consider

**Comment by neil-ices-dk** [comment]
@joern-o-schmidt 

Hi Joern,

The DIG sub-group worked on the ShinyApp hosting guidance back in June, and we had a couple of things that we need to run by you before we follow-up in the September DIG meeting.

Existing document is here for reference https://community.ices.dk/Committees/DIG/DIG%202022/02.%20Background%20documents/ShinyApps%20guidance-2.docx and github issue on DIG board https://github.com/ices-eg/DIG/issues/306 

1)	DIG considered that the ICES resolution process was a good fit for ShinyApp hosting/publishing at ICES as this is essentially a similar need as to publishing a traditional paper publication through the ICES library. This would allow an upfront evaluation of the business case for the app, and resource implications in a well established framework. 
**Do you agree with this approach, and do you see any drawbacks or adaptations that might be needed?**

2)	Following on from this, if you agree with the above, we had the idea to ask SIPG to review the guideline from the point of view of their experience with the publication process, and to consider any additional steps and measures we may need.
**Any objections/thoughts on that?**

**Comment by joern-o-schmidt** [comment]
@neil-ices-dk 

Hi Neil,

thank you very much for reaching out. My responses to the two points below:

1) I agree that every product or activity with resource implications should go through a resolution process and the forms and process should be harmonized. The publication resolution is probably the closest to what you need for a ShinyApp. However, there are clearly some differences, which are partly addressed in the document you linked, particularly that the app will need maintenance and can be updated, thus the form needs adaptation to fit the needs for applications.
And should this be specific for ShinyApps only, or are there other formats that can be relevant? Meaning, should the form be more generic to applications in general?

2) I have no objections to involve SIPG, especially as some ShinyApps will support science and advice dissemination quite effectively. To get feedback on the process and learn about challenges with specific steps, please also involve the editorial office. The specificities for applications is probably something that DIG knows best itself. 

And a general comment: We need to very carefully set up the process for approval here, as this could have potentially more resource implications, especially longer term ones. And could it be that for some products, the Data Centre could take on further maintenance and development as they could become part of other products or support visualization for core services?

Thank you very much again and all the best

Jörn

**Comment by sjurl** [comment]
* Testcase from Acoustic working group
* Finalization of guidance - plan to finish by end of November
   * Suggestion to add point on usage of ICES API's for data to Shiny Apps 
   * Suggestion to add usage tracking information into Apps - important to manage expectations
   * @neil-ices-dk Bring forward shinyapp hosting to SIPG

**Comment by neil-ices-dk** [comment]
working on revised version, new link https://community.ices.dk/Committees/DIG/Master%20documents/ShinyApp/ShinyApps-guideline.docx
- aim to have internal draft ready by 22 FEB

**Comment by neil-ices-dk** [comment]
Came across an alternate publishing route; we have an existing example of ShinyApps being published as a part of advice, which means they have already been through an evaluation via ACOM, and in this case it would not be necessary to create a resolution. However, the ShinyApp coming through this route would still need to follow the other criteria in the process i.e. maintenance, ownership, licensing and metadata. Will make a flowchart as part of the document to illustrate.

This was discussed and agreed with the ACOM chair (21/02/2023)

**Comment by neil-ices-dk** [comment]
Draft sent out to Sjur, Colin, Mike and Periklis for edits and comments; aiming to finalise 1st March for submission to SCICOM 3rd March

**Comment by neil-ices-dk** [comment]
The ShinyApp guideline was approved by SCICOM in March '23; this is now in the process of being published in the ICES publications as a Guideline. Will post link when done

**Comment by neil-ices-dk** [comment]
https://doi.org/10.17895/ices.pub.22695898.v1
