### ISSUE TITLE
New entry in Challenges and Opportunities

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#312]
Removal of data from ICES data center from a member country

**Comment by neil-ices-dk** [comment]
here is the text i put in the Bureau Risk Register:

The temporary suspension of Russian Federation moves this risk to very likely, and may warrant moving this to a major risk. 
- non-provision of data from Russia in the medium and perhaps longer term, affecting provision of advice and science 
- consequence of Russia attempting to submit data to ICES 
- risk that Russian owned data could be requested to be removed from ICES databases affecting time series and transparency

**Comment by davidcurrie2001** [comment]
We have a general issue in the Tracker on a similar topic: https://github.com/ices-eg/DIG/issues/453
