### ISSUE TITLE
New value for POSYS

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#314]
Within the data harvesting project with HELCOM (BDF a.3), there's a need to add a code EPSG:4619 to the POSYS vocab: https://vocab.ices.dk/?ref=40

**Comment by pcrjoana** [comment]
Create the code without ":".

**Comment by Osanna123** [comment]
The code appears to be Sweden-specific projection. is it also used by FI?

**Comment by odontaster** [comment]
@Osanna123 to make it invisible. Needs further discussion in BDF A3 group

**Comment by odontaster** [comment]
Checked with national submitters and agreed to approve it.
