### ISSUE TITLE
Two new stock codes - split of rjc.27.8

### ISSUE THREAD

**Issue by JetteFredslund** [ices-eg/DIG#315]
WKELASMO benchmark: rjc.27.8 will be split into rjc.27.8abd and rjc.27.8c

stock ID: rjc.27.8c
stock description: Thornback ray (Raja clavata) in Division 8.c (Cantabrian Sea)

stock ID: rjc.27.8abd
stock description: Thornback ray (Raja clavata) in divisions 8.a-b and 8.d (Bay of Biscay)

SIMWG has reviewed and endorsed the split. ACOM will approve formally 10 June.

WGEF meets from 14 - 23 June. Stocks will need to be created in time for this meeting, if at all possible?

**Comment by JetteFredslund** [comment]
Once the new stocks are created in RECO, can the codes be implemented in the drop-down in the SAG template, please?

**Comment by odontaster** [comment]
Old stock here
[//vocab.ices.dk/?CodeID=169205](https://vocab.ices.dk/?CodeID=169205)

**Comment by odontaster** [comment]
@odontaster  to implement. In IC old code will have to be deprecated.

**Comment by JetteFredslund** [comment]
Benchmark report (final draft, not published yet): https://community.ices.dk/ExpertGroups/benchmarks/2022/WKELASMO/2021_Meeting_Documents/03.%20Report%202022/WKELASMO%20Report%202022.docx

**Comment by odontaster** [comment]
@JetteFredslund implemented in RECO. SHould be available in SAG (mayeb not available in the template, but will be accepted). SID you can import it.
@odontaster pending implementation in IC.

**Comment by odontaster** [comment]
implemented in IC and informed @HenrikK-N
