### ISSUE TITLE
DATRAS Litter: Two new codes for C-TS-REV

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#316]
WGML requests two new codes:
A15 medical masks
A16 other fishing related plastics

**Comment by odontaster** [comment]
Inform WGDG about these new codes.

**Comment by odontaster** [comment]
@Osanna123 to create the two codes in PARAM. To inform @odontaster, so this task can be fully implemented.

**Comment by Osanna123** [comment]
LT300 and LT301 are added to PARAM with respective relations.
A15 and A16 might be missing some relations

**Comment by odontaster** [comment]
implemented, also missing links.
