### ISSUE TITLE
ENV2022-06-09 new SMTYP benthic sled

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#318]
New code request for SMTYP https://vocab.ices.dk/?ref=152
[SMTYP Blomqvist and Lundgren - 1996 - A benthic sled for sampling soft bottoms.pdf](https://github.com/ices-eg/DIG/files/8891742/SMTYP.Blomqvist.and.Lundgren.-.1996.-.A.benthic.sled.for.sampling.soft.bottoms.pdf)
Doc saved: P:\DP12\QA\SMTYP

**Comment by odontaster** [comment]
@Osanna123 to check with experts whether they need specific models or a more generic benthic sled code.

**Comment by odontaster** [comment]
Experts require generic Benthic sled.

**Comment by Osanna123** [comment]
BS
