### ISSUE TITLE
Behaviour request to delete a code

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#323]
ESAS project requested to delete code 135 'Flushing' from Behaviour (https://vocab.ices.dk/?ref=1709) as an added code from Activity, duplicating the behaviour code 114 'Flying off'.
Need confirmation that the code is not used in the Cetaceans project.
Linked to https://github.com/ices-tools-dev/esas/issues/70#issuecomment-1148655344

**Comment by neil-ices-dk** [comment]
@pcrjoana to confirm and revert back - by 14:00!

**Comment by pcrjoana** [comment]
Confirmed that code "135 - Flushing" isn't needed for the Cetaceans DP and that it can be deleted!

**Comment by Osanna123** [comment]
done
