### ISSUE TITLE
RDBES: New codetype FishingAreaCategory and codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#329]
Can you add a new code type FishingAreaCategory.
Codetype			Description
FishingAreaCategory	Specify the fishing area category, used for salmon and sea trout

Code	Description
O		Open sea, beyond about 4 nautical miles from the shore
C		Coast, until about 4 nautical miles from the shore
F		Fresh water, e.g. a river or lake
NA		NotApplicable

**Comment by neil-ices-dk** [comment]
@HenrikK-N do we have a reference for why this is 4 nm? in other legislation there are different definitions

> 4 nautical miles from the shore

**Comment by odontaster** [comment]
@HenrikK-N I also found a reference in eionet for this concept:
https://dd.eionet.europa.eu/vocabularyconcept/inspire/ZoneTypeCode/waterBody/view
Please check if this could be used.

**Comment by HenrikK-N** [comment]
@odontaster I had a fast look, I would not be able to say that can be used, I do not think so. WGBAST said that the code would depend on the gear used so it is not a fixed 4 nm line. Please take the dialog with the WGBAST chair and data users, you have their names.
Cheers Kjems

**Comment by odontaster** [comment]
I contacted WGBAST for clarification but they still did not answer.

**Comment by odontaster** [comment]
The suggested existing CodeType, that should eb linked in Neil's comment is this one:
[//vocab.ices.dk/?ref=212](https://vocab.ices.dk/?ref=212)
It could be supplemented with new codes if the existing ones did not cover required concepts.

**Comment by HenrikK-N** [comment]
I have just been looking at the codes [//vocab.ices.dk/?ref=212](https://vocab.ices.dk/?ref=212), and I can see why you suggest this code. We could tell WGBAST to use 'C' : 'WFD Coastal water' for Coast, but WGBAST does not use the WFD Coastal water definition, WGBAST are (according to what they told me) using a rough 4 nm and a gear depending wague definition. So it would be misleading, using the same code in two different contexts, having one written definition, and where some data would be using another unwritten definition. Then we should add the e.g. 'CW' for 'Coastal water'. We also need to add 'F': 'Fresh water', e.g. a river or lake and 'NA' 'NotApplicable'. But objectively seen I think that if the 'Water and Land Station Type' is used for WDF data, then we are starting to 'pollute' the codes with WGBAST needed codes, just because the codes are for a kind of the same types. Grouping things together which are the same makes good sence, but if the codes are not meaning the same and are not used for the same purpose or in the same context, it might confuse the picture. I would think it would be best for everybody to have a new code list, but if you want to add the missing codes to the 'Water and Land Station Type', then okay.

**Comment by HenrikK-N** [comment]
Hi. What is status? We really need this list now : ) Cheers

**Comment by odontaster** [comment]
Hi @HenrikK-N. Your suggestions will be discussed tomorrow in RMG. I think I would prefer to add Codes to the existing Code Type, but listening to the rest of RMG will be useful.

**Comment by odontaster** [comment]
Agreed to add missing codes Fresh water, Coastal 4 nm and NA and link relevant ones to RDBES

**Comment by odontaster** [comment]
Added MC- Marine water (coast), FW- Fresh water and NA- Not applicable to the WLTYP. Linked to RDBES these plus MO
