### ISSUE TITLE
Agenda for DIG May 2021

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#33]
possible breakouts in addition to below:
_data.ices.dk
ocean format_

**Tuesday**
- DISCUSSION PLENARY: Recommendations to DIG
- DISCUSSION PLENARY: Review of DIG Actions [actions on board](https://github.com/ices-eg/DIG/projects/1)
- INFORMATION POINT: Update on accreditation @pcrjoana and @neil-ices-dk 
- INFORMATION POINT: DSTSG highlights from SG chair (@jensr how long will you need on the DIG agenda for this?)
- DISCUSSION PLENARY (TUESDAY): Filtering granularity of vocab.ices.dk (themes or datasets by dataset) [see discussion](https://github.com/ices-eg/DIG/issues/42#issuecomment-819472174) and [presentation](http://community.ices.dk/Committees/DIG/DIG%202021/05.%20Presentations/Filtering-DIG-May18-2021.pptx)
- BREAKOUT (TUESDAY): Framework for data/products outside of normal data management flow #5 (@jensr)

**Wednesday**
- INFORMATION POINT: progress on master reference change management [vocab.ices.dk management](https://github.com/ices-eg/DIG/projects/2) (@Osanna123 and @neil-ices-dk)
- INFORMATION POINT: AIMS (@mehdiabbasi), 
- INFORMATION POINT: data.ices.dk (@mehdiabbasi and @cmspinto) #9 
- INFORMATION POINT: Data policy/licence #2 and #3 (@sjurl or @neil-ices-dk)
- INFORMATION POINT: Ocean format: awaiting some info from Hjalte, see #23 

**Thursday**
- DISCUSSION PLENARY (THURSDAY): World Data System membership; @pcrjoana 
- BREAKOUT (THURSDAY): data preservation plan #34

**Friday**
- BREAKOUT (FRIDAY): feedback and test data.ices.dk #9

**Comment by jensr** [comment]
@neil-ices-dk Thanks for heads-up I reckon 10-15 minutes should be adequate for DSTSG update.
