### ISSUE TITLE
RDBES: New codetype StatRecSource and codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#330]
Hi Adriana
Can you create the following new codetype StatRecSource and codes:

Codetype		Description
StatRecSource		Data source of statistical rectangle

Code		Description
RepLogbook	Statistical rectangle reported in logbook
AdjPosData	Adjusted based on positional data
EstHarbLoc	Estimated based on harbour location
EstPosData	Estimated based on positional data
EstExpKnow	Estimated based on expert knowledge
EstOther		Estimated based on other data sources

Cheers

**Comment by odontaster** [comment]
implemented in RECO and communicated to @EjazAtIces

**Comment by HenrikK-N** [comment]
@odontaster. Thanks for pointing out that if the field XXstatisticalRectangle is '-9', then the code 'NotApplicable', with the description: 'Not applicable' should be added to the code type ‘StatRecSource’. The Core Group agree to that, so please add that.
Cheers
