### ISSUE TITLE
RDBES: New code type EEZ OR new code HS High Sea in code type ISO_3166

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#332]
Hi Adriana
Can you add a new code 'HS' High Sea in code type ISO_3166 OR create a new code type 'EEZ'. What ever solution you/RMG think is best. The RDBES need a list of all the country codes including a code for 'HS' High Sea for the field 'Exclusive Economic Zone', which need all country codes and the 'HS'. 

1) Add code 'HS' High Sea in code type ISO_3166
Code	Description
HS		High Sea (Sold at sea - only applicable as Landingcountry)

OR
 2) Create a new code type 'EEZ'

Codetype Description
EEZ		Exclusive Economic Zone

Code	Description
HS		High Sea (Sold at sea - only applicable as Landingcountry)
(all country codes from code type ISO_3166)

Cheers Henrik

**Comment by neil-ices-dk** [comment]
The ISO_3166 codelist does not have such terms, so it would be a new codetype - this needs further discussion i.e. high seas/international waters. We should look at FAO CWP for guidance here. 

EEZ's are also really difficult as we need to refer to a source of definition of EEZ i.e. marineregions gazeteer

@HenrikK-N come to next RMG meeting when available

**Comment by HenrikK-N** [comment]
Fine, I will.

**Comment by odontaster** [comment]
Useful link with a few concepts:
https://www.fao.org/cwp-on-fishery-statistics/handbook/general-concepts/main-water-areas/en/

**Comment by odontaster** [comment]
RMG suggests to create a code type 
Water jurisdiction areas, with values:
- Internal waters and archipelagic waters
- Territorial sea
- Contiguous zone
- Exclusive economic zone
- International waters/high seas/areas beyond national jurisdiction

Good descriptions of all these can be found in the previous link to CWP.

@HenrikK-N

**Comment by HenrikK-N** [comment]
Hi Adriana/RMG. What is status? It was agreed to make a new code type. What is requested is a list with country codes, and the standard is the ISO_xxx and a High Sea/International water code. I do not think we should complicate things and include all the RMG extra suggested waters/zones. The RDBES system opens in 7 working days, and the developers also need some time to develop code for the new code type, so it would be really good if this list can be finished very soon : ) Cheers

**Comment by odontaster** [comment]
Hi @HenrikK-N, first I understood you agreed to add the Code Type RMG suggests, but in your last comment you still mention the list of countries, so I am unsure. 
It would be a good idea if you join RMG tomorrow at 13, so we are sure we have a common understanding of the issues.

**Comment by HenrikK-N** [comment]
Hi @odontaster. When looking at the FAO link you send. I could not find any code list, but I could see that the Exclusive economic zone was in your list of codes from the link, and the EEZ would be a countries/nation, so that is fine. What I wrote 2 Aug. was "If all the codes for all the areas you list all are the ISO country codes and International waters/high seas, then it could make sense to have the common name you suggest Water jurisdiction areas and not EEZ". So as long as the country codes are in the list (and the High sea would also be I could see, the last on your list) then it is fine. Because it is the country codes that are requested. But now when it looks like the code list have not been made and we only have working 7 days left to make the list. I suggest we focus on the requested country list and High sea/International waters. Then at any point after the 7 days (22 Aug.) you can add what the RMG think is relevant, as long at the country codes are in the list you create. I assume adding the country codes to the new list would cover the Territorial sea, Contiguous zone and EEZ. Because that would be countries/nations rights just extending 12, 24 and 200 nautical miles from the baseline. And then we need the High sea/International waters. So I am just suggesting we should not spend time now on the 'Internal waters and archipelagic waters'. I will join RMG tomorrow at 13, please send an invitiation. The request is still and only country codes and High Sea/International waters : )

**Comment by HenrikK-N** [comment]
Hi @odontaster/RMG. I will talk with the Core Group and let them know that they should add a new field to the format, and not combine a country list and an International water code. This morning I was just thinking that you do not need to create the list of the 5 codes you suggest above: Internal waters and archipelagic waters, Territorial sea, Contiguous zone, Exclusive economic zone and International waters/high seas/areas beyond national jurisdiction. Because we already have the code type 

'Exclusive Economic Zone (EEZ) indicator', EEZI, [https://vocab.ices.dk/?ref=212](url). 
There there is the distinguishing between EEZ and International waters, just with the 
code 'EU', desc: 'EU waters', that would be the EEZ, and 
code 'RFMO', desc: 'International waters'. 

So I do not think you need to create the list. Cheers

**Comment by odontaster** [comment]
Hi @HenrikK-N that sounds good then, will close this issue for the time being.
