### ISSUE TITLE
RDBES: Deprecate or delete 2 codes from code type SelectionMethod

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#333]
Hi Adriana

Can you deprecate or delete (best solution, but check with Ejaz if every used) the following 2 codes from code type SelectionMethod, so far only used by RDBES.

Code		Description
NotSampled	Used in cases where the selected unit is not sampled 
OutOfFrame	Used in cases where not all sampling units are included in sample selection

Cheers Henrik

**Comment by neil-ices-dk** [comment]
Adriana has confirmed they are not in use

**Comment by odontaster** [comment]
Deleted the two codes from the code type, communicated to @EjazAtIces
