### ISSUE TITLE
RDBES: New codetype FreshWaterName and codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#337]
Hi Adriana
Can you create the following new codetype FreshWaterName and codes:

Codetype 		Description
FreshWaterName	Name of the fresh water. E.g. river name or lake name

The following is just to show some potential codes and descriptions.
I have suggested that the code is using English letters and the description have the local letters.

Code		Description
Agluona		Agluona
Raane Aelv	Råne älv
Serksne		Šerkšnė

And up to 450 more river names.

Contact WGBAST persons for the river name list (Martin is the chair): Martin Kesler <martin.kesler@ut.ee>; Tapani Pakarinen <tapani.pakarinen@luke.fi>; Susanne Tärnlund <susanne.tarnlund@slu.se>; Anders Kagervall <Anders.Kagervall@slu.se>. 	

Cheers Kjems

**Comment by neil-ices-dk** [comment]
These already exist under f.ex the[ WFD ](https://dd.eionet.europa.eu/vocabulary?vocabularyFolder.folderName=wise&vocabularyFolder.identifier=WaterBody&vocabularyFolder.workingCopy=false&filter.conceptStatusInt=145&filter.text=agluona&filter.visibleColumns=Notation&filter.visibleColumns=Status&filter.visibleColumns=Status+Modified&filter.pageSize=20&view=Search&_sourcePage=GVedL6dhCEevOyohamMchPsB-Sd518qf0W91g9Qr3M-tFPWuGEFVI1ZQogqTPA8FgP-gq2t1-Cs%3D&__fp=DBt3xQv-NtumaSQ9QuKsn3Ogd9i83ehWCAdoohRvzDl2q8aMgOD3s5Q-Xh5aWMUGL8NMGsNDEMhctgVAcVZF2HhOri0pDJQQ263OoGfolfyaxJ_gkBJJ6zjdXfzWr-0E)

also Eurostat. We should refer to subsets defined in these lists and not come with a new vocab.

**Comment by odontaster** [comment]
@odontaster  will create the CodeType WaterBody. Will populate it later on when we solved issues with duplicate Labels etc

**Comment by HenrikK-N** [comment]
Hi Adriana. We need to move on with this WaterBody (or WaterBodies) code list, the list should be ready when we open the RDBES the 22 Aug. I will attache the river list I received from WGBAST, have you had any contact with them? I suggest that we take a pragmatic approache, meaning that you take each of the rivers in the attached list and identify it in the EIONET Water bodies (I guess status stable, I suggest you forget EIONET issue with duplicate Labels), you create a code with the EIONET Lable, and the local spelling in the description to the extent possible, you can always at a later point update the description to a more correct local spelling. Then we are in-line with the EIONET, and we can have the code list ready for the 22 Aug. 

Cheers Kjems

**Comment by HenrikK-N** [comment]
[WGBAST_Rivers.xlsx](https://github.com/ices-eg/DIG/files/9266883/WGBAST_Rivers.xlsx)

**Comment by odontaster** [comment]
I agree @HenrikK-N. I was in contact with WGBAST but had not much answer, probably due to holidays. Will work on this and try to have something usable for next thursday, will ask RMG or you for help if needed.

**Comment by odontaster** [comment]
There are several relevant sources of information for rivers, for example:
https://data.apps.fao.org/aquamaps/
https://land.copernicus.eu/imagery-in-situ/eu-hydro/eu-hydro-river-network-database?tab=mapview
In these cases, the data refer mostly to basins and subbasins. These are consistent at the european level, but they are defined for different scopes, based on geological and hydrological properties, so the scale is not fit for purpose for the WGBAST submissions, is too large scale, mostly in Baltic countries.

We also have WISE dataset in EIONET:
https://dd.eionet.europa.eu/vocabulary/wise/WaterBody/view
In this case, most rivers can be found, but there can be many records refering to different parts of the river. WGBAST requires a single code per river, as the reported data would refer to catches for the whole river, ussually done in the lower part of it. WGBAST suggested to ask national experts to go through this vocabulary and hand pick the codes for each river that could fit better their scope, but it would always be an approximation.

A third possibility arised from the conversation with WGBAST, as all countries have an authority defining codes for water catchments in the country, please see for instance
https://www.smhi.se/polopoly_fs/1.26703!/Sveriges_huvudavrinningsomr%C3%A5den_SVAR_2016_6.pdf
These are the codes WGBAST and submitters are commonly using in their national reporting (also included in the WISE codes). We could create a Code Type "National Catchment Areas" (Description: Codes for rivers and fresh water bodies as defined by national authorities). The codes would require a country prefix, as some national codes are just numbers, underscore and the code as is in the national relevant authority site. The description would be the country and the Name of the river as is in the national authority site.
WGBAST suggested that its members can provide all required information, but it might take them some time.

We solve a few issues with this suggestion: the list can grow with time, so we can start straightaway with the few rivers required for the data call (15 tops, Tapsa already working on it) and add more rivers as we receive the information from WGBAST members. This list can be used in other data calls, the codes are concise but quite informative and well known for each country nationals, it has relevant source of information and this list does not exist elsewhere, as far as we could research.

The list for next weeks opening would start with these codes:

Code | Description

SE_09 | Sweden   Luleälven
SE_20 | Sweden   Skellefteälven
SE_38 | Sweden   Ångermanälven
SE_40 | Sweden   Indalsälven
SE_48 | Sweden   Ljusnan
FI_61 | Finland   Iijoki
FI_65 | Finland   Kemijoki
LV_41 | Latvia   Daugava
PL_?? | Poland   Vistula

**Comment by odontaster** [comment]
RMG accepts the proposal for a new Code Type. Some attention will be needed when receiving the national codes as to keep the aggregation level similar, rivers, basins or subbasins, accross countries.

**Comment by odontaster** [comment]
Preliminary list has been created, pending to improve with WGBAST input.

**Comment by HenrikK-N** [comment]
Hi @odontaster, can you as we talked about add the code 'NA' 'Not applicable', for all the catches not in rivers.
Cheers Kjems

**Comment by odontaster** [comment]
29/09/2022: Asked WGBAST chairs for a short list of members per country to ask for their input to build up this list.

**Comment by odontaster** [comment]
Will attend WGBAST in March to move this a bit forward.

**Comment by odontaster** [comment]
Communicated in WGBAST, only received feedback from Estonia
[RiversAndCatchments_vocabulary_ICESDCrequest Estonian salmon rivers.xlsx](https://github.com/ices-eg/DIG/files/11259741/RiversAndCatchments_vocabulary_ICESDCrequest.Estonian.salmon.rivers.xlsx)

**Comment by odontaster** [comment]
[RiversAndCatchments_vocabulary_ICESDCrequest.xlsx](https://github.com/ices-eg/DIG/files/11487479/RiversAndCatchments_vocabulary_ICESDCrequest.xlsx)

**Comment by odontaster** [comment]
[NEW_RECO_Rivers&Catchments.xlsx](https://github.com/ices-eg/DIG/files/11487492/NEW_RECO_Rivers.Catchments.xlsx)

**Comment by odontaster** [comment]
Deprecate old ones and make them invisible. Create new ones without "-".

**Comment by HenrikK-N** [comment]
Hi Adriana
If the same river change code and/or description, so it is possible to update the code and/or description, then that is best. Because then the data records are linked to current valid river codes, and the number of depricated codes is kept to a minimum.
Cheers Kjems

**Comment by odontaster** [comment]
When asking WGBAST, most submitters proposed different codes to the ones created last year, in order to be able to be more specific and closer to their national databases. For these, all 8 codes were deprecated and made invisible to avoid confusion. New list is already available.
