### ISSUE TITLE
RDBES: New codetype ErrorMeasureType and codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#339]
Hi Adriana
Can you create the following new codetype ErrorMeasureType and codes:

Code type		Description
ErrorMeasureType	The type of the error measure
	
Code	Description
RSE		Relative Standard Error
90CI	90 % confidence interval 
90PI		90 % Probability interval

Cheers Kjems

**Comment by odontaster** [comment]
RMG has some concerns on the completeness of the CodeType,
This code type could fit the concept:
[//vocab.ices.dk/?ref=213](http://vocab.ices.dk/?ref=213)
new codes can be added.
@HenrikK-N

**Comment by HenrikK-N** [comment]
That is a good suggestion, please add the new codes. Cheers Kjems

**Comment by odontaster** [comment]
Hi all

Sorry for a slow reply, I have been on leave. 

I don’t have a  comment on the High Seas query. 

For the error measure type codes, the suggested codes don’t seem to have a 1-1 match with our suggested codes. Or perhaps they do, but the description is not clear enough.

For our suggested code RSE, the equivalent is SD – but RSE is essentially SD/estimate so not quite the same. 

90CI possibly ties in with U2. But it is not clear and there is no link to the OSPAR guidance to confirm.

90PI does not have a 1-1 link unless it is covered under U2 – but how can we distinguish between the 90PI and 90CI.  

% in the METCU list – we do not need.

All that said, I think that we could maybe add our codes (or some version of them) to METCU with the agreement of others who use these codes, and checking there is no overlap. 

All the best
Liz

**Comment by odontaster** [comment]
Codes to be added to METCU, as suggested by Henrik after Liz's email:
Code Description
RSE    Relative Standard Error
90CI   90 % confidence interval
90PI   90 % Probability interval
