### ISSUE TITLE
ENV2022-06-27 SFLAG new codes

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#341]
Info from the German data submitterÆ
'
for reporting species counts properly we need some additional codes in SFLAG. In case that several species are included under one name in one sample SFLAG provides the codes SPP-1 to SPP-4. In our samples up to 12 species are included under one name, e. g., Bacillariales. So we need the additional SFLAG codes SPP-5 to SPP-12
'

**Comment by odontaster** [comment]
@Osanna123 to ask PEG (EGPHYTO) for advice on this issue, whether this is acceptable use, operational for the wider community.

**Comment by Osanna123** [comment]
PEG expert doubted the usefulness of extra SFLAG values, but the answer from the requester was:

...we have that problem with old and new Phytoplankton and Zooplankton data. The laboratory that is doing the species determination and counts is in some cases not able to determine the species exactly but a higher taxonomic level. E. g., they know that there some individuals in a sample that belong to a special family and that these individuals are different species but they can’t say which genus or species exactly. So for these cases they report number and biomass for each assumed species in a sample with only the family as taxon.
What I did for Phytoplankton data delivery in the past is aggregating the data for the e. g. the family. But our experts say that this leads to a loss of information. A good solution for us would be to use a number of different SFLAG values to make the records unique. As far as I know, the PEG_BVOL lists are used for the Baltic Sea and not for our North Sea data.
Hope that makes it a little bit clearer...

Requested codes are now created
