### ISSUE TITLE
REFSK need updating with CEMP guidelines

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#342]
https://vocab.ices.dk/?ref=171
REFSK contains the full list of the JAMP guidelines, but are seem to be updated with the CEMP references. 
This needs a revision according to:
https://www.ospar.org/work-areas/cross-cutting-issues/cemp

**Comment by evabrna** [comment]
![image](https://user-images.githubusercontent.com/119604756/205639676-7b846c17-bfda-4ff0-a810-4819719fe0e9.png)
