### ISSUE TITLE
New CodeType needed for Digestion Stage

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#344]
[Code and Codetypes.xlsx](https://github.com/ices-eg/DIG/files/9109546/Code.and.Codetypes.xlsx)
A new code type is needed for digestion stage for the fish stomach database format

Attached: suggestions from experts as used in many countries already

**Comment by neil-ices-dk** [comment]
@cekv to get an opinion from WGBIOP and then come back with a final proposal

**Comment by cekv** [comment]
Submitters have accepted the use of the description  (and code) in this document for digestion stage
[Code.and.Codetypes.xlsx](https://github.com/ices-eg/DIG/files/10217123/Code.and.Codetypes.xlsx)

**Comment by cekv** [comment]
DigestionStage	0	Body intact, shiny eyes, body surface at least partially with scales, species easy to identify (FISH); intact prey, species easy to identify (INVERTEBRATES)
	1	Body cavity opened, Head partly digested, Nothing or little left of the body cavity, Spine with muscle tissue, species or groups may be identified (FISH); Partially digested prey, species or groups may be identified (INVERTEBRATES)
	2	Exclusively spine and also other skeletal remains and/or otoliths, only remnants of main groups of prey can be identified (FISH); skeletal material/remains only (INVERTEBRATES)
