### ISSUE TITLE
New codes to be added to PARAM

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#346]
Need 3 new codes to be added to the PARAM CodeType: https://vocab.ices.dk/?ref=37

DRYWT - dry weight
WETWT - wet weight
VOL% - percent volume

DRYWT% exist but cannot be reused since this is not a percentage of the parameter used to establish the gravimetric method used

**Comment by Osanna123** [comment]
@cekv which project was this request for? can we have a look at this request together when you have time?

**Comment by Osanna123** [comment]
DRYWT - dry weight
WETWT - wet weight
VOL% - percent volume
created
