### ISSUE TITLE
New CodeType - Relative stomach fullness

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#347]
New CodeType for stomach fullness is needed.

Stomach fulness is based on a point system where the stomach is assessed before opening it.

Option1) Taken from a Norwegian manual and personal experience, approved by scientists working in this field.
Code and description
1	Stomach is empty/or regurgitated
2	So little content that it is not visible prior to opening the stomach
3	Content is easily visible prior to opening, but the stomach is not full
4	Stomach is full, but not stretched.
5	Stomach is full and stretched thin

Option 2)  From other manuals regarding the workup of stomach samples 
Code and description
1	empty, 0%
2	one-quarter filled, 25%
3	half-filled, 50 %
4	three-quarters filled 75%
5	bursting, 100%

Option 3 is to combine the two

**Comment by odontaster** [comment]
@cekv to check with WGBIOP whether they have feedback on this.

**Comment by cekv** [comment]
From the comments received, submitters would like option 1 (above)
