### ISSUE TITLE
Naming the new Stomach DB - for RECO purposes

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#348]
Having some trouble giving name and description to the new and improved stomach database 

Have put it as StomachDB in RECO (invisible) under datasets and datasetsver, but not sure regarding name and description. 

So far my description is as follows:
Stomach database containing predator and prey information

**Comment by odontaster** [comment]
RMG suggests STOM for Dataset code.

**Comment by Osanna123** [comment]
Please revise the description, to avoid the word Database

**Comment by cekv** [comment]
How about: Stomach data

**Comment by cekv** [comment]
@cekv please change to Stomach Content
