### ISSUE TITLE
ENV2022-07-25 new SMTYP

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#350]
new code for SMTYP: sampling from helicopter. It is a stainless steel mount with a 9 liter high density polyethylene canister.

**Comment by odontaster** [comment]
Confirm with submitter whether this sampler is specific to helicopter sampling, and if volume is relevant.

**Comment by Osanna123** [comment]
The sampler is specific to helicopter, the requester prefers a detailed version.
Code HPM-HDPE9 is created for Helicopter-based stainless steel mount with an HDPE sampling canister - 9 litres
