### ISSUE TITLE
BycatchDB- New codes needed to map old vessel lengths reported

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#353]
The old code type used in bycatch accepted larger than 15 and smaller than 15 as codes. 
//vocab.ices.dk/?ref=1502
the mapping with the new code for the already submitted data is impossible.
//vocab.ices.dk/?ref=1725
We would suggest to add VL0015 and VL15XX to convert the data in the database and deprecate the codes immediately so they are not used anymore.

**Comment by neil-ices-dk** [comment]
> We would suggest to add VL0015 and VL15XX to convert the data in the database and deprecate the codes immediately so they are not used anymore.
agreed from RMG

**Comment by odontaster** [comment]
Codes created and deprecated @cmspinto
