### ISSUE TITLE
RECO2022-08-30 missing Themes/Datasets

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#356]
Relevant for the new RECO developments, and also Data portal in the future
https://icesit.sharepoint.com/:x:/r/sites/DCTeam/Shared%20Documents/RECO%20Management%20API/Theme-Datasets.xlsx?d=wbbd8bf6a8d744662ba319ea9ee5f0d00&csf=1&web=1&e=ZxNPll

some datasets are missing from the Themes and/or link to the Datasets 
ByCatch
Cetaceans
HistoricalPlanktonData
Biodiversity - Sea Birds(BiodivBirds)
Biodiversity - Seals(BiodivSeals)
Historical Danish Limfjord Data - Fish Trawl Data 
Historical Danish Limfjord Data - Benthos Data 
SmartDots(SmartDots)

Also, some datasets linked to the Themes are still invisible

**Comment by Osanna123** [comment]
@cmspinto can we chat about the historical datasets?
With the shift of scope for datasets, we need to consider splitting Historical Plankton, and 2 Limfjord datasetvers from the joint dataset in RECO

**Comment by Osanna123** [comment]
@HjalteParner can we have a chat about the invisible datasets in RECO?

**Comment by Osanna123** [comment]
@neil-ices-dk could you please help us with identifying relevant Themes for the datasets:
Bycatch
Cetaceans
Seabirds
Seals
SmartDots
and the Historical datasets (plankton, trawl, benthos)

**Comment by cmspinto** [comment]
> @cmspinto can we chat about the historical datasets? With the shift of scope for datasets, we need to consider splitting Historical Plankton, and 2 Limfjord datasetvers from the joint dataset in RECO

I think it is a good idea to split them, I actually though they were already two distinct datasets.

**Comment by HjalteParner** [comment]
> @HjalteParner can we have a chat about the invisible datasets in RECO?

Yes ... if you want to talk about the 2 acoustic trawl datasets and the 6 ocean hydrochemistry datasets, then they should indeed be visible.

**Comment by neil-ices-dk** [comment]
just checking i have understood, you mean according to this vocab [//vocab.ices.dk/?ref=1574](https://vocab.ices.dk/?ref=1574)?

if so:
For Cetaceans, Seabirds and Seals, i would suggest we need a new Theme: Biodivesity which would be consistent with how we have arranged it on the website

Bycatch would be best placed under Commercial Catch

Historical datasets should go into the relavent thematic category, allthough i'm not sure what the benthos dataset is?

**Comment by odontaster** [comment]
Approved.

**Comment by Osanna123** [comment]
Datasets needed for DP are made visible (except for the noise indicator, which will probably be a part of stage 2)

New codes are created![image](https://user-images.githubusercontent.com/17157764/189348805-eb440d5c-ea8a-4e76-9b25-36bb326ff236.png)
HIDAT deprecated and made invisible

New Theme BD (Biodiversity) added
Missing Themes/Datasets are mapped except for SmartDots

**Comment by Osanna123** [comment]
@neil-ices-dk should SmartDots have their own Theme?

**Comment by Osanna123** [comment]
Hmm.. Either it's so unique that it deserves a separate Theme (Biological measurements / SmartDots / ...)
or perhaps it could go under the Stock assessments as the goal of SmartDots is better stock assessment, isn't it?

**Comment by neil-ices-dk** [comment]
> Hmm.. Either it's so unique that it deserves a separate Theme (Biological measurements / SmartDots / ...) or perhaps it could go under the Stock assessments as the goal of SmartDots is better stock assessment, isn't it?

that also makes sense, but then it could go under Trawl surveys as that is where the samples are derived from. Will wait for a full RMG meeting to figure this one out :)

**Comment by neil-ices-dk** [comment]
so, i think a lot depends on where we would place the likes of fish stomach contents - i can see a better logic for including this under the fish trawl survey umbrella, rather than the stock assessment; So that is my vote, but happy to take counter suggestions :)
![image](https://user-images.githubusercontent.com/23527005/190356108-b8268066-9543-4df5-beec-0d884bc50402.png)

**Comment by Osanna123** [comment]
If this theme is to become an umbrella, I'd prefer getting rid of the term 'trawl'. 
We could possibly merge all survey datasets under the 'fisheries surveys'. It is quite logical, and should look nice in both RECO and the Data Portal.
Or, perhaps we could find a more specific term that could exclusively include Trawl, Fecundity&Atresia, Stomachs, and SmartDots, but not E&L or Acoustic?

**Comment by neil-ices-dk** [comment]
> If this theme is to become an umbrella, I'd prefer getting rid of the term 'trawl'. We could possibly merge all survey datasets under the 'fisheries surveys'. It is quite logical, and should look nice in both RECO and the Data Portal. Or, perhaps we could find a more specific term that could exclusively include Trawl, Fecundity&Atresia, Stomachs, and SmartDots, but not E&L or Acoustic?

we could go with Biotic surveys, but that would include E&L...

**Comment by Osanna123** [comment]
If we don't want to start shuffling the existing Themes/Datasets settings, we should probably create a new Theme specific for SmartDots. Would 'Biological measurements' do?
@neil-ices-dk

**Comment by neil-ices-dk** [comment]
yes, or biological parameter issues - up to you :)

**Comment by Osanna123** [comment]
![image](https://user-images.githubusercontent.com/17157764/197461749-f77b59eb-426d-417b-b5af-8bcaaf359d77.png)
+VMS was linked to the Commercial catch (wouldn't the term 'Commercial fisheries' be more appropriate?)

**Comment by neil-ices-dk** [comment]
good point, i would actually suggest we align with the FAO and use the term 'capture fisheries' https://www.fao.org/fishery/en/capture

**Comment by Osanna123** [comment]
@mehdiabbasi please note a vocab Theme code CAT changed the description to 'Capture fisheries'
