### ISSUE TITLE
DATRAS: Deprecate TS_ code types replaced by common ones

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#358]
TS_Ship, TS_AgePrepMet, TS_Country and TS_AgeSource have been substituted by common use Code types (SHIPC, PreparationMethod, ISO_3166 and SampleType respectively).
How should I proceed to deprecate them?

**Comment by Osanna123** [comment]
@odontaster change the Visibility flag to 0, and change the description to point to the correct CodeType.
Long description might include info on the year of 'deprecation'
