### ISSUE TITLE
New code for RS_SamplingScheme

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#36]
Kirsten Birch Håkansson from DTU-Aqua wants to add  code **Baltic SPF regional** to the codetype RS_SamplingScheme
They need it to be able to upload data from a pilot under ISSG - Baltic SPF.

**Comment by neil-ices-dk** [comment]
@HenrikK-N can you 'officially' approve this and add the lablel "Approved-asis"

**Comment by HenrikK-N** [comment]
Approved.
