### ISSUE TITLE
SMARTDOTS: PreservationMethod

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#361]
Hi Adriana, 

Thanks for the help with this.

I will start describing the issue: https://github.com/ices-eg/SmartDots/issues/188

Two years ago it was requested that we changed the expertise of the readers to be more than the Sample Type and the Preparation Method. 

It was requested that we added the Preservation Method and the Observation Method.
Joana talked with the community from SmartDots and they arrived to this: https://github.com/ices-eg/SmartDots/files/9306917/SmartDots_PreparationMethods_FINAL.1.xlsx

 

Question is that now I can’t find some of the preservation methods, I could find these two here (https://vocab.ices.dk/?ref=34): 

 

But I’m still missing:

in brine
fresh
frozen (to be r linked with preparation method)

Could you give a help?
I hope that I was clear,

Thanks, 

Best,

Carlos

**Comment by odontaster** [comment]
The best fitting code type would be METFP:
Fresh would be Non
In brine could be added with some more description
Frozen is still left out, could it be used another code type, like Storage Method or Preparation Method?

**Comment by Osanna123** [comment]
@cmspinto could you please check the status of this issue?

**Comment by odontaster** [comment]
duplicate of #388
