### ISSUE TITLE
Smartdots: AQ

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/DIG#362]
Can you have a quick check to this question:

https://github.com/ices-eg/SmartDots/issues/222

**Comment by cmspinto** [comment]
This is the vocab used in the RBDES. We have no idea how the countries uploading data to the RDBES are using this.
https://vocab.ices.dk/?ref=1682
@pcrjoana is this the same as that used in SmartDots or are there different versions of the AQ code in ICES vocabs?

**Comment by Osanna123** [comment]
yes, it's the same, all is fine :)

**Comment by JaneGodiksen** [comment]
WGSMART don't think the vocabs are the same. Vocab 1682 not the same as 1395
