### ISSUE TITLE
How to handle EDMO code synchronisation to RECO and RECO EDMO relationship to ISO 3166 country codes including the ISO region codes embeded in ICES version of the country list

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#367]
Relationship between the ICES 'ISO 3166 country code and region codes used by ICES' vocabulary and the ICES EDMO list is automatiacally synchronised nightly.

However manual relationship establish between EDMO codes and our ISO 3166 embeded region codes gets overwritten at the nightly synchronisation as EDMO only uses the ISO country codes.

The relationship between the EDMO code for Marine Scotland Science (2135) and the ISO 3166 region code for Scotland (GB-SCT) gets deleted during synchronisation and this relationship is used for validation in acoutic at least.

I've discused this with @Mehdi and one solution would be to have the synchonisation skipping deleting establish relationships with the GB region codes in case EDMO codes code is GB.

This will mean that all ICES EDMO codes with a relationship to GB and in addtion a possible GB region code, will keep the GB region code upon synchronisation. In case (not likely) a central EDMO code change from GB to another country, then both the GB and GB region code will be deleted.

Can you agree on this?

P.S. Another possibility is the get rid of the GB region codes in the ICES ISO 3166 hybrid vocabulary and then be political  and let Scotland and the like to not have a region code within the ICES vocabulary i.e. Scotland does political belong to Great Britain for the time being at least ;-)

**Comment by Osanna123** [comment]
Skipping deleting established relationships with the GB region codes in case of  EDMO synchronisation is ok with us

**Comment by Osanna123** [comment]
@mehdiabbasi @HjalteParner please let us know when this is implemented, so we can close the issue

**Comment by mehdiabbasi** [comment]
@Osanna123 @HjalteParner It is implemented and I tested that sync does not remove the country that the data manager added. I just added GB-SCT to the EDMO code -> 2135

**Comment by HjalteParner** [comment]
Thanks, @mehdiabbasi
