### ISSUE TITLE
Event logging vocabs: Seavox

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#368]
I think we should take a look at this and see if we have coordinated input as it touches on some of our existing vocabs
https://github.com/nvs-vocabs/eLoggerVocabs/issues/1

**Comment by gwemon** [comment]
Thanks @neil-ices-dk happy to have a quick chat about this with Anna and all if needed. Or maybe point me to the vocabs you had in mind so that I can check how they align to or fit in with what we are proposing?

**Comment by neil-ices-dk** [comment]
> Thanks @neil-ices-dk happy to have a quick chat about this with Anna and all if needed. Or maybe point me to the vocabs you had in mind so that I can check how they align to or fit in with what we are proposing?

@gwemon you could guest star at our regular vocab management meeting - will send you the invite :)

**Comment by Osanna123** [comment]
Discussed with Gwen, feedback is provided
