### ISSUE TITLE
New unified survey codes for Advice

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#37]
New unified survey coding for referencing in ICES documents, publications, reference lists, and databases. 

The new suggested survey codes can be found following the link:
https://icesit.sharepoint.com/:x:/r/sites/DCTeam/_layouts/15/Doc.aspx?sourcedoc=%7B5B9F4E7C-6DCA-4D9B-A391-0F435F03572D%7D&file=Survey%20codes_ckv_draft.xlsx&action=default&mobileredirect=true

Needs to be checked/discussed before implemented

**Comment by neil-ices-dk** [comment]
@cekv the survey code doesn't follow the pattern we discussed in our last meeting:
[1 Letter][Integer] i.e. A1234 (for an acoustic survey)

**Comment by cekv** [comment]
@neil-ices-dk Anna suggested lettes and a number instead. I was under the understanding that that was the format we went with? Anna and I have gone through the list together. Do you want numbers instead?

**Comment by neil-ices-dk** [comment]
i think we discussed the same thing; the idea being to make it as independent as possible of any semantic meaning, while offering the small carrot that they could at least identify what type of survey series it was i,e,
A acoustic
U underwater TV 
etc

I would accept a further compromise of a two letter prefix for **all** survey types (that would allow use to grow beyond 26 types as well) - but not a mix of 2 and 3 character prefixes.
AC1234
UT1234
etc.

**Comment by Lotte-ices-dk** [comment]
I have the same understanding as Neil; some sort of recognition of survey type and then a code - and a very good list for the experts to use this year, so they can be confident that all information is available with the new code. Until we have that database thing.

**Comment by cekv** [comment]
I have changed codes to two letters and 4 numbers, you can find the new document here:
https://icesit.sharepoint.com/:x:/r/sites/DCTeam/_layouts/15/Doc.aspx?sourcedoc=%7B328C9E78-2842-4751-B1EA-FF8C4689CC4D%7D&file=Survey%20codes_ckv_draft_NEW.xlsx&action=default&mobileredirect=true

I would also like a comment if you would prefer a separate code for a whole survey (which includes all quarters - see the line marked in green in the document above) as well, e.g. for NS-IBTS there is a separate code for each quarter - should we have one code that is for both quarters combined?

**Comment by neil-ices-dk** [comment]
this is timely, WGQUALITY were just asking about this...

**Comment by neil-ices-dk** [comment]
do you have a revised list of the 2 character survey codes, i couldn's see it on the sheet

**Comment by cekv** [comment]
It is there it is the first row.

**Comment by neil-ices-dk** [comment]
> 
> 
> It is there it is the first row.

no that is the survey code type (2 char + the number); 
where is the list of the 2 char survey type codes and their descriptions? (i can see the old list on a separate sheet and some at the bottom of the main sheet, but they are not 2 char)? Sorry if i was unclear - but the 2 char version of the below is what i was after :)


Code | Survey type
-- | --
APT | Acoustic - pelagic trawl survey
ADT | Acoustic - demersal trawl survey
APL | Acoustic - pole and line
BTS | Beam trawl
DTS (GFS) | Demersal trawl survey (Groundfish survey)
GN | Gillnet
GNFN | Gillnet-Fykenet
IPS | Ichthyoplankton survey
PTS | Pelagic trawl survey
TV | Underwater TV survey
LL | Longline survey
COM | Commercial survey
DRG | Dredge/Crustacean travl
SHF | Shelfish
PN | Poundnet
BS | Beach Seine
GR | Grab (shelfish)
HE | Hensen Trawl
MIK | MIK net

**Comment by cekv** [comment]
Ok now I get it :)
I misunderstood

**Comment by cekv** [comment]
https://icesit.sharepoint.com/:x:/r/sites/DCTeam/_layouts/15/Doc.aspx?sourcedoc=%7B328C9E78-2842-4751-B1EA-FF8C4689CC4D%7D&file=Survey%20codes_ckv_draft_NEW.xlsx&action=default&mobileredirect=true

**Comment by neil-ices-dk** [comment]
thanks - i now see a few issues - we're not quite on the same page with the approach. Will leave this til we talk next week.

**Comment by cekv** [comment]
The new and revised list:
https://icesit.sharepoint.com/:x:/s/DCTeam/ERR1fezlmw9HhpUNyJBmh5oBUU1VEIEvDBHdF-66yh0nRA?e=SuwFJU

**Comment by neil-ices-dk** [comment]
looks good Cecilia 👍

**Comment by Lotte-ices-dk** [comment]
So - I'm meeting the FRSG chairs on Thursday - is this the list I can show them and take the beatings for? And just for my own safety; could you spell out to me what will be the next steps on making this database on surveys. Just to ensure the experts that 'their' survey will be very easily found by that code and that the update of that database will be their doing and not ICES Secretariat...
Thanks :) And apologies for being slow...

**Comment by neil-ices-dk** [comment]
we have a 'code' meeting on Wednesday - maybe you should join for this item?

**Comment by Lotte-ices-dk** [comment]
Sure - when is it? Have some appointments during the day, unfortunately.

**Comment by neil-ices-dk** [comment]
> 
> 
> Sure - when is it? Have some appointments during the day, unfortunately.

just sent you the meeting request - 14:00

**Comment by Lotte-ices-dk** [comment]
Thanks for the help yesterday :) Can we - when referring to the controlled vocab in the report - have a EG'specific subset of the vocab to add to the reports? Am I making sense?

**Comment by neil-ices-dk** [comment]
> 
> 
> Thanks for the help yesterday :) Can we - when referring to the controlled vocab in the report - have a EG'specific subset of the vocab to add to the reports? Am I making sense?

by linking specific survey codes to a specific group or groups, subsetting - yes you are 💡

**Comment by neil-ices-dk** [comment]
advice are soliciting feedback abd updates on an online form which needs to be fedback into this board

[survey code form results](https://forms.office.com/Pages/DesignPage.aspx?origin=OfficeDotCom&lang=en-GB&route=GroupForms#Analysis=true&FormId=ziCy4DVXaESR3wXK5f8f3Pxhf0w9PQFCqXFsLbgcI0FUQVJVQkgzR0xRWEYxVjRBQkpRUzIyTzlQSyQlQCN0PWcu&TopView=SurveyResults)

**Comment by cekv** [comment]
@neil-ices-dk unfortunately I do not have access to these results , can you grant me or let me know who can?

**Comment by neil-ices-dk** [comment]
I think Jette is running it, i would suggest you ask her to send an excel of the feedback and we can then evaluate them - we might need a separate meeting to go through them

**Comment by Lotte-ices-dk** [comment]
Hello - I have the feedback and will send it to you @cekv. There are a couple of surveys which need to be fixed quite asap (and it is entirely my fault that you only get informed now, apologies!):

Faroese groundfish summer survey (FO-GFS-Q3); Faroese Deepwater survey (FO-GFS-Q3); Scottish Deepwater Survey (XXXX)

Happy to chat about the updating if you like?

**Comment by pcrjoana** [comment]
Adriana to contact Ruth to clarify some of the codes.

**Comment by Osanna123** [comment]
We close this issue, #173 remains opened.
