### ISSUE TITLE
SMARTD2022-10-07 new SampleType request

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#377]
From Carlos:
Right now in SmartDots we are using the vocabulary SampleType (https://vocab.ices.dk/?ref=1507) for the user expertise. 
Could we add Fecundity and Atresia (in two separate records) to the list of SampleType?
So there could be experts in SampleType Fecundity and experts in Atresia.

**Comment by cmspinto** [comment]
Comment from Cindy:

I guess you could argue that the SampleType for the fecundity and atresia events is gonad. But we need to somehow separate between:
1 gonad, as used for a maturity event = macroscopic maturity staging
2 fecundity = counting and measuring oocytes in a microscopic or histological image 
3 atresia = identifying and counting atretic oocytes per development stage in a histological image

**Comment by neil-ices-dk** [comment]
@Osanna123 to find something on her desk, @pcrjoana to lead her to the desk

**Comment by Osanna123** [comment]
The suggested codes are the information on the events, would fit mostly the Type of Annotation (not in Vocab). 
Message is send to Cindy and Carlos for discussion.
Joana received the comm thread.

**Comment by neil-ices-dk** [comment]
@pcrjoana to re-email Cindy

**Comment by MariaMakri** [comment]
No response
