### ISSUE TITLE
Completing 'Human activities' in vocab

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#378]
I was reviewing the technical guidelines for ecosystem overviews, and there is a full table of human activities which should equate to the vocab.ices.dk codetype, but it looks like this has not been completed 

https://vocab.ices.dk/?ref=1573 

With help from @martinezinigo  we should try and include the full list

Human activity | Explanation and examples
-- | --
Aggregate extraction | Inorganic mine and   particulate waste, maerl, rock/minerals (coastal quarrying), sand/gravel   (aggregates)
Agriculture run-off | Agricultural wastes,   coastal farming, coastal forestry, land/waterfront run-off
Aquaculture | Fin-fish, shellfish,   macroalgae
Coastal development | Artificial reefs,   barrage, beach replenishment, communication infrastructure on the shoreline,   construction phase, culverting lagoons, dock/port facilities, groynes, land   claim, marinas, oil and gas infrastructure found on the coast rather in the   marine environment (e.g. shore pipelines), urban dwellings (i.e. housing and   other buildings)
Desalinization | Removal of salt and other   minerals from the seawater
Fishing | Benthic trawls and   dredging, netting (e.g. fixed nets), pelagic trawls, potting/creeling,   suction (hydraulic dredging)
Harvesting/collecting | Bait digging, seaweed and   saltmarsh vegetation harvesting, bird egg collecting, shellfish hand   collecting, peels, curios
Land-based industry | Industrial effluent   discharge, industrial/urban emissions (air), particulate waste
Military | Military (ships,   munitions)
Navigation dredging | Capital dredging,   maintenance dredging, removal of substrate, spoil dumping
Nuclear power | Nuclear power stations,   water abstraction and thermal discharge
Oil, gas, and hydro | Oil and gas power   stations, thermal discharge (cooling water), water resources (abstraction)
Renewable energy[NH2] | Renewable   (tide/wave/wind) power stations
Research | Animal sanctuaries,   marine archaeology, activities undertaken as part of marine research (e.g.   survey cruises, grab sampling, trawls)
Shipping | Litter and debris,   mooring/beaching/launching, shipping, shipping wastes
Telecommunications | Communication cables
Tourism and recreation | Angling,   boating/yachting, diving/dive site, litter and debris, public beach, tourist   resort, water sports
Waste water treatment | Sewage discharge, thermal   discharge

<p class=MsoCommentText><span class=MsoCommentReference><span lang=DA
style='font-size:8.0pt'><span style='mso-special-character:comment'>&nbsp;<![if !supportAnnotations]><a
href="#_msoanchor_1" class=msocomoff>[NH1]</a><![endif]></span></span></span><span
lang=DA>I would recommend that this is properly aligned to the vocab that was
started and not completed on vocab.ices.dk<br>
<a href="https://vocab.ices.dk/?ref=1573">https://vocab.ices.dk/?ref=1573</a><o:p></o:p></span></p>

<p class=MsoCommentText><span lang=DA><o:p>&nbsp;</o:p></span></p>

<p class=MsoCommentText><span lang=DA>I will add an issue on this and tag you
Inigo; <o:p></o:p></span></p>

<![if !supportAnnotations]></div>

<![endif]></div>

<div style='mso-element:comment'><![if !supportAnnotations]>

<div id="_com_2" class=msocomtxt language=JavaScript
onmouseover="msoCommentShow('_anchor_2','_com_2')"
onmouseout="msoCommentHide('_com_2')"><![endif]><span style='mso-comment-author:
"Neil Holdsworth";mso-comment-providerid:AD;mso-comment-userid:S-1-5-21-1123561945-1035525444-1801674531-5018'><![if !supportAnnotations]><a
name="_msocom_2"></a><![endif]></span>

<p class=MsoCommentText><span class=MsoCommentReference><span lang=DA
style='font-size:8.0pt'><span style='mso-special-character:comment'>&nbsp;<![if !supportAnnotations]><a
href="#_msoanchor_2" class=msocomoff>[NH2]</a><![endif]></span></span></span><span
lang=DA>Is this specifically offshore, or does it include onshore?<o:p></o:p></span></p>

<![if !supportAnnotations]></div>

<![endif]></div>

</div>

</body>

</html>

**Comment by Osanna123** [comment]
done

**Comment by neil-ices-dk** [comment]
@odontaster and @Osanna123 there is an error in the label for POWER2, the 'NH2' is an artefact of the comment i made on a word document (the Ecosystem overview guidelines) and shouldn't be part of the label ;)

**Comment by Osanna123** [comment]
Fixed now, thanks for the heads up
