### ISSUE TITLE
new acoustic code - AC_AgeUnit

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#38]
Currently the Individual Age in the Biotic Biology record is given in years. However we need to add the options to specify the Individual AgeUnit using a vocabulary having years and winter rings in it (Used i HERAS survey). It will be related to AC_AgeSource already in vocab. 

AC_AgeUnit vocab with Y = Years, W = Winter Rings

**Comment by HjalteParner** [comment]
@cekv how should I approve this?

**Comment by HjalteParner** [comment]
@cekv, I think we agreed to have AC_AgeUnit vocab with Y = Years, WR = Winter Rings

**Comment by Osanna123** [comment]
Considering that the vocab could apply to any WGBIOP datasets, I'd recommend not to limit it to AC_

**Comment by HjalteParner** [comment]
As you know using AC_ is the current practise for vocabularies only used by Acoustic so until its needed for other datasets, I think we should keep to this rule, Thanks

**Comment by neil-ices-dk** [comment]
agreed to implement but with the **AC_ removed**; as this will cause an issue down the line when it is no longer specific to acoustic.

**Comment by HjalteParner** [comment]
@neil-ices-dk I disagree. As long as we don't have another use case then we should stick to the current systematic for the users sake. It will be easy to change at any point in time. One of the problems about having common vocabs is that another dataset which start to use the given existing vocab, migth at a term which doesn't make sense for the original dataset. Therefore we allready decided years ago to add the AC_ to specific acoustic vocabs and then relate it to other datasets vocabs instead.

**Comment by neil-ices-dk** [comment]
i'm sorry, but it won't be easy to change once in use and semantically locked in to acoustic through AC_; this was unanimously decided at the meeting. it stands.

**Comment by neil-ices-dk** [comment]
you're right that past practice i.e. TS is a thorn in our side, but does that mean we should continue down a parallel path? Everybody is who exactly?

**Comment by HjalteParner** [comment]
We have had 3 data managers and 2 programmers in acoustic the last couple of years and apparently the reason why we have the AC_ in front, has been lost.

What happens when DATRAS wants -9 in the vocab or another dataset wants something for their need which isn't acceptable for the other datasets?

It can be easely solved by adding relations and only keep truely overarching vocabs in common like Platforms, WORMS etc.

**Comment by HjalteParner** [comment]
I think that if we decide to take a new route to not using prefixes then it should be done for all vocabularies and not just one. I'm in principle fine with removing all prefixes for all the vocabularies used. It will removed the current flexibility between different datasets using the given vocabs - in contrast to the current approach of making relationships between the different types as seen fit.

I don't think we as such have an immediate issue in acoustic doing this i.e. to remove all the current prefixes now (if this code type isn't already occupied by another, that is).

Do any of the data managers / programmers have a view on this then please make your point(s) asap as we would like to move on.

**Comment by cekv** [comment]
AC_AgeUnit will be AgeUnit with Y = Years, WR = Winter Rings, since it is not Acoustics specific vocabulary and other projects will be using this code type in the future.
