### ISSUE TITLE
RDBES: large request to FAO for ASFIS codes

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#384]
50 first species according to the priority order provided by @HenrikK-N have now ASFIS code. Will send again the request to FAO, Stefania Savore, to see when can they create some more codes.
[Request_ASFIScodes_oct22.xlsx](https://github.com/ices-eg/DIG/files/9869748/Request_ASFIScodes_oct22.xlsx)

**Comment by MariaMakri** [comment]
Hi All, 

We have received an updated ASFIS code list:
[ASFIS_sp_2023.xlsx](https://github.com/ices-eg/DIG/files/12575757/ASFIS_sp_2023.xlsx)

Me and Adriana, have compared this to the current RECO export 
[RECO_Export_08-19-2023-01-19-17.csv](https://github.com/ices-eg/DIG/files/12575825/RECO_Export_08-19-2023-01-19-17.csv)

and have identified the codes and descriptions that need to be changed and some that we are unsure about that we could discuss tomorrow at the meeting 

[ASFIS_ICES_DIFF.xlsx](https://github.com/ices-eg/DIG/files/12575858/ASFIS_ICES_DIFF.xlsx)

**Comment by MariaMakri** [comment]
Process all descriptions that are not yellow, send email for the rest.

**Comment by odontaster** [comment]
Changes in codes identified now, happened many years ago. Issue with maintenance. 
I think we can take this maintenance task, not as big as worms.
Proceed to deprecate the wrong codes, add information on reason for deprecation in the long description.

**Comment by Osanna123** [comment]
More investigation pending

**Comment by MariaMakri** [comment]
[remaining requests.xlsx](https://github.com/ices-eg/DIG/files/13279268/remaining.requests.xlsx)
These (in grey) are the only requested codes that were not present in the ASFIS 2023 release

We can close the matter unless we want to ask FAO regarding the issue with the changing codes.

**Comment by pcrjoana** [comment]
I went through all of the ASFIS change files Adriana sent me, and I could not find the change from SRZ to SRG for Diplodus spp.

**Comment by pcrjoana** [comment]
@odontaster to contact FAO to understand when the change from SRZ to SRG happened, and to request the old species list.

**Comment by pcrjoana** [comment]
Update. The folder @odontaster sent me did have the full ASFIS lists. in 2000, Diplodus was already SRG. It seems we inputted it wrong to the database.

**Comment by Osanna123** [comment]
SRZ for Diplodus seems to be created in 2020.
Where is it used? RDBES?
Catch stats are harvested, species lists are not managed by ICES, so the error should not be there.
Not in stock list, not in IC_Species list, not in preliminary catches

**Comment by odontaster** [comment]
sent email to the only submitter of the wrong code to RDBES.

**Comment by MariaMakri** [comment]
Create SRG code for Diplodus and change description to SRZ, while waiting for submitters response. 
Then the SRZ code will be changed to Semele radiata.

**Comment by odontaster** [comment]
All changes implemented. Submitter resubmitted with the new code.

**Comment by MariaMakri** [comment]
Some changes were missed: 

ILU (Carlarius heudelotii) was changed to SMC (Carlarius heuderlotii) in the 2023 list. ILU was deleted. we still have ILU in specASFIS
