### ISSUE TITLE
RDBES: code type or types for non ICES_Areas geographical references in stocks

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#385]
They need codes for Functional Units and for 6aN, and 6aS.

**Comment by odontaster** [comment]
Do they also need Sandeel areas? @HenrikK-N

**Comment by odontaster** [comment]
27.4.a.e
27.4.a.w
27.4.b.e
27.4.b.w
27.4.outFU
27.5.a.2.n
27.5.a.2.s
27.6.a.n
27.6.a.outFU
27.6.a.s
27.6.b.outFU
27.7.a.n
27.7.a.s
27.7.outFU
27.8.c.e
27.8.c.w
27.9.a.c
27.9.a.c.n
27.9.a.c.s
27.9.a.n
27.9.a.s
27.9.a.s.a
27.9.a.s.c
FU.10
FU.11
FU.12
FU.13
FU.14
FU.15
FU.16
FU.17
FU.18
FU.19
FU.20-21
FU.22
FU.23-24
FU.25
FU.26
FU.27
FU.28-29
FU.30
FU.31
FU.32
FU.33
FU.34

**Comment by neil-ices-dk** [comment]
@odontaster to check in RECO management whether there is a non-visible list (Nephrops FU's) already setup; otherwise it is a new CodeType to be established;
"Nephrops Functional Units"

**Comment by HenrikK-N** [comment]
At the last Core Group meeting, it was agreed to suggest to have only one code type for the species/stock specific areas, so there would be only one extra field to add to the data model, and the users would only have to check one extra area field for an area (and not to check several area fields depending on several area types, all fields would be empty except one field. It is suggested to call the code type ‘Area species specific’.

**Comment by odontaster** [comment]
Hi @HenrikK-N we will discuss your message again next tuesday, but in the last RMG we spoke about this issue and we agreed that the technical problem of RDBES, not being able to set up a field that dynamically shows different codes in function of the value of another field (or alternatively, having a single field that includes values of several code types), can not be solved through the vocabs, which should remain independent of technical requirements and clear on their scope. RMG did not accept the request to create a Code Type containing all Areas used in stocks, official or not, and agreed that Nephrops and sandeel areas deserve a Code Type each, and I will continue working to reference the remaining ones for mackerel with the relevant POs, which will end up in another Code Type. As always, you are more than welcome to join RMG to further argument if needed.

**Comment by odontaster** [comment]
27.8.c.e
27.8.c.w
27.9.a.c
27.9.a.c.n
27.9.a.c.s
27.9.a.n
27.9.a.s
27.9.a.s.a
27.9.a.s.c
Seem to come from HANSA, there are maps in the stock annexes for pil and ane. We might need to ask experts for specific coordinates of the limits.

**Comment by odontaster** [comment]
27.6.a.n
27.6.a.s
Have a reference in a valid stock 
Herring (Clupea harengus) in Division 6.a North (North of 56°00’N and East of 07°00’W), autumn spawners (West of Scotland)
Herring (Clupea harengus) in Division 6.a South (South of 56°00’N and West of 07°00’W) and 7.b-c (northwest and west of Ireland)

**Comment by odontaster** [comment]
Relevant reference: WGHANSA 2019, section 12
https://doi.org/10.17895/ices.pub.4983

**Comment by odontaster** [comment]
Almost final list of codes, with relevant references:
[Unofficial_areas_work.xlsx](https://github.com/ices-eg/DIG/files/10849859/Unofficial_areas_work.xlsx)
- Nephrops functiona units ongoing process
- RDBES requirement for a single list.

**Comment by evabrna** [comment]
create single code type AssessmentArea 
description: Areas used for single stock assessments not included in FAO fishing areas
@odontaster

**Comment by odontaster** [comment]
I find AssessmentArea as CodeType a bit confussing. I would suggest:
ICES_ExtraAreas
ICES_Area_nonFAO
ICES_Area_unofficial
...
And description:
Areas used for single stock assessments not included in FAO fishing areas

This reminds me that we could review the ICES_Area code type description, as at the moment is not even mentioned the FAO codes.
I would suggest:
Subset of FAO inland and marine fishing areas, as used in ICES products. 
https://www.fao.org/fishery/en/area/search

**Comment by neil-ices-dk** [comment]
> Area_nonFAO

I think this is the only acceptable one of your suggestions (removing ICES) as these are not official ICES areas right?; do we need the underscores?

**Comment by evabrna** [comment]
Change description for ICES_Area: FAO Major Fishing Areas, subareas, divisions and subdivisions used by ICES in products
