### ISSUE TITLE
Underwater Noise - splitting source-event types

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#386]
Split source event: “Sonar or acoustic deterrent” NE – Event: Source_event
Currently this source event is combined, it is suggested to split into two separate source-event types. 
-	Vocab, http://vocab.ices.dk/?ref=1431 need to add two new terms: 
o	Sonar
o	Acoustic deterrent
-	And deprecate current term “Sonar of acoustic deterrent” but leave visible

**Comment by neil-ices-dk** [comment]
also remove

**Comment by pcrjoana** [comment]
The codes have been added, but just a question on the "Sonar" description. Should it be "Sonar" or "Sonar deterrents"? The phrasing of the old code makes it difficult to interpret.

**Comment by neil-ices-dk** [comment]
@pcrjoana for the label description, go with "Sonar deterrents" 🔈
