### ISSUE TITLE
OSPAR: Biodiversity Seals new references

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#39]
For the new Seals data format we are missing some CodeTypes and Codes as below.
Planned data call is scheduled to be sent out by the end of this week (w4 2021), so answer on the request needs to be fast.

CodeType | New Code | Description | Long description
-- | -- | -- | --
SpecWoRMS | 137080 | Halichoerus grypus | Gray seal
  | 137084 | Phoca vitulina | Harbour seal
  |   |   |  
BD_SealAU   (new) |   | Seal assessment unit   area references |  
  | _tbd_ | _under revision_ |  
  |   |   |  
PARAM | tbd | Total count (all   ages) |  
  | tbd | Adult/juvenile count |  
  | tbd | Pup production   abundance |  
  | tbd | Pup count (all) |  
  | tbd | Pup count   (Whitecoats) |  
  | tbd | Pup count (Moulted   pups) |  
  | tbd | Pup count (Dead pups) |  
  | tbd | Pup count (other   categories) |  
  |   |   |  
(BD_)EstimateType   (new) |   | Type of abundance   estimation |  
  | tbd | Count on a single day |  
  | tbd | Counts over multiple   days |  
  | tbd | Counts over multiple   years |  
  | tbd | Modelled estimate |  
  | tbd | Maximum |  
  |   |   |  
BD_ActivityType   (new) |   | Activity type |  
  | GSM | Grey seal moult |  
  | GSB | Grey seal breeding |  
  | GSS | Grey seal summer |  
  | HSB | Harbour seal breeding |  
  | HSM | Harbour seal moult |  
  |   |   |  
BD_UnitType   (new) |   | Unit type |  
  | tbd | Haulout unit |  
  | tbd | Hg breeding unit |  
  |   |   |  
GeometryType | grid-cell-centroid | grid cell centroid |  
  | polygon | polygon |  
  |   |   |  
  |   |   |  
BD_CountMethod | photo | photo |

**Comment by neil-ices-dk** [comment]
@Osanna123 
1. For pup count: label should include "Seal pup....count"
2. Can we clarify 'Maximum' in EstimateType
3. Can we clarify ActivityType, why separate species labels are needed?
4. BD_UnitType (new) - could we get some definitions of these

**Comment by Osanna123** [comment]
Updated list:
(CodeTypes in **bold** are new)

CodeType | New Code | Description | Long description
-- | -- | -- | --
SpecWoRMS | 137080 | Halichoerus grypus | Gray seal
  | 137084 | Phoca vitulina | Harbour seal
  |   |   |  
PARAM | S-C-Tot | Total seal count (all   ages) |  
  | S-C-Ad/Juv | Seal adult/juvenile   count |  
  | SP-P | Seal pup production |  
  | SP-C-A | Seal pup count - all |  
  | SP-C-WC | Seal pup count -   Whitecoats |  
  | SP-C-MP | Seal pup count -   Moulted pups |  
  | SP-C-DP | Seal pup count - Dead   pups |  
  | SP-C-Oth | Seal pup count -   other categories |  
  |   |   |  
**EstimateType   (new)** |   | **Type of abundance   estimation** |  
  | Count-1day | Count on a single day |  
  | Count-over-days | Counts over multiple   days |  
  | Count-over-years | Counts over multiple   years |  
  | Modelled | Modelled estimate |  
  | Average | Average count | Several counts were   made and an average (mean) of these counts is reported
  | Maximum | Maximum count | Several counts were   made but only the maximum (highest) count is reported
  |   |   |  
**ActivityType   (new)** |   | **Activity type** |  
  | moult | moulting season |  
  | breeding | breeding season |  
  | summer | summer colonies |  
  |   |   |  
**BD_UnitType   (new)** |   | **Unit type** |  
  | HOU | Haulout unit |  Haulout unit is an arbitrary unit which can represent part of what may biologically considered a haulout (e.g. a count associated with the location of an individual photograph), a haul out or a cluster of haulouts. Haulout units for which the spatial extent is < c. 2.5 km can be input as Points. Polygons should reflect the approximate extent of haulouts/clusters and can be used instead of points for any haulout unit but must be used for any haulout units which are >2.5 km in spatial extent.
  | BU | Breeding unit |  Breeding unit refers to a grey seal breeding colony(ies) on which pup counts and pup production estimates are provided. Irrespective of spatial extent, such colonies can be represented by points or polygons and must be identifiable (i.e. consistent) between surveys.
  |   |   |  
**BD_Data_resolution**   (new) |   | **Resolution the unit   data are reported by** |  
  | HU | by haulout units |  
  | BU | by breeding units |  
  | 5km-grid | 5 km grid |  
  |   |   |  
**BD_Data_type   (new)** |   | **Reported data type** |  
  | PA | presence and absence |  
  | P | presence only |  
  |   |   |  
GeometryType | Polygon | Polygon |  
  | MultiPolygon | MultiPolygon |  
  |   |   |  
BD_CountMethod | photo | Count from photo | Identification and   count (manually or digitally) from a photograph
  |   |   |  
**BD_SealAU   (new)** |   | **Seal assessment unit   area references** |  
  | 1 | Southwest Scotland |  
  | 2 | West Scotland |  
  | 3 | Western Isles |  
  | 4 | North coast and   Orkney |  
  | 5 | Shetland |  
  | 6 | Moray Firth |  
  | 7 | East Scotland |  
  | 8 | Northeast England |  
  | 9 | Southeast England |  
  | 10 | South England |  
  | 11 | Southwest England |  
  | 12 | Wales |  
  | 13 | Northwest England |  
  | 14 | Northern Ireland |  
  | 15 | Ireland |  
  | 16 | French North Sea and   Channel coast |  
  | 17 | Belgium coast and   Dutch Delta |  
  | 18 | Wadden Sea |  
  | 19 | Limfjord |  
  | 20 | Kattegat |  
  | 21 | Iceland |  
  | 22 | Skagerrak |  
  | 23 | Norway MA1 |  
  | 24 | Norway MA2 |  
  | 25 | Norway MA3 |

**Comment by cekv** [comment]
BD_UnitType change to PopulationUnitType

**Comment by cekv** [comment]
BD_Data_type (new) merge to presence flag

**Comment by Osanna123** [comment]
BD_CountMethod additional request for video and photo&video (suggested multimedia instead)
BD_Data_type - presence CodeType does not seem to be fitting here

**Comment by Osanna123** [comment]
As agreed at the RMG meeting: 
CountMethod - new codes for video and mixed media
Data_type - create a generic CodeType CountType with the initially suggested options
