### ISSUE TITLE
RECO sprint question on the application users

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#390]
Right now RECO Management Studio application ca neb used by anyone with ICES login. 
Due to the sensitivity of the functions, and linkage to the databases, it was suggested to limit the full functionality of the  application only to the data managers. All others can have reading rights, bot not writing

**Comment by neil-ices-dk** [comment]
@mehdiabbasi all data managers fully agree and support restricting writing rights to DM's **only**;

**Comment by mehdiabbasi** [comment]
@neil-ices-dk @Osanna123 I set write permission for all members of DCDBmanager and read for all DCDBDeveloper. It is ready on the test server to test
