### ISSUE TITLE
"Fresh" code needed for SmartDots

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#392]
An extra "fresh" code is needed for SmartDots. 
They would need a code that covers these conditions: gonads are sampled in a laboratory or action hall were there is no heating and temperatures are cool

The code "fresh and kept at room temperature" from <METPT><https://vocab.ices.dk/?ref=200> could potentially cover it, but would need some added information, as Cindy thinks the description would confuse users.

**Comment by neil-ices-dk** [comment]
METST - propose a term "Room below normal temperature"
@pcrjoana to ask Cindy for a precise description that covers all labs in this situation

**Comment by pcrjoana** [comment]
@pcrjoana to refresh this.
