### ISSUE TITLE
RDBES: New code 'Berried' in code type BiologicalMeasurementType

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#399]
Hi Adriana

Can you add the code 'Berried' that was agreed with the WGBIOP chairs and Core Group today.
Code: ‘Berried’, Description: ‘Berried female for crustacean’ in the code type BiologicalMeasurementType.

Cheers Kjems

**Comment by odontaster** [comment]
[//vocab.ices.dk/?ref=1606](https://vocab.ices.dk/?ref=1606)
