### ISSUE TITLE
Add a Unique identifier to all the codes

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/DIG#400]
The stock codes need to report a Globally Unique Identifier (GUID) to FIRMS.
In order for each stock to have a GUID associated and the best place to do that is RECO. 

This was also an ISSUE in the advisory board team, maybe someone could link this issue.

**Comment by evabrna** [comment]
https://github.com/ices-tools-prod/icesSAG/issues/216 
add new code type GRSF Global Record of Stocks and Fisheries unique identifiers @odontaster 
please download and check the list of UIs and get Mehdi to import to RECO

**Comment by neil-ices-dk** [comment]
@odontaster we have a deadline for this - the FIRMS meeting in **June**!

**Comment by odontaster** [comment]
Reminder sent to Aureliano today.

**Comment by odontaster** [comment]
Dear Adriana,

Sorry for the delay. With the aim of providing the full list of ICES stocks vs. the FIRMS / GRSF unique identifiers we needed more time to ensure the overall consistency and uniqueness of the records.

The attached file is indeed not a final one since 8 Nephrops stocks have not been loaded yet.
And for other Nephrops, the semantic identifiers (column I) will change as well since we have now fixed their area codes in the FIRMS/GRSF database.

All the other records are now fine with their UUIDs (see column J).

We have only two questions for you in cells M133 and M317. Please, if you can provide feedback on that.

We should load and assign the remaining UUIDs in the very next days, we will inform you when done. (They will arrive jointly with the Spring!) 😉

Thanks for the continued collaboration and sorry again for the delay.

**Comment by odontaster** [comment]
Suggested action points for Adriana:
- Create Code Type GRSF  with description "Subset of FAO Global Record of Stocks and Fisheries unique identifiers"
- Populate it with the list received from FAO, description being stock code?
- Link each GRSF code to corresponding ICES_StockCode, is this needed?

**Comment by pcrjoana** [comment]
UUID (column J on the file above) to be used as the code and FIRMS title (column H on the file above) to be used as the description. Link to ICES stock codes.

Title for CodeType "FAO Global Record of Stocks and Fisheries Unique Identifiers".

@mehdiabbasi to create a link to the external codes.

**Comment by neil-ices-dk** [comment]
example https://ckan-grsf.d4science.org/dataset/a9ea3b7a-f115-3f8c-b4bd-bfc772298ab2

**Comment by odontaster** [comment]
Added external relation through new available feature available as bulk upload.

**Comment by odontaster** [comment]
Aureliano reviewed our vocab and asked for some changes:
-They believe the GRSF Semantic ID would be more useful as description (Column J)
- The FIRMS title could be kept as long description
- The external link should be this
- [https://i-marine.d4science.org/web/grsf/data-catalogue?path=/dataset/](https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fi-marine.d4science.org%2Fweb%2Fgrsf%2Fdata-catalogue%3Fpath%3D%2Fdataset%2F908e83a9-955d-3082-b4d1-0dfe95931da6&data=05%7C01%7CAdriana.villamor%40ices.dk%7C6fc646361cd94d5cedcb08db847ab0f0%7Ce0b220ce5735446891df05cae5ff1fdc%7C0%7C0%7C638249436069849259%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HoplWgY2msyw2xdLS%2FdVt08aULZr2UGSDxe4B6A8u2I%3D&reserved=0)<GRSF UUID>

**Comment by MariaMakri** [comment]
RMG agrees with FAO requests.
@neil-ices-dk @cekv please let us know if you have any comments.

**Comment by neil-ices-dk** [comment]
all good from me 👍🏼

**Comment by cekv** [comment]
I would think it is ok - since you are only changing descriptions. But I m not the expert... ;)

**Comment by odontaster** [comment]
https://vocab.ices.dk/?codetypeguid=3b2c4f50-c75f-446a-a15b-c5693a829dd5
RMG kindly requests @mehdiabbasi to perform a one-time task:
- Either delete all codes in the codetype
- Or change descriptions and external links programatically

**Comment by odontaster** [comment]
Mehdi deleted all codes in the code type. 
Bulk uploaded all codes, descriptions and long descriptions. Bulk uploaded all relations to ICES_StockCode. Bulk uploaded all external links.
Done
