### ISSUE TITLE
Add 'Sexual' to the JCDP behaviour

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/DIG#402]
Link Sexual Behavior with Cetaceans.

It was requested by one submitter for observation of Whales

**Comment by pcrjoana** [comment]
What kind of sexual behaviour are they interested in? We have codes for courtship display, courtship feeding, or for copulating that could work.

**Comment by evabrna** [comment]
We needed to link this to the cetacean database (already done)
![image](https://user-images.githubusercontent.com/119604756/214294157-05c0817b-b8c5-47b1-97a7-fb2b245f100f.png)
and to add it into the format to the Behaviour 1,2 and 3 lookup options. Also done but the new format is not on the web yet.
