### ISSUE TITLE
DOME Datasets rev. for DP

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#405]
https://vocab.ices.dk/?ref=102
DOME contaminants datasets have brief labels/descriptions not useful for data users in Data Portal, so they are suggested to be enhanced:
Biota CF to Contaminants, biol.effects and diseases in biota
Seawater CW to Contaminants in seawater
Sediment CS to Contaminants and biological effects in sediment

**Comment by odontaster** [comment]
Without abreviations in biol.
