### ISSUE TITLE
Continuous underwater noise: need two new codes to be added to RecorderType

### ISSUE THREAD

**Issue by evabrna** [ices-eg/DIG#409]
Need two new codes to be added to RecorderType CodeType: //vocab.ices.dk/?ref=1585
“Aural-M2”  - http://www.multi-electronique.com/aural.html
"µAURAL" - http://www.multi-electronique.com/uaural.html

**Comment by odontaster** [comment]
Avoid special characters in the codes, can be used in the descriptions. Keep links in the long descriptions.
