### ISSUE TITLE
Review RS_ValueType vocabulary

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#41]
The existing RS_ValueType (http://vocab.ices.dk/?ref=1625) vocabulary seems to mix different concepts in one vocabulary. Since it is not live yet, it would be worth discussing yet.

**Comment by Osanna123** [comment]
RDBES team to revise the concepts in this CodeType, where each Type and Unit are spelled out together

**Comment by Osanna123** [comment]
@HenrikK-N, could you please provide an update for this issue?

**Comment by HenrikK-N** [comment]
The list should stay as it is.
The code 'Year' should be deleted. @EjazAtIces: Ejaz will let Cecilia know when it can be done in RECO.
The description 'mili meter' should be updated to 'Milimeter'.
All descriptions should be updated to capital start letter if not already.

**Comment by EjazAtIces** [comment]
@HenrikK-N  we have data connected to "Year". We have to contact users. I will let Cecilia (@cekv )  know once deleted in RES

**Comment by neil-ices-dk** [comment]
> 
> 
> The list should stay as it is.
> The code 'Year' should be deleted. @EjazAtIces: Ejaz will let Cecilia know when it can be done in RECO.
> The description 'mili meter' should be updated to 'Milimeter'.
> All descriptions should be updated to capital start letter if not already.

are you sure about that spelling of millimetre @HenrikK-N ?

**Comment by HenrikK-N** [comment]
@EjazAtIces: The spelling is 'Millimeter', but please always check spelling yourself, so we avoid double corrections (and Thanks Neil).

**Comment by EjazAtIces** [comment]
@HenrikK-N , @neil-ices-dk  according to Cambridge Dictionary (millimetre in UK) and (millimeter in US).

**Comment by neil-ices-dk** [comment]
yes - my point was the original spelling you proposed was neither of these; UK english is the default for ICES, but US english is used in some specific vocabs.

**Comment by EjazAtIces** [comment]
@neil-ices-dk thanks and its good to know UK English is default for the ICES.

**Comment by neil-ices-dk** [comment]
this is part of the #68

**Comment by pcrjoana** [comment]
@HenrikK-N @davidcurrie2001  we recommend updating the list as below, so that we can semantically link them to existing used vocabularies, which will make these terms interoperable with other data. When you discuss vocabularies in the RDBES meetings, we strongly suggest inviting the data officer (Cecilia).

weightg | Weight in grams
maturityscale | Type of maturity scale
lengthmm | Length in millimeters
sex | Sex as male, female, transitioning or undetermined
agewr | Age in winter rings
ageyear | Age in years

**Comment by Osanna123** [comment]
> @HenrikK-N @davidcurrie2001 we recommend updating the list as below, so that we can semantically link them to existing used vocabularies, which will make these terms interoperable with other data. When you discuss vocabularies in the RDBES meetings, we strongly suggest inviting the data officer (Cecilia).
> 
> weightg | Weight in grams
> maturityscale | Type of maturity scale
> lengthmm | Length in millimeters
> sex | Sex as male, female, transitioning or undetermined
> agewr | Age in winter rings
> ageyear | Age in years

@HenrikK-N @davidcurrie2001 with your silent approval, we are going to implement the suggestion above, with only one correction matirutyscale --> SMSF | WKSMSF 2018 Maturity Scale

**Comment by HenrikK-N** [comment]
Please do not make any changes. I think silent approval is not the way forward. I will have to get back to the Core Group with you suggestions.

**Comment by pcrjoana** [comment]
@HenrikK-N do you have a timeline on this, please?

**Comment by cekv** [comment]
Suggested code for maturity was accepted by Henrik and David on the 8th of June 2021.
Also RS_ was dropped and code type was renamed to ValueUnitOrScale by the wishes of the RDBES core group.

**Comment by cekv** [comment]
Implemented in RECO the 8th of June
