### ISSUE TITLE
SpecWoRMS and SpecASFIS requests

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#410]
In this ticket we can enumerate ordinary SpecWoRMS and SpecASFIS requests

**Comment by odontaster** [comment]
For REC12 we need to insert SpecWoRMS
105825 Hydrolagus affinis

It exists also in ASFIS so I will create also the code SpecASFIS
CYA Hydrolagus affinis

Link them with eachother and both to RDBES Datasets.
Implemented 1st February 2023 by @odontaster

**Comment by odontaster** [comment]
Need to add Branchiostoma lanceolatum to SpecWoRms for ELDB
https://www.marinespecies.org/aphia.php?p=taxdetails&id=104906

**Comment by odontaster** [comment]
Needed for preliminary catches submission Hydrolagus spp:

- Added https://www.marinespecies.org/aphia.php?p=taxdetails&id=105734
to SpecWorms.
- Added HYD to SpecASFIS
- Linked both with each other and to RDBES

**Comment by odontaster** [comment]
For preliminary catches needed Solea spp
Added 126132 to SpecWoRMS
https://www.marinespecies.org/aphia.php?p=taxdetails&id=126132
Added SOO to SpecASFIS
Linked them both to RDBES and between them

**Comment by MariaMakri** [comment]
The following ASFIS/APHIA codes were added.
Code relations were created between ASFIS and Aphia, between Aphia and RDBES (Datasets code type) and ASFIS and RDBES.


[asfis_checked_matched.xlsx](https://github.com/user-attachments/files/17279049/asfis_checked_matched.xlsx)

**Comment by MariaMakri** [comment]
Final list of updated descriptions and links between ASFIS and APHIA: "P:\Data_Centre\Reference documents and lists\Procedures\ASFIS-APHIA documentation\asfis_2024_diff_newnames_matched_final0403.xlsx"

**Comment by MariaMakri** [comment]
Added these codes: [data_differences.xlsx](https://github.com/user-attachments/files/19504025/data_differences.xlsx)

**Comment by MariaMakri** [comment]
Added: 

GJG	Lepadogaster purpurea	126519  	Lepadogaster purpurea
GDB	Diplecogaster bimaculata	126513	Diplecogaster bimaculata

**Comment by MariaMakri** [comment]
I have now added the two ASFIS codes and linked them to the already existing AphiaIDs: 
FKG   Sphaerechinus granularis   124427
WRX   Labrus spp   126021

**Comment by MariaMakri** [comment]
Added Aphia and ASFIS plus links

[fullmatchtoadd_2.csv](https://github.com/user-attachments/files/25939639/fullmatchtoadd_2.csv)

[fullmatchtoadd_ifremer.csv](https://github.com/user-attachments/files/25939643/fullmatchtoadd_ifremer.csv)

**Comment by MariaMakri** [comment]
@MariaMakri to put these files in the sharepoint.  (under requests)

**Comment by MariaMakri** [comment]
Done: https://icesit.sharepoint.com/:x:/s/icesintranet/datacentre/IQDbtplXyGrkQYoHJ_2-jiKBAbG8euNg18KnSdMfgusi9VE?e=tTEVVb
https://icesit.sharepoint.com/:x:/s/icesintranet/datacentre/IQBr6Rnk4Yo_S6AkEXnoUL13AawjlWFCPPiUuqQ3wimKEo0?e=8AwEjk

**Comment by MariaMakri** [comment]
Added these codes and links as well: https://icesit.sharepoint.com/:x:/s/icesintranet/datacentre/IQDlkE2kxYEoSIMv1LrAGroNAZD7XNMTlh6GXHyb-c_KW8Y?e=KzBPU6

**Comment by MariaMakri** [comment]
Added 103733 Diazona violacea

**Comment by MariaMakri** [comment]
https://icesit.sharepoint.com/:x:/s/icesintranet/datacentre/IQCiHIr7n6qKQa-RowuXjAK1AXH_oT_-_gYu9hiXeiFKQ_Y?e=FRRQvg

**Comment by MariaMakri** [comment]
Added ASFIS and AphiaIDs "P:\Data_Centre\Reference documents and lists\Procedures\ASFIS-APHIA documentation\AddingNewAphiaASFIS\fullmatchtoadd_vocab_fao_species_to_add_290526.csv"
