### ISSUE TITLE
ENV2023-01-11 DOME Litter codes request

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#411]
While we're working on the new Litter format proposal for DOME, a submitter wants to deliver data in water and sediment asap, and needs codes as follows

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/anna/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/anna/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

  | Progress and code | Description | Comment_AO | Comment_TW
-- | -- | -- | -- | --
LTPRP or PARAM ot TYPPL (see comment in right-hand column) | Done LTREF H01 + H01 code for foam| Expanded cellular plastic | I expect shapes to be further discussed at the WGML-2023,   but they seemed quite redundant related to the litter categories and material   type | I agree, simple shape descriptions like   "rectangle", "triangle", "sub-irregular", dont   seem useful. Maybe the descriptive codes I have requested here should not be   shape/SHP codes, but some kind of morphological descriptions that distinguish   the type of microlitter, and can be recorded from basic analysis with a light   microscope. For example "preproduction pellet","film",   "expanded cellular plastic", "synthetic sponge",   "foam", "filament >50 um thick", "micro fibre   <50um thick", seem relevant for linking microlitter to its source.
" | Done: PARAM LT253 | Waxy semisolid |   | To distinguish the fraction of paraffin-like particles,   important in North Sea/Skagerrak.
" | cancelled/changed - to be reported with H01 code for pre-prod pellets and SIZCL  | Pre-production pellet (<1mm) |   | For smaller, often irregularly shaped, preproduction   powders, often referred to as fluff, Karlsson et al. (2018). https://www.sciencedirect.com/science/article/pii/S0025326X18300523
" | E.g.   "TAC1", "TAC2", "TAC3". Done: PARAM LT253 | consider codes for tactile characteristics such as   "semisolid" | I expect tactile characteristics to be further discussed   at the WGML-2023 | Yes, would be good if they would include tactile   characteristics for the new format. For this submission, an important aspect   of the GU Byfjorded water data is a substantial proportion of micro-paraffin   particles in most/all samples. Is there a way that these can be distinguished   from the more usual, harder, thermoplastics? Would it work for example to   create a LTPRP or PARAM code (e.g. SHP6 for "waxy semisolid") to   avoid loss of information for this submission?
MATRIX | E.g.   "SEDfrac". DONE: new codes for specific fractions are offered, also MATRX SEDtot + METPT SVW | "Sediment" or "Size fractionated   sediment" | Please check if any of these work for you, and let me know   if more codes need to be added | None of the existing codes, such as those you listed with   specific grain sizes, would work, as the size classes do not match those in   the datasets from either of the two universities.     However, I am a bit confused now, as when I searched for MATRX options   within LT, I found only BE, SF, WC, and SF. I think I also got an issue   raised by DATSU related to invalid MATRX codes for LT. Should I just record   SF in the MATRX column, or can a more appropriate code be created and used   such a "sediment" (our sediment could be described as "size   fractionated sediment")? A code like this might be widely applicable to   diverse microlitter submitters.
LTSZC | Done. 38 | microns 100-299 | Would you like me to create these size categories or   follow the EMODnet/TGML recommendations for standardized size categories   reporting? | Adil discussed as standard (from OSPAR?) at WKLIDA. Yes,   please create for GU sed and water datasets
LTSZC | Done. 39 | microns 300-999 |   | Adil discussed as standard (from OSPAR?) at WKLIDA. Yes,   please create for GU sed and water datasets
LTSZC | Done. 40 | 1 mm-5 mm |   | Adil discussed as standard (from OSPAR?) at WKLIDA. Yes,   please create for GU sed and water datasets
LTSZC | Done. 41 | microns 50-299 |   | Non-standard but needed for ORU sediment and water   datasets
LTSZC | Done. 42 | microns 300-5000 |   | Non-standard but needed for ORU sediment and water   datasets
LTSZC | Done. 18 | 5 mm-25 mm |   | Not discussed at WKLIDA but needed for a few records   within the GU datasets, if they are not to be excluded. 5-25 mm was proposed   for mesolitter by Kroon et al., 2018 (Nature).
MUNIT | Done (partially). items/kg | items/kg (dry weight) sediment | Dry weight will be covered by BASIS, sediment is covered   by MATRX. Items/g exists already, items/kg can be added | OK, then just items/kg should work. Then I just need to   add a column titled BASIS with the code D, or?
TYPPL | Cancelled. AC | akrylglas/perspex | Request should be sent to EMODnet Chem/TGML as well for   adding an H05 category | Could a DOME code be created for the current submission?
TYPPL | Done. PES | Polyester | Ok to add |  
METPT | Cancelled. SVW| Size fractionated |   | Useful to describe pretreatment of sediment samples. I can   leave this column blank.
METCX | Done. ALDKNC | "KOH + NaOCl digestion of biogenic matter" | Right now, variety of digestion methods is added to the   METCX. If WGML suggests moving it to METPT for plastics, we’ll look at it   with MCWG as well. | You are right, I should have been looking in METCX, not   METPT. As also suggested by Adil in his sediment spreadsheet, it would be   useful to have a METCX code for digestion using a mixture of KOH and NaOCl   (Strand & Tairova, 2016). e.g. "KOH + NaOCl digestion" (we call   it Strand solution).

</body>

</html>

**Comment by evabrna** [comment]
LTSZC okay to implement 
MUNIT items/kg OK. Dry weight to think about
Polyester okay to add
Digestion generic code/description

**Comment by Osanna123** [comment]
![image](https://user-images.githubusercontent.com/17157764/220099112-a3a763a1-1d2e-4310-b1e8-020b047a2528.png)
![image](https://user-images.githubusercontent.com/17157764/220099897-6b2ecfc2-f63a-4347-9898-0c1c0ba341a6.png)
![image](https://user-images.githubusercontent.com/17157764/220100451-e602f6c2-b676-411b-9e9f-f75d5f895c7d.png)
![image](https://user-images.githubusercontent.com/17157764/220110557-94652180-6f0f-4f6b-b327-8615ecf3b2b7.png)

**Comment by Osanna123** [comment]
also see #416

**Comment by Osanna123** [comment]
MATRX SEDfrac is still in discussion, but check https://vocab.ices.dk/?CodeID=26973 vs. https://vocab.ices.dk/?ref=55

**Comment by Osanna123** [comment]
[Suggestion_fibres-lines from Lisa Roscher.docx](https://github.com/ices-eg/DIG/files/10968664/Suggestion_fibres-lines.from.Lisa.Roscher.docx)
[Gagoetal.2019.pdf](https://github.com/ices-eg/DIG/files/10968666/Gagoetal.2019.pdf)
[Khnetal.2020.pdf](https://github.com/ices-eg/DIG/files/10968667/Khnetal.2020.pdf)
[TanakaTakada2016.pdf](https://github.com/ices-eg/DIG/files/10968668/TanakaTakada2016.pdf)

**Comment by evabrna** [comment]
MATRX we can allow ranges
TYPPL ok
PARAM ok

**Comment by Osanna123** [comment]
Some details might have not be logged here. check ENV2023-01-11 in the accessions.
