### ISSUE TITLE
New CodeTypes for Fecundity and Atresia

### ISSUE THREAD

**Issue by evabrna** [ices-eg/DIG#415]
New CodeTypes for the Fecundity and Atresia format are needed.

1. OocyteStage
Description: The most advanced oocyte development stage present
Code and description
1 previtellogenic oocytes, 
2 early vitellogenic oocytes< 400 µm, 
3 vitellogenic oocytes,
4 migratory nucleus, 
5 hydrated oocytes 

2. EggFlag
Description: Egg stages present
Code and description
0 No eggs present
1 New eggs present
2 Residual eggs present
3 New and residual eggs present

3. HydratedOocyteFlag
Description: Hydration state present 
Code and Description
0 no hydrated oocytes present
1 Early hydration
2 Advanced hydration
3 Late hydration

4. FecundityFlag
Description: The type of the sample that was analyzed
Code and description
f fecundity
b batch fecundity

**Comment by cekv** [comment]
@evabrna to contact Cindy for documentation for hydration score/oocyte stage (i.e. manual)

**Comment by evabrna** [comment]
after our meeting with Cindy:
OocyteStage,EggFlag and HydratedOocyteFlag shouldn't be new code types. There is already a code type called HistologicalScreening in RECO. Missing codes could be added there
![image](https://user-images.githubusercontent.com/119604756/222369488-a7c73411-cf57-4a19-be54-a83ad9ee8057.png)

FecundityFlag
What   type of sample was screened, p = potential fecundity sample or b = batch   fecundity sample to be discussed in WGMEGS 2023

**Comment by evabrna** [comment]
documentation here file:///C:/Users/evab/Downloads/SISP%205%20-%20WGMEGS%20Manual%20for%20AEPM%20and%20DEPM.pdf

**Comment by evabrna** [comment]
New field POFStage, link to code type called POF staging (smartdots) and add what is missing
![image](https://user-images.githubusercontent.com/119604756/222383274-3da9c812-fe7e-4f7c-8ff3-610b78a8455e.png)

**Comment by evabrna** [comment]
@evabrna to add missing codes-make them visible in RECO
check with Cindy if existing codes are okay

**Comment by evabrna** [comment]
Cindy approves the codes;she recommends removing te 's' from EggsStage1 etc..

**Comment by pcrjoana** [comment]
@evabrna and @Osanna123 to meet with Cindy.

**Comment by MariaMakri** [comment]
To check if these are implemented
