### ISSUE TITLE
Litter: implement EMODnet H01 microlitter categories

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#416]
Suggestion to add new LTREF for the H01 (EMODnet micro-litter types) and respective new CodeType. Also, to create respective PARAM codes

https://vocab.seadatanet.org/v_bodc_vocab_v2/browse.asp?order=conceptid&formname=search&screen=0&lib=h01&v0_0=&v1_0=conceptid%2Cpreflabel%2Caltlabel%2Cdefinition%2Cmodified&v2_0=0&v0_1=&v1_1=conceptid&v2_1=3&v0_2=&v1_2=preflabel&v2_2=3&v0_3=&v1_3=altlabel&v2_3=3&v0_4=&v1_4=modified&v2_4=9&v0_5=&v1_5=modified&v2_5=10&x=56&y=26&v1_6=&v2_6=&v1_7=&v2_7=

**Comment by evabrna** [comment]
consider versioning in EDMOnet H01 list
