### ISSUE TITLE
IC and RECO: small changes to synchronize both

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#417]
In preparation for the new RECO publication, Kadji has run a consistency report between codes in InterCatch and in RECO. There are a few changes to be done in RECO to have the two copies in sync:
- IC_DepthRange: Deprecate all existing codes, add -9 [//vocab.ices.dk/?ref=258](https://vocab.ices.dk/?ref=258)
- IC_Stock, deprecate AllStocks [//vocab.ices.dk/?ref=260](https://vocab.ices.dk/?ref=260)
- IC_unitCANUM, deprecate n, add N [//vocab.ices.dk/?ref=270](https://vocab.ices.dk/?ref=270)
- Deprecate IC_Gear and IC_LSDataType [//vocab.ices.dk/?ref=317](https://vocab.ices.dk/?ref=317) [//vocab.ices.dk/?ref=295](https://vocab.ices.dk/?ref=295)

**Comment by evabrna** [comment]
capitalize n no need to deprecate
Allstocks already deprecated
the rest is ok to deprecate
