### ISSUE TITLE
ENV2023-02-20 New ICCOD codes for some proficiency tests

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#418]
DRRR 2017          RVEP 170197 Bestimmung des Gehalts an Phthalaten in Bedarfsgegenständen (doc not ok)
QT-0032357        Sigma Aldrich Proficiency Testing SPE009-50G Chlorinated Pesticides in Soil, LRAC7398 (doc not ok)
LUERV-A-2021-SSO         Länderübergreifender Ringversuch LÜRV A from 2021 - organics in sewage sludge (doc not ok)
LUERV-2021-SOIL            Länderübergreifender Ringversuch LÜRV A from 2021 - inorganics in soil (doc ok)
UKWIR-4-21       Proficiency Tests UKWIR 1/21 to 4/21 priority substances in surface water (doc ok)

**Comment by Osanna123** [comment]
LUERV-A-2021-SSO doc ok
DRRR 2017 RVEP 170197 doc ok - determination of the content of phthalates in consumer goods

**Comment by cekv** [comment]
No go for the code without documentation.

**Comment by Osanna123** [comment]
QT-0032357 is a quick-turn proficiency testing, which does not require more than 1 participant. So there is no other report than we already received I'll check with our experts if it makes sense to have them in ICCOD.

**Comment by Osanna123** [comment]
DRRR-2017-RVEP-170197
LUERV-A-2021-SSO
LUERV-2021-SOIL
UKWIR-1-4-21
