### ISSUE TITLE
RDBES: New codetype 'PositionDataIndicator' with 9 codes 'VMS', 'AIS', ect.

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#419]
Hi Adriana
Can you create the following new:
Codetype                         Description
'PositionDataIndicator'    Indicate which type of position data there is collected and available

Code		Description
‘VMS’ 		VMS data only are collected and available
‘AIS’		        AIS data only are collected and available
‘VMSAIS’	        VMS and AIS data only are collected and available
‘Other’	        Only other position data are collected and available, like iVMS In-shore VMS or BlackBox
‘VMSOther’ 	VMS and other position data (not AIS) only are collected and available
‘AISOther’	AIS and other position data (not VMS) only are collected and available
‘VMSAISOther’ VMS and AIS and other position data are collected and available
‘Unknown’ 	Unknown
‘No’	                No position data available

Cheers Kjems

**Comment by evabrna** [comment]
review available vocabs for vessel tracking systems and check with RDBES whether they could use such a vocab or they NEED only flagging @odontaster

**Comment by HenrikK-N** [comment]
The Core Group need to discuss the codes further, so I am setting this issue on hold for now.

**Comment by HenrikK-N** [comment]
The codetype is not needed.
