### ISSUE TITLE
Common vocabs not filtered by theme / dataset --> Data Quality issue 

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#42]
Currently common vocabularies like Gear, SHIPS, SpecWoRMS etc. isn't selective for the different datasets using them partial even when filtering by theme on the web.

This potential leads to data quality loss as the users can select whatever they want and there is no way to control this which as such is a serious issue!

On behalf of acoustic:

- One solution could be to filter the vocabs for codes of acoustic relevants (ask the data collecters / submitters possible though the acoustic governance group) and make sure the acoustic validation rule follow these relationships setup.
- Another solution could be to setup specific acoustic vocabs (which partial currently is the case) for thematic vocabs and then make relationships between codes of datasets specific vocabs if needed for some reason.

**Comment by neil-ices-dk** [comment]
This is a good long term issue; we will have challenges as this is for some datasets handled in DATSU, for some handled at the database level; so we will need to agree the common way to approach this across the systems. Probably going to take a few discussions across the Data Centre

**Comment by HjalteParner** [comment]
I think the common ground here is RECO and as such it should be enforced in RECO and as such also shown to the users in the RECO interface so they are award of the relationship

**Comment by neil-ices-dk** [comment]
> 
> 
> I think the common ground here is RECO and as such it should be enforced in RECO and as such also shown to the users in the RECO interface so they are award of the relationship

i think you're right, that is our common outward facing interface/service. We will have something on the agenda for the next DC meeting to start warming people up

**Comment by cekv** [comment]
@mehdiabbasi and @mikeydrew provide the criteria to filtering at the themes level on the vocab page.
This seems to be no longer up to date.

**Comment by mehdiabbasi** [comment]
@cekv 
For each theme, there is a procedure that retrieves all code types that used in the theme. EX. for Acoustic procedure is looking on Acoustic database and retrieve a list of code types that used in Acoustic DB.

**Comment by Osanna123** [comment]
@mehdiabbasi , do you have an overview of these procedures? Are they managed centrally, or separately by respective project teams?

**Comment by mehdiabbasi** [comment]
@Osanna123 There are in RECO_Publish db and I manage them

**Comment by pcrjoana** [comment]
To bring up in next DC meeting - individual teams should check if their themes are up to date. :-)

**Comment by neil-ices-dk** [comment]
@Osanna123 to invite Mehdi to next vocab meeting to discuss using the data.ices. themes

**Comment by HenrikK-N** [comment]
@mehdiabbasi For the theme "InterCatch" (the fish box) the following code lists should be removed: AGDET, Class, ICCOD and SpecClass 
I would like to know the procedure that retrives all the InterCatch codes, can you forward that to me?

**Comment by Osanna123** [comment]
For discussion at the DC meeting: 
Suggestion to use DP_Theme, and to link all related CodeTypes AND Codes to each theme.
Display in web-Vocab would need to show that the subset is filtered by what codes are possible to use within the theme.

**Comment by mehdiabbasi** [comment]
List of Themes in DP_Theme:

Acoustic trawl surveys
Biological communities
Contaminants and biological effects
Fish trawl surveys
Ichtyoplantkon surveys
Underwater noise
Ocean hydrochemistry
Commercial catches
Stock assessments
Stomach content
Vulnerable marine ecosystems

**Comment by neil-ices-dk** [comment]
agreement by DC team; @mehdiabbasi to formulate a process flow for review;

**Comment by HenrikK-N** [comment]
The RDBES and InterCatch are working in parallel and both have data calls, and they both contain data for commercial fisheries. Both systems are also using the Vocabulary, therefore it is relevant for the ICES community and data submitters to be able to see both the RDBES and the InterCatch code lists, when finding the right codes for the data submissions of the data calls.

**Comment by neil-ices-dk** [comment]
@HenrikK-N this is possible when using the theme 'Commercial catch' (it would return all InterCatch, RDB and RDBES codes), i don't think you have described the user story correctly?

**Comment by HenrikK-N** [comment]
Okay, but it would be better if only the code lists relevant for the system, which the user is trying to submit data for is shown. So if the user want to see code lists for the RDBES, then only code lists for the RDBES is shown, and the same for code lists for InterCatch.

**Comment by neil-ices-dk** [comment]
@sjurl can we have a short discussion slot at the DIG meeting on this, we can prepare a short presentation and the idea is we want to get the view of the user, rather than our internal viewpoint:

Issue: the use of 'theme filter' in the vocab.ices.dk and whether this needs to be at the theme level i.e. commercial catch as proposed, or at a level down at 'dataset'; the view was that specific vocabs for datasets are dealt with in data calls, data portal pages and formats, and the vocab.ices.dk would provide more of an overview of types based on theme to the more casual observer that doesn't necessarily know the ICES dataset/data portals

**Comment by sjurl** [comment]
@neil-ices-dk It's allways good to get external input on things like this so I think it's a good topic for DIG. Could you add it to the initial plan we have made for the DIG agenda?

**Comment by neil-ices-dk** [comment]
for DIG on 18th May [presentation](http://community.ices.dk/Committees/DIG/DIG%202021/05.%20Presentations/Filtering-DIG-May18-2021.pptx)

**Comment by neil-ices-dk** [comment]
feedback being sought on DIG action #95

**Comment by Osanna123** [comment]
@neil-ices-dk to set up a survey :)

**Comment by neil-ices-dk** [comment]
survey sent out 9th July

> Dear all,

> I do have a request for all of you that I hope you are able to do over summer. During this year’s DIG meeting we discussed and agreed that we would have a questionnaire for people in our organizations that uses the ICES Vocab Web Interface. The ICES Data Centre have now compiled the questions into an online form that I hope you can share among your colleagues are responsible for delivering data to ICES or that you know uses the ICES Vocab Web Interface.

> The questionnaire is available at  [https://forms.office.com/r/6KC81fycRP](https://forms.office.com/r/6KC81fycRP)

> Sjur Ringheim Lid
Head of Digital Development
