### ISSUE TITLE
Fecundity & Atresia new vocab for SamplingApproach

### ISSUE THREAD

**Issue by evabrna** [ices-eg/DIG#422]
After a meeting with Anna and Cindy, we discussed if we might need new vocab for Sampling approach.

Refers to if a fecundity sample is taken randomly or directed sampling
R= Random sampling from a subsample of the catch
D= Directed sampling from the remainder of the catch"

**Comment by evabrna** [comment]
suggest to Cindy if these make sense https://vocab.ices.dk/?ref=1511 and can be used
Ask Kjems about interpretation

**Comment by evabrna** [comment]
https://vocab.ices.dk/?ref=1603 this link not the one above

**Comment by evabrna** [comment]
After a discussion with Kjems, it does not seem that Clustering codetype would work https://vocab.ices.dk/?ref=1603

**Comment by evabrna** [comment]
ask Hjalte and @odontaster what is the use of https://vocab.ices.dk/?ref=1483 in acoustic surveys
we could possibly add them in this codetype as flags

another option is to add them in selection method https://vocab.ices.dk/?ref=1637

**Comment by Osanna123** [comment]
Let's use https://vocab.ices.dk/?ref=1637 
Check with @odontaster to be on the safe side

**Comment by pcrjoana** [comment]
Codes added to https://vocab.ices.dk/?ref=1637
