### ISSUE TITLE
TAF new codeTypes request

### ISSUE THREAD

**Issue by colinpmillar** [ices-eg/DIG#426]
For the TAF DB we need several new vocabulary CodeTypes

### RunType (or TAFRunType). 

This is similar to Purpose as used in SAG so could be an extension of this.
http://vocab.ices.dk/?ref=1516

I would need Codes:
* Exploratory => reuse Unnoficial
* Draft => reuse InitAdvice
* Final => Advice

conclusion -> not required for now

### AnalysisType (or TAFAnalysisType)

Codes:
* StockAssessment  - description: analysis used in stock assessment
* AcousticIndex - description: analysis used in calculation of acoustic index
* RDBES - description: analysis used to estimate raised national and total catches for the RDBES

#### RunObjectType (or TAFRunObjectType)

Codes:
* FLStock - FLStock data object
* SAGUpload - SAG upload file in XML format

**Comment by odontaster** [comment]
The code types can have TAF as prefix, as they are very project specific. They should be invisible.
