### ISSUE TITLE
Review RDBES unknown codetypes

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#43]
RDBES codetypes raising concern:

Isn't this a dataset? CodeType RDBES: https://vocab.ices.dk/?ref=1597
Information is ambiguous: RS_UpperHierarchy https://vocab.ices.dk/?ref=1627

Visible CodeTypes without an individual link and 0 codes (are these services?):
RDBES_CT_DataDownloadCountry
RDBES_CT_DataUploadCountry 
RDBES_CT_RecoSyncServiceAccess 
RDBES_CV_PageAccess
RDBES_CV_RecoSyncServiceAccess

**Comment by Osanna123** [comment]
- [ ] RDBES (1597) to be deleted, and new codes to be created in Datasets and DatasetVer
- [ ] RS_UpperHierarchy is ok, might need a 'hierarchy' in the description
- [ ] To be reviewed by the RDBES team:
RDBES_CT_DataDownloadCountry
RDBES_CT_DataUploadCountry
RDBES_CT_RecoSyncServiceAccess
RDBES_CV_PageAccess
RDBES_CV_RecoSyncServiceAccess

**Comment by Osanna123** [comment]
@HenrikK-N and @cekv , could you please provide an update on progress of this issue?

**Comment by HenrikK-N** [comment]
@EjazAtIces: You are working on this task, could you give an update?

**Comment by EjazAtIces** [comment]
We should delete all these code types (RDBES_CT_DataDownloadCountry,RDBES_CT_DataUploadCountry,RDBES_CT_RecoSyncServiceAccess,RDBES_CV_PageAccess,RDBES_CV_RecoSyncServiceAccess).

We need only one code list with the following code type and and codes. All should be invisible.

CodeType | Description
RS_ClaimTypes | For managing claims for authorizations in RBDES application

Code | Description
AdminAccess | Claim required to access administration resources
DataUploadCountry | Claim required for data upload
RecoSyncServiceAccess | Claim required to access RBDES web service for sync calls
DataDeleteCountry | Claim required for data delete
DataDownloadCountry | Claim required for data download

@HenrikK-N , @cekv , @Osanna123 , @Kadji . Cecilie let me know once you ready to delete these. I need to deploy RDBES with new changes.

**Comment by Osanna123** [comment]
@EjazAtIces, we suggest dropping the prefix RS_, as it will be used by other thematic portals.
As for the codes, we have no objections, but recommend checking with other DC developers/projects,
