### ISSUE TITLE
Add code to vocab NationalFishingActivity

### ISSUE THREAD

**Issue by josefineegekvist** [ices-eg/DIG#430]
Could you add the code LHP_LPF_0_0_0_SWO to the http://vocab.ices.dk/?ref=1614 NationalFishingActivity? with the description:

Hand and pole lines (hand-operated), Large pelagic fish, see the code reg. mesh size and selectivity device - main species targeted: Swordfish (Xiphias gladius)

**Comment by josefineegekvist** [comment]
Hi,

No, it a level 7 code so it should only be added to http://vocab.ices.dk/?ref=1614. The NationalFishingActivity is also a field in the RDBES.

Thanks.

**Comment by odontaster** [comment]
Done, will be visible on web tomorrow.
