### ISSUE TITLE
ENV2023-02-28 new PARAMs for NL

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#431]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/anna/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/anna/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

PARAM | PARname | CASnr | CASname
-- | -- | -- | --
  |   | 70887-84-2 | 3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,10-Hexadecafluorodec-2-enoic   acid
  |   | 919005-14-4 | 2,2,3-Trifluoro-3-(1,1,2,2,3,3-hexafluoro-3-(trifluoromethoxy)propoxy)propanoic   acid
  |   | 68259-12-1 | Perfluorononanesulfonic   acid
n-PFBSA | Perfluorobutanesulfonic   acid - linear form | IS | isomer
n-PFHpS | Perfluoroheptanesulfonic   acid - linear form | IS | isomer
sbr-PFHxS | Perfluorohexanesulfonic   acid - sum branched form | IS | isomer
sbr-PFOS | Perfluorooctanyl   sulphonic acid - sum branched form | IS | isomer

</body>

</html>

**Comment by Osanna123** [comment]
added 5 first codes, but two last should be covered by the respective br-codes

**Comment by Osanna123** [comment]
regarding the last 2 codes, we have 10 codes referring to branched and linear forms. Can we improve the description to specify that they relate to the sum of branched/linear isoforms? (this would fit with the original request in 2018, and requirements by the Dutch requester. 
![image](https://user-images.githubusercontent.com/17157764/231729291-892bfb3e-90fa-4280-b870-c644e120fe6b.png)

**Comment by pcrjoana** [comment]
@Osanna123 to improve the descriptions.
