### ISSUE TITLE
ENV old formats/vocabs flagging

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#432]
DatasetVer ENV formats 2.2 and 3.1 are no longer accepted in DOME, so perhaps, the codes should be deprecated?
Also some of the related vocabs, like BDMET are no longer in use and might have misleading concepts, so the suggestion is to review and perhaps make invisible or deprecate old codes

**Comment by Osanna123** [comment]
BDMET - if it is needed for other projects, at least deprecate the old codes, more relevant for SMTYP
STTYP
VESSL- is it used by any other projects?
PHOTO
SMPRE
SORPC
SRCWT
SREFW
AGTYP

AMAAR - invisible
AMREC - invisible
BECOA - invisible
COSED - invisible
GEART - invisible
HELAR - invisible
SFRAC - invisible
SSTYP - invisible
STRAT - invisible
INORB - invisible
JMPAR - invisible
OELWA -  invisible
ORGNZ - invisible
PTSRC - invisible
SEORB - invisioble
TISSU - invisible

**Comment by pcrjoana** [comment]
All data managers to look into the codetypes to make sure they're not used in their data flows. Unused codetypes from the list can be deprecated.

Review by 25/04/2023.

**Comment by odontaster** [comment]
Checked and ok to deprecate and make invisible.
