### ISSUE TITLE
Chat on display of Themes/datasets in new webRECO http://ices256:81/reco/

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#439]
http://ices256:81/reco/

**Comment by cekv** [comment]
remove ICES from the VME description
add acronyms to the description, and remove dataset codes from the display.
review the codes mapped to BDFTS

**Comment by odontaster** [comment]
ask Mehdi to remove dataset codes from the display.
Pending discussion on the codes mapped to BDFTS with @Osanna123

**Comment by mehdiabbasi** [comment]
Done. Code removed from the list
