### ISSUE TITLE
Review RDBES: visibility of certain codetypes

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#44]
Should be visible?
https://vocab.ices.dk/?ref=1654

**Comment by Osanna123** [comment]
for the RDBES team to discuss, if it should stay in RECO.
If it stays, consider  generalizing the label, and making it invisible

**Comment by Osanna123** [comment]
@HenrikK-N, could you please provide an update for this issue?

**Comment by HenrikK-N** [comment]
Codes: Admin, Download, Upload
@EjazAtIces: could you give an update?

**Comment by EjazAtIces** [comment]
We should delete these codes and code type RDBES_CT_PageAccess.
 @HenrikK-N , @cekv please let me know once you are ready to delete so I can deploy RDBES
