### ISSUE TITLE
ENV2023-04-21 new STAGE codes request for zooplankton

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#442]
I need some additional codes in STAGE for reporting zooplankton data. In the table below I’ve made some proposals for the codes. But these are just proposals.

LV-AC	Larvae - actinotrocha
LV-BR	Larvae - brachiolaria
LV-CY	Larvae - cyphonautes
LV-CP	Larvae - cypris
LV-MI	Larvae - mitraria
LV-NA	Larvae - nauplius
LV-NE	Larvae - nectochaeta
LV-PI	Larvae - pilidium
LV-PL	Larvae - pluteus
LV-VE	Larvae - veliger
LV-ZO	Larvae - zoea

**Comment by cekv** [comment]
@Osanna123 to send the request to HELCOM ZEN for consultation

**Comment by cekv** [comment]
Found this page for reference:
https://www.marinespecies.org/traits/wiki/Traits:Zoea

Only pitfall is that it does not have any reference material for 3 of the larval stages (actinotrocha, brachiolaria and pluteus)
bottom line - there is reference material for all of them, some need a bit of help from Google to find the original source material.

**Comment by Osanna123** [comment]
![image](https://github.com/ices-eg/DIG/assets/17157764/9d365266-24ad-44e4-a27e-3c032a2f371b)
