### ISSUE TITLE
ESAS Species

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/DIG#448]
ESAS, should the ESAS species be added to SpeciesWORMS vocab?

**Comment by odontaster** [comment]
@Osanna123 to check if all ESAS species are in WoRMs, and add them to SpecWoRMS.
https://esas-docs.ices.dk/species/

**Comment by pcrjoana** [comment]
- [ ] Create new CodeType for the ESAS list
- [ ] Add ESAS aphia IDs to SpecWorms
- [ ] Semantically map the ESAS list to SpecWorms
- [ ] Reflect SpecWorm based search in disclaimer

**Comment by Osanna123** [comment]
Added ESAS aphia IDs to SpecWorms, however, these are not accepted and not added thus far:
137100 junior objective synonym of 1571853 (status changed in 2022)
137147 unaccepted, ref 1584284 (2022)
148764 unaccepted family, ref 136988 
1534756 unaccepted, ref. 1534755
1534769 unaccepted, ref. 1534773
1534806 unaccepted, ref. 1534805
1534834 unaccepted subspecies, ref. species 1037315

**Comment by Osanna123** [comment]
present unaccepted:
137178
1534834
1484453

**Comment by Osanna123** [comment]
@cmspinto the respective WoRMS codes are in the SpecWoRMS.
Could you please make sure to replace the ESAS disclaimer?
the latest version is here: https://github.com/ices-tools-prod/disclaimers

**Comment by cmspinto** [comment]
Hi @LApetre, I can't load the ESAS project because of the local references, could you update the disclamer like Anna suggests?

**Comment by LApetre** [comment]
The disclaimer is updated now. @Osanna123
