### ISSUE TITLE
Oceanography data submission format and revised procedure

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#449]
With effect from July 2021 ICES Oceanography data submission format was change from free format to a standard format based on the ODV spreadsheet format i.e. https://www.ices.dk/data/data-portals/Pages/ocean-format.aspx

As part of the funding provided by the Baltic Data Flow project, we have for the past two years after the release of the new format, focused on upgrading the oceanographic data submission procedures and database, enabling automatic ingestion of the new data format, quality control including the production of an intuitive and informative data submission validation report.

**Data format**
- Based on the Ocean Data View (ODV) generic spreadsheet format with the use the SeaDataNet (SDN) semantic header to map parameter units into the NERC P01 parameter and P06 unit vocabularies.
- ICES ODV format differs from the SDN ODV format in that some mandatory metadata i.e. ICES Platform code and EDMO distributor and custodian code are required within the format itself and that submitters own quality flag schemes are allowed.

**Data format checks**
- Semantic header describing the mapping from column header to the NERC P01 parameter and P06 unit vocabularies.
- Column header to semantic header, mandatory and optional fields. 
- Data records metadata uniqueness, relationships and vocabulary validation i.e. cruise, station and platform ICES code, distributor, custodian and originators EDMO code and project EDMERP code.

**Data existing checks**
- Check for existing or overlapping data in oceanographic database.
- Check for existing or overlapping data in external CSR database hosted by SeaDataNet (IFREMER) i.e. https://csr.seadatanet.org.

**Quality control checks** - taking submitters quality control flags into consideration 
- Station checks
  - Impossible Datetime
  - Impossible Location
  - Position on Land using EMODnet Bathymetric or else GEBCO
  - Impossible Speed
  - Impossible Sounding
  - Deep Shelf Station
- Sample checks
  - Impossible Parameter Global Range Values
  - Decreasing Depth/Pressure
  - Density Inversion
  - Impossible Oxygen Saturation
- Visual Inspection
  - Station map
  - _Profile plot planned for ..._

**Next**
- Enable upload in production currently (deliberately) in test.
- Improve data format documentation
- Focus on further development of the quality control procedures to give submitters an better second opinion of their data and as such help submitters improving the data quality even further of data going into the oceanographic database.
- ERF 3.2 format is strongly considered to be deprecated for oceanographic data submissions as the mapping between the ERF format to the oceanographic format and quality control isn't one-to-one, and the current number of users wanting to submit oceanographic data using the ERF 3.2 format is very limited, if existing at all. 

**Issues still to be solved / decided on**
- Integrated samples
- Device category codes vs Datasets

**API** - https://ocean.ices.dk/odb/api
- Submit (email, callbackurl and file) --> guid
- Validate (guid) --> ValidationReport
- Upload (guid) --> UploadReport

**UI** - https://ocean.ices.dk/odb/submissions/submit (live demonstration planned in session)

**Comment by HjalteParner** [comment]
Validation reports examples:

https://ocean.ices.dk/odb/submissions/validationReport/909abce3-a75f-46d8-9c6a-24a7a80610c5

https://ocean.ices.dk/odb/submissions/validationReport/4fc5ad9c-7902-43bc-a78b-d2d4798ac66e

https://ocean.ices.dk/odb/submissions/validationReport/d98ebc65-8fe5-4a63-a697-5fff0fb5d427

**Comment by sjurl** [comment]
Closed for now, open new task for next update
