### ISSUE TITLE
Review RDBES duplicated codetypes

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#45]
TargetSpecies https://vocab.ices.dk/?ref=1661, copy of Metier-5
GearType  //vocab.ices.dk/?ref=1653 (see description!), copy of Metier-4
RS_VesselType https://vocab.ices.dk/?ref=1631 (???), we can suggest PlatformClass
RS_Sex https://vocab.ices.dk/?ref=1636 - it is in WGBIOP's jurisdiction to suggest a single universal ref. list for fisheries (right now, we have 4 project-specific codetypes with essentially same info (RS, IC, TS, AC)  
RS_CatchCategory https://vocab.ices.dk/?ref=1610 (see descriptions!) is essentially a replicate of an IC_ CodeType. Could a more generic CodeType be in use?
RS_CatchFraction https://vocab.ices.dk/?ref=1611 is a subset of RS_CatchCategory
RS_CatchRegistration https://vocab.ices.dk/?ref=1604 is conceptually close to these 2 as well

**Comment by cekv** [comment]
All vocab with mostly the same measurement units, should be probable to find one to fit them all:
 //vocab.ices.dk/?ref=1663
 //vocab.ices.dk/?ref=1608
//vocab.ices.dk/?ref=1625

And this //vocab.ices.dk/?ref=1622 is a copy of this //vocab.ices.dk/?CodeID=197374
This //vocab.ices.dk/?ref=1628 could be part of METOA, since the parameters already exist there?

This  //vocab.ices.dk/?ref=1602 same as  //vocab.ices.dk/?ref=1474

**Comment by Osanna123** [comment]
Metier-5 is confused with the fishing activity codes, so the label for Metier-5 is to be revised, 1661 to be deleted
Metier-5 is used in VMS and BYC
more info:
https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2008:346:0037:0088:EN:PDF#page=16

**Comment by Osanna123** [comment]
For RS_VesselType, suggestion is to have a subset of https://vocab.ices.dk/?ref=311, and delete 1631

**Comment by Osanna123** [comment]
RS_Sex needs better descriptions, make the label generic

**Comment by Osanna123** [comment]
RS_CatchCategory make the label generic, improve the descriptions

**Comment by Osanna123** [comment]
RS_AccuracyCode and RS_AddGrpMeasurementType to be looked at by the CoreGroup and possibly merged with the RS_ValueType

**Comment by Osanna123** [comment]
RS_UnitScaleList to be deleted, generic is to be used instead (most likely https://vocab.ices.dk/?CodeID=197374)
(see if one scale would be enough - other projects need both MaturityScale and MaturityStage)

**Comment by Osanna123** [comment]
RS_ObservationType need better definitions, consider making the codetype generic

**Comment by Osanna123** [comment]
RS_FishingValidity make into a generic CodeType ValidityFlag, encourage other projects to use

**Comment by Osanna123** [comment]
@HenrikK-N, could you please provide an update for this issue?
@cmspinto @pcrjoana could you please provide info on the comment with Metier-5 and Metier-4?

**Comment by Osanna123** [comment]
@davidcurrie2001 @cekv @HenrikK-N please put for review by the RDBES core group

**Comment by pcrjoana** [comment]
@cekv to include this ticket in her email to @davidcurrie2001 and @HenrikK-N

**Comment by HenrikK-N** [comment]
After the meeting with the refernce group Anna etc and Neil, it was agreed to use TargetSpecies https://vocab.ices.dk/?ref=1661 or rename 'Metier-5' to 'TargetSpecies'.  'Metier-5' contain the targetSpecies or target assemblage. The term metier is use for the combination of several fields.

**Comment by Osanna123** [comment]
We invite @cmspinto and @HenrikK-N to the next RMG meeting to review this issue

**Comment by cmspinto** [comment]
I'm looking forward :)

**Comment by Osanna123** [comment]
@odontaster please review this monster when you have time
