### ISSUE TITLE
Create fora and invite Governance groups and governance bodies to DIG 2024 meeting.

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#461]

**Comment by davidcurrie2001** [comment]
Invitation email sent this morning to chairs of WGACOUSTICGOV, WGDG, WGJCDP, WGRDBESGOV, WGSFDGOV, WGSMART, and WGTAFGOV.  Text is included below for information:

"Hi all,

I’m writing as you are chairs of a data governance group.  Data governance groups have been a great success story in improving how we manage ICES data and we’re planning to have a session dedicated to them at the upcoming Data and Information Group (DIG) meeting.  This session will take place online on Tuesday 21st May, from 10:00 CEST – 12:30 CEST and it would be great if you can participate.  

The aims of the session are to encourage communication between governance groups, and to identify any areas where DIG and the governance groups can help each other.  The plan is to split the session into two parts.  During the first part we’ll give the floor to each of the governance groups and ask you to make a short presentation (~10 mins, requested format below), then in the second part we’ll have an open discussion where we can pick up on common topics and themes.

Please could you let me know whether you are able to attend this session.  If you have any questions please let me know.

Best wishes,
Dave
On behalf of the Data & Information Group


Requested format for presentation:
•	Brief summary of the group membership and how it is run (max 1 slide)
•	Your group’s main achievements in the last year
•	Any problems encountered in the last year (along with solutions, if relevant)
•	Your group’s plans for the next 12 months – highlighting any challenges you foresee"

**Comment by davidcurrie2001** [comment]
The chairs of WGACOUSTICGOV, WGDG, WGRDBESGOV, WGSFDGOV, WGSMART, and WGTAFGOV have accepted.  The chair of WGJCDP can't make it but is looking for an alternate from that group.

**Comment by davidcurrie2001** [comment]
We also have a representative from WGJCDP  - so a full house :-)
