### ISSUE TITLE
WKEnsure & WKDSG review of update Best practices Handbook

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#467]
To be performed after #13

**Comment by sjurl** [comment]
Followup workshop from WKENSURE october 2023 WKAFPA

**Comment by Ingeborg1312** [comment]
The following recommendations were listed as 'related to the Best practices document' (hereafter BPD), see https://community.ices.dk/Committees/DIG/Master%20documents/Best%20practices%20document/Recommendations_WKEnsure_WKDSG.xlsx?web=1:
WKEnsure 2023-35: not incorporated as the BPD focusses on the data contributors and not on the users
WKDGS 2021-30: version 2 of the BPD provides more information on standards, and communication channels.
