### ISSUE TITLE
Controlled list for overall categorization of pubs and data

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#468]
Hi all,

Following up on the discussion at DIG on the DPT categorisation, which needs to be better aligned in ICES, and we can use the vocab.ices.dk for this.

### Background
Regarding the vocab of categorisations used in the DPT, which is focussed on biological information and came from the list used in the library. I spoke with Ruth from publications, and we have a narrow window to update this list as they are migrating the backend system. 

The categorisation generically used by Figshare is based on the Australian National Statistics list (2020); having had a quick browse the good news is that there are terms that cover the ICES work, but to be understandable it has to be picked from table 3 (Division, Group, Field) level, which has 2 000 terms - so would take a bit of effort; this would work for the use case here but not for publications as they have the choice of all or nothing i believe. 
https://www.abs.gov.au/statistics/classifications/australian-and-new-zealand-standard-research-classification-anzsrc/2020

Of course, we have no basis for using an Australian list, and there is an equivalent European list that has a full taxonomy
https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://data.europa.eu/8mn/euroscivoc/40c0f173-baa3-48a3-9fe6-d6e8fb366a00 

So the approach i will discuss with Ruth and Ffion is to use this as the master list but only import a subset for our use, which we can then manage in the normal way through the RMG. This would then be the list used by Pubs, DPT and other applications as we move forward (leaving out the dataset themese discussion for the time being). 

Will discuss in next meeting

**Comment by odontaster** [comment]
Hi @neil-ices-dk, it sounds good to me, you want to use the second list, right?. The australian list seems to give a finer detail at least in the fisheries sciences categories than the european list, but it might be enough for the scope.

**Comment by neil-ices-dk** [comment]
> Hi @neil-ices-dk, it sounds good to me, you want to use the second list, right?. The australian list seems to give a finer detail at least in the fisheries sciences categories than the european list, but it might be enough for the scope.

thanks @odontaster yes the idea was to use the European list as it would be odd to use a list from outside of the ICES area; pubs are keen to keep the detail out, which i agree is the aim as long as the terms are understandable when they stand alone. Meeting with Ruth and Ffion at **9am tomorrow morning** - if anyone wants to join then i can forward the invite

**Comment by neil-ices-dk** [comment]
ok it turns out that the list that came from pubs for DPT was a draft that was not approved by SIPG (1st image), and they ultimately went with the broad categorisation based on steering group titles (2nd image) which is already a separate question in the Data Profiling Tool;

![image](https://github.com/ices-eg/DIG/assets/23527005/50bddf6f-c398-4310-8095-e934b9354630)

![image](https://github.com/ices-eg/DIG/assets/23527005/acbfb0b2-cba3-44b2-a5d5-4acc683508f0)

### Conclusion and next steps
- I will make a draft of the terms from the EUScienceVocab and make a preliminary mapping to the broad steering group categorisation
- Ruth/Ffion will check if they have all areas covered and consider additions to their categorization on figshare based on this
- RMG will review the draft and the semantic mapping, make additions and changes
- Publish new CodeType (subset of EUSCIVOC terms), and include links to existing CodeType 'Committees' https://vocab.ices.dk/?codetypeguid=cb2e607b-dcf8-4fad-8e7e-987ca3681913

**Comment by neil-ices-dk** [comment]
@RuthAnders i had a closer look into the EU science vocab and it gets fiddly - terms are understandably at different levels but the issue is some of the important terms are listed as **UF** which might mean undefined? or something, so it is a bit tricky to use and we might end up pulling our hair out. So will abandon the exercise

selected terms in the [spreadsheet](https://icesit.sharepoint.com/:x:/r/sites/icesintranet/datacentre/_layouts/15/Doc.aspx?sourcedoc=%7B30a1eb0d-2da0-4dbc-9e24-97b1e7fa5a78%7D&action=edit&wdenableroaming=1&wdorigin=Other&wdredirectionreason=Force_SingleStepBoot&wdinitialsession=ffb85c8c-2e13-4d2f-91d0-72477b792e5a&wdrldsc=2&wdrldc=1&wdrldr=ContinueInExcel&cid=e21357a9-3e6b-4f1c-ad47-849683a4a03f)
