### ISSUE TITLE
Time sensitive! C-square code to be added to "GeometryType", so it can be used in Impulsive Underwater Noise

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#47]
The form can be found at https://forms.office.com/Pages/DesignPage.aspx#Analysis=true&FormId=ziCy4DVXaESR3wXK5f8f3BWA1fNSx4tPsQVXsp2REGRUQkZWSTBTVVZDVVVSWUxMNVBXSkUxSk1NWCQlQCN0PWcu&Token=96ff5a3d226c4a92a1a2159cb052a615&TopView=SurveyResults
(Respondent 10)

**Comment by Osanna123** [comment]
It is a good idea to add C-squares to the existing codetype GeometryType. I support the suggestion.
However, C-squares should not become an ICES vocabulary.

**Comment by neil-ices-dk** [comment]
i think it is necessary, just one related question; how does one denote the resolution of the c-square when reporting the data i.e. C-squares can be at any scale and can this be handled in the geometry like for polygons or lines?

**Comment by Osanna123** [comment]
C-square would need a label to define the specific resolution in use

**Comment by pcrjoana** [comment]
To reflect the size of the C-Square, and to leave room for adding more C-Square sizes to GeometryType in the future, the code C-Square_0.05 was added to GeometryType.
