### ISSUE TITLE
ISO 3166 code labels

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#474]
Can we take a review of these, it seems we have a mix of capitalized name labels which is not consistent internally or as they are described externally:
our labels https://vocab.ices.dk/?codetypeguid=6d4239d2-b9b2-43c2-a9d4-0ddcd5dd640c 
external label example https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#DK

**Comment by neil-ices-dk** [comment]
We should standardise on Sentence case but we cannot make this change until we move from DAD to AIMS as it is difficult to identify which code list the country originates from in the DAD interface

**Comment by MariaMakri** [comment]
@odontaster to ask Mehdi to change the descriptions.

**Comment by odontaster** [comment]
-Bulk edit Descriptions and/or Long descriptions
-For security the procedure should ask for Code, Old description, New description (or Long description)
-If only editing one of the two fields (description or long description), the fields of the other will be empty, and that will mean no action.
-In case of wanting to make all fields empty, we should add some character, but that seems very improbable.

**Comment by MariaMakri** [comment]
Description can never be empty, in case of wanting to delete all long description, insert NA.

**Comment by Osanna123** [comment]
@mehdiabbasi implementation timeline - by the end of this year.
RMG needs to be able to bulk edit all code-related edit options in bulk: Description, Long description, Visibility, Deprecated.
-For security, the procedure should ask for Code, old attribute value, new value.
-In case of wanting to make all fields empty, we should add some character, but that seems very improbable.

**Comment by mehdiabbasi** [comment]
Hi All,

I added a new form for bulk edit. Please test it from the test folder here \\fs\projects\DP1\projects\RECO\RECO Management System\ForTest\RECO Management System.exe

 and the test database is on SQl2022dev

![image](https://github.com/user-attachments/assets/8f3a8e64-3b3b-4580-9955-bef73e1f59ce)

**Comment by odontaster** [comment]
Would call it "Edit code attributes" instead of "Edit Code(s)"
I think we can remove "in ICES Vocabulary" and "to the ICES Vocabulary" in all the titles of the Bulk Operations 

Tested with ISO_3166, changed cases, changed visibility and deprecation flags.
Bug in Long description, from empty to something does not work.

**Comment by mehdiabbasi** [comment]
@odontaster I edited titles. if put 'NA' in the old long description, then you can add new long description. please test it again

**Comment by odontaster** [comment]
Looking good @mehdiabbasi, it can go to production thanks

**Comment by mehdiabbasi** [comment]
Thanks @odontaster for the test. It is on the production

**Comment by odontaster** [comment]
ISO_3166 descriptions have been reviewed. 
Som eparticles like and and of remain lower case. Please let me know if you find any other exceptions to the Sentence case.
Thanks

**Comment by MariaMakri** [comment]
Thank you @odontaster :)
