### ISSUE TITLE
Population code for acoustic and possible datras and eggs/larvae

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#478]
https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/48

**Comment by cekv** [comment]
https://github.com/ices-taf/advice-dept/issues/197

**Comment by florianberg** [comment]
Who should we contact when you talk about ACOM LS/Advice/Data C? and, what is a SWOT? We need to upload the data for the HERAS acoustic survey soon and need this new code.

**Comment by cekv** [comment]
The ACOM LS (leadership or vice-chairs) can be found here: https://www.ices.dk/community/groups/Pages/ACOM.aspx
For Advice I think you should get in touch with Lotte Worsøe Clausen, since she is listed as the professional sec for the WK -  and for the Data Centre it should be Adriana/Hjalte - I know Adriana has had her eye on this, and put it forward within the reference management group.
A SWOT stands for Strength, Weakness, Opportunities and Threat analysis

If you have any other questions please contact me or Adriana.

**Comment by neil-ices-dk** [comment]
Now clarifiying the process. WKSIDAC2 should make a **recommendation**, which would then be considered by SCICOM/ACOM as part of the usual process of review of recommendations. This would be the sense check and documentation of a change - exactly how we do it for new stocks/split of stocks.

This would then be taken up by the vocab governance to implement in consultation with WGACOUSTICGOV.

**Comment by odontaster** [comment]
The recommendation ia already there:
https://community.ices.dk/admin/Recomendations/_layouts/15/start.aspx#/Lists/Recommendations%202023/AllItems.aspx#InplviewHash688c456e-54b2-4425-8ea8-3e6862b509c5=FilterField1%3DEG-FilterValue1%3DWKSIDAC2

I had a quick chat with @florianberg during WGIPS and he confirmed that Codes and descriptions will not need to be modified. When a population changes, a new code/description will be requested. The previous codes should be deprecated so they can't be used for upload and some info about history of the population will be stored in the long description of the new codes (and info on the new codes in the old codes long description).
They are happy with the RMG suggestion of ASFIS+3-4random numbers.

@florianberg can you provide better descriptions for the population codes you are requesting? if there was some relevant link to publications or reports that would be good. Thanks
[Herring.baseline.samples (3).xlsx](https://github.com/ices-eg/DIG/files/14168684/Herring.baseline.samples.3.xlsx)

**Comment by florianberg** [comment]
Hei, 
The latest overview of populations were published in the WKSIDAC report and corresponding Excel file:
ICES. 2024. Second Workshop on Stock Identification and Allocation of Catches of Herring to Stocks (WKSIDAC2; outputs from 2023 meeting). ICES Scientific Reports. 6:5. 67 pp. https://doi.org/10.17895/ices.pub.24998747

I can provide a more detailed description if the information from the Excel file attached to the WKSIDAC report is not enough.

**Comment by odontaster** [comment]
[Spatial_distribution_baselines.csv](https://github.com/ices-eg/DIG/files/14176741/Spatial_distribution_baselines.csv)

**Comment by Osanna123** [comment]
@odontaster 
Please check with Lotte on the outcomes of the workshop reg. approval from ACOM.
Create the new codetype and codes as suggested. Add species reference to the descriptions.
Ask Florian if ICES codes could be published in the doc above.

**Comment by odontaster** [comment]
Final list of codes and descriptions, reviewed by WKSIDAC2 chair and agreed also by HAWG

[ICES_vocab_GeneticPopulation_FB_March2024.xlsx](https://github.com/ices-eg/DIG/files/14692757/ICES_vocab_GeneticPopulation_FB_March2024.xlsx)
