### ISSUE TITLE
ENV2023-06-27 new entries for STAGE

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#479]
German requester:
I need additional codes for STAGE again (we are preparing zooplankton data from several years for data import and upload). The first one is:

Larvae – actinula.  Crawling larval stage of some hydoids (Allman, G.J., 1871)

The source is: George James Allman (1871): A Monograph of the Gymnoblastic Or Tubularian Hydroids: In Two Parts, Part 1: The Hydroida In General, pp. 90 – 92

You can find the book here: https://www.google.de/books/edition/A_Monograph_of_the_Gymnoblastic_Or_Tubul/YE9TAAAAcAAJ?hl=de&gbpv=1&dq=A+Monograph+of+the+Gymnoblastic+Or+Tubularian+Hydroids:+In+Two+Parts&printsec=frontcover

Next two are:

Medusa – Free-swimming adult stage of the Cnidaria phylum
Unfortunately, I could not find out who used this term first until now. But I’m still searching.

Polyp – Sessile adult stage of the Cnidaria phylum 
The Source at least for the naming of these organisms is: Réaumur, R.-A. F. de. 1740: Mémoires pour servir a l'histoire des insectes Vol. 5. Paris: Imprimerie Royale. 1740

**Comment by odontaster** [comment]
@Osanna123 will create the codes and check whether these are used for Baltic samples.

**Comment by Osanna123** [comment]
LV-AT
AD-ME
AD-PO
