### ISSUE TITLE
RDBES: New codetype 'AuxiliaryVariableName' with 4 codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#483]
Hi Adriana
The Core Group would like to request the following new codetype:
Codetype                         Description
'AuxiliaryVariableName'   Auxiliary variables are 'extra' variables measured in association with the desired variable that might be used to increase precision of the estimate.

Code						Description
WeightLandingsGroupedSpecies	Weight of the landings of several species e.g. gadoid. 
WeightLandingsSingleSpecies	Weight of the landings of single species
SortingEffort					The amount of effort spent on sorting the catch
FishingEffort					The amount of effort spent on fishing

Cheers Kjems

**Comment by odontaster** [comment]
https://github.com/ices-tools-dev/RDBES/tree/master/Documents
Already published here with no reference to the codes.

**Comment by odontaster** [comment]
RMG would suggest more compact codes, with complete descriptions:

LandingsGS Weight of the landings of several species e.g. gadoid.
LandingsSS Weight of the landings of single species
EffortSorting The amount of effort spent on sorting the catch
EffortFishing The amount of effort spent on fishing

The first part of the code refers to the measure and the second part specifies the details of the subject.
@HenrikK-N

**Comment by odontaster** [comment]
Will create it, invisible, pending suggestions to be confirmed by @HenrikK-N

**Comment by HenrikK-N** [comment]
The Core Group suggest to rename the code ‘LandingsGS’ to ‘LandedWeight’ and update the description to: ‘Weight of the landing’, and delete the code ‘LandingsSS’.
