### ISSUE TITLE
26th June DPT review meeting and actions

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#484]
### Review team:
Jens, Sjur, Joana, Malin, Neil

### Latest version: 
https://community.ices.dk/Committees/DIG/Master%20documents/Data-Profiling-Tool/Data%20Profiling%20Tool_%20Template_Summary-26June2023.xlsx

**Comment by neil-ices-dk** [comment]
**24.1.23 Small Cetacean Bycatch**
@neil-ices-dk to contact FO professional officer and follow-up (2 critical issues)

**31.8.22 Geophysical Map**
@neil-ices-dk to contact Inigo to discuss, not clear what the product is? (Critical Issue)

**02.5.23 EMODnet Human Activities**
@neil-ices-dk to contact Andy Kenny and point out the issue of squeezing multiple products into one entry (Critical Issue)

**08.05.23 Seatrack (Birds)
@neil-ices-dk to contact officer for WKBB and follow-up (1 critical issue)

**09.06.23 Birdlife
@jensr to contact Bethany and cc: Ruth Fernandez to follow-up on issue of generic citation to whole database (Critical Issue)

**29.6.22 Aquaculture
@neil-ices-dk and @pcrjoana follow-up with Anne Cooper


**Other actions
@pcrjoana to update form question 14 (Provide a textual citation of the dataflow/product) to include a subtitle with a generic citation example

**Comment by neil-ices-dk** [comment]
- [x] 24.1.23 Small Cetacean Bycatch: emailed summary to Ruth Fernandez, awaiting follow-up
- [x] 31.8.22 Geophysical Map: emailed Inigo, awaiting follow-up
- [x] 02.5.23 EMODnet Human Activities: emailed Andy Kenny, awaiting follow-up

**Comment by neil-ices-dk** [comment]
@pcrjoana i have done the ones above, will you take the aquaculture one your PDF'd and write to Anne Cooper for follow-up. Thanks

**Comment by pcrjoana** [comment]
Done!

**Comment by pcrjoana** [comment]
Added a generic example (if we can call it that) to question 15 (citation):

![image](https://github.com/ices-eg/DIG/assets/49305340/ccfe880e-21ad-4c3d-8ddb-a0c331e44335)
