### ISSUE TITLE
Ecoregions review for CRM/RCT

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#49]
RCT is using ecoregions references as below. Only the ones in bold are in the Ecoregion Vocab https://vocab.ices.dk/?ref=1414
two actions are requested
1. decide if FAO areas belong to this vocab, or the respective codes from ICES_Area should be used instead https://vocab.ices.dk/?ref=358
2. add missing EcoRegions to the vocab

Name
--
Adriatic Sea
Aegean-Levantine   Sea
**Arctic Ocean**
Arctic   Sea (FAO area 18)
Atlantic, Antarctic (FAO area   48)
Atlantic,   Eastern Central (FAO area 34)
Atlantic, Northeast (FAO area   27)
Atlantic,   Northwest (FAO area 21)
Atlantic, Southeast (FAO area   47)
Atlantic,   Southwest (FAO area 41)
Atlantic, Western Central (FAO   area 31)
**Azores
Baltic Sea
Barents   Sea
Bay of Biscay and the Iberian   Coast**
Black   Sea
**Celtic Seas
Faroes
Greater North Sea
Greenland   Sea
Icelandic Waters**
Indian   Ocean, Antarctic and Southern (FAO area 58)
Indian Ocean, Eastern (FAO area   57)
Indian   Ocean, Western (FAO area 51)
Ionian Sea and the Central   Mediterranean Sea
Mediterranean   and Black Sea (FAO area 37)
**Norwegian Sea
Oceanic   Northeast Atlantic**
Pacific, Antarctic (FAO area 88)
Pacific,   Eastern Central (FAO area 77)
Pacific, Northeast (FAO area 67)
Pacific,   Northwest (FAO area 61)
Pacific, Southeast (FAO area 87)
Pacific,   Southwest (FAO area 81)
Pacific, Western Central (FAO   area 71)
Western   Mediterranean Sea

**Comment by Osanna123** [comment]
Non-ICES Ecoregions would need a separate Code Type (Ecoregions outside of ICES area)

**Comment by neil-ices-dk** [comment]
follow segmentation like this and change CodeType label
![image](https://user-images.githubusercontent.com/23527005/108211126-a3784500-712c-11eb-80e3-3c52724d1ea3.png)

**Comment by Osanna123** [comment]
List of Ecoregions is updated, also labels for the existing codes edited to remove the 'Ecoregion' part. 
And what was the conclusion for the FAO areas? New ref. list, or something like https://vocab.ices.dk/?CodeTypeRelID=358&CodeID=156504 ?

**Comment by mikeydrew** [comment]
@Osanna123  Can you please give me an update on what was decided for the following? Thanks

> List of Ecoregions is updated, also labels for the existing codes edited to remove the 'Ecoregion' part.
> And what was the conclusion for the FAO areas? New ref. list, or something like https://vocab.ices.dk/?CodeTypeRelID=358&CodeID=156504 ?

**Comment by Osanna123** [comment]
ICES_Area will be mapped with the DatasetVer, and CRM-RCT will be linked with the area codes needed for the project

**Comment by Osanna123** [comment]
https://vocab.ices.dk/?CodeTypeRelID=358&CodeID=232105

**Comment by mikeydrew** [comment]
Many thanks @Osanna123
