### ISSUE TITLE
Station vocab - possibly remove test stations?

### ISSUE THREAD

**Issue by HansMJ** [ices-eg/DIG#493]
In the Station vocab there are some test stations. Could they be removed?
![test stations](https://github.com/ices-eg/DIG/assets/17447426/73fcc76b-f86a-4f59-9711-77719410e73d)

Requested by Rob (removal of 13773/TestBulkUload)
https://github.com/osparcomm/HARSAT/issues/227

**Comment by neil-ices-dk** [comment]
@Osanna123 to check and deprecate the codes

**Comment by pcrjoana** [comment]
Any development on this?

**Comment by Osanna123** [comment]
Codes were deprecated, @HansMJ to make sure they are flagged respectively in the webservices

**Comment by HansMJ** [comment]
Thanks @Osanna123, I will inform Rob about this. There is a issue in the [HARSAT GitHub](https://github.com/osparcomm/HARSAT/issues/227) on this
