### ISSUE TITLE
Harmonization of Metier L6 and Gear L4: New Gear L4 LH

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#495]
For bycatch submission, Spanish submitters needed Gear L4 LH, corresponding to Metier L6 LH

**Comment by odontaster** [comment]
I contacted ISSG, Josefine Egekvist and she agreed that this is needed. I cretaed the generic LH in GearL4.

**Comment by Osanna123** [comment]
@odontaster to check the reference for Gear types L4 in DCF/JRC list(s)

**Comment by odontaster** [comment]
Dear Adriana, 

I brought up this issue to the chairs for the gear type to match the metier LH_. Since the code LH is not foreseen in the COMMISSION DELEGATED DECISION (EU) 2021/1167 and it is not used by the fleet economic data call they did not think it would be crucial to include this. 
In the gear list of the FDI data call there are already the 2 following gear codes:
Handlines and pole-lines (mechanised) LHM
Handlines and pole-lines (hand-operated) LHP
that specifies the LH. But you think this would not be sufficient? maybe I misunderstood something.

Warm greetings from Ispra. 

Kind regards, 
Zeynep

**Comment by odontaster** [comment]
In the light of this, I would reject this request.
