### ISSUE TITLE
Cetaceans: Two new codes needed in Order

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#497]
From the requester:

I was wondering if you could add another couple of terms to the 'PlatformInstance' vocab (https://vocab.ices.dk/?ref=1724). Aerial surveys have observers on the left and right side of the plane, so 'primary' and 'secondary' aren't quite correct for aerial. 

Could you add 'Right' and 'Left' to this vocab list please?

**Comment by Osanna123** [comment]
@pcrjoana to check with the group if this should be a new field or the present fields can be used for separating observations from the left/right sides of the plane

**Comment by pcrjoana** [comment]
The group decided that the codes are no longer needed and they can use the field "angleofsearch" for the purpose they wanted to use the codes "left" and "right".
