### ISSUE TITLE
Cooperating Organisations review for RCT

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#50]
Julie Kellner reviewed the CooperatingOrganizations vocab http://vocab.ices.dk/?ref=1669, suggesting one code change and several alterations to the code descriptions as follows: 

- [x] CBD – acronym should be SCBD
- [x] UNEP – to be consistent with full title of another entry (UNESCO-IOC), change UNEP long name to United Nations Environment Programme
- [x] long names remove the “The” in front of 4 entries EEA, NASCO, OSPAR, CIESM
 - [x] OSPAR – capitalize Marine
- [x] GFCM – long name is General Fisheries Commission for the Mediterranean
- [x] IMBeR – long name remove the word project, should just be Integrated Marine Biosphere Research
- [x] Eurostat – longname is Statistical Office of the European Union
- [x] UNESCO-IOC – remove comma after Scientific

**Comment by Osanna123** [comment]
I think, this codetype is presently used only by the RCT

**Comment by Osanna123** [comment]
@mikeydrew , @jbkellner done, will be published on web tomorrow.
Note, IOC is normally referred to as the 'Intergovernmental Oceanographic Commission of UNESCO', without spelling out what UNESCO stands for.

**Comment by jbkellner** [comment]
@Osanna123 @mikeydrew  
Thanks Anna, so if you let me know what if preferable, I will add these updates to the printed form when it is updated so they match.  Are we going with acronym UNESCO-IOC and full name Intergovernmental Oceanographic Commission of UNESCO?

**Comment by neil-ices-dk** [comment]
@Osanna123 can you confirm to Julie the decision on UNESCO label - thanks 🥇

**Comment by Osanna123** [comment]
@jbkellner , it was decided to keep the acronym UNESCO-IOC, but change the description to 'Intergovernmental Oceanographic Commission of UNESCO'.
Present description will be moved to the Long description, if it does not interfere with any procedures that @mikeydrew has for this vocab.
