### ISSUE TITLE
DATRAS_LT: New CodeType C-TS-REV2

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#503]
WGML decided to create a new C-TS_REV2. For the time being the only difference with the C-TS-REV is that it should include A15 and A16, but there might be some more changes in the next year.
For that:
-Create C-TS-REV2
-Deprecate A15 and A16 in C-TS-REV
-Review submissions done under C-TS-REV with A15 and A16 values, ask for resubmission with new code.

**Comment by cekv** [comment]
Go ahead :)
