### ISSUE TITLE
RDBES: SamplingScheme, new codes

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#505]
It took some time as the submitter had to send me the descriptions.
Some exist without description and some are brand new.
https://vocab.ices.dk/?codetypeguid=6255253a-cc20-47a9-aa63-864dc6d476db

EST_OnShoreCommercialCoastal - Biological samples from commercial landings in costal fishery using passive gears and small boats (<12m).
EST_OnShoreCommercialMarkets - Biological samples from commercial landings in costal fishery from markets.
EST_SelfOnShoreCommercialCoastalSalmon – Biological salmonid samples by fishermen from landings in costal fishery.
EST_OnShoreCommercialPelagic - Biological herring and sprat samples from commercial landings from Baltic Sea pelagic trawlers
EST_OnShoreCommercialPelagicGOR - Biological herring and sprat samples from commercial landings from Baltic Sea pelagic trawlers fishing in Gulf of Livonia
EST_AtSeaCommercialNEAFC - Biological samples by observers on Estonian trawlers fishing in NEAFC regulatory area
EST_AtSeaCommercialNAFO - Biological samples by observers on Estonian trawlers fishing NAFO area

**Comment by Osanna123** [comment]
EST_OnShoreCommercialPelagicGOR Gulf of Riga or Livonia?
