### ISSUE TITLE
ENV link Dataset LT to a Theme

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#506]
for AIMS

**Comment by Osanna123** [comment]
temporarily linked to CON for testing purposes, but it needs a bit of discussion

**Comment by MariaMakri** [comment]
@neil-ices-dk what do you think about Litter as a new Theme?
https://vocab.ices.dk/?codetypeguid=c1887911-3ea7-4ad9-a844-ba989e6b5b9c

**Comment by neil-ices-dk** [comment]
> @neil-ices-dk what do you think about Litter as a new Theme? https://vocab.ices.dk/?codetypeguid=c1887911-3ea7-4ad9-a844-ba989e6b5b9c

Marine Litter; yes 👍🏼

**Comment by odontaster** [comment]
LT-DATRAS would also be linked to this theme.

**Comment by Osanna123** [comment]
Datasets LT and LT-DATRAS are now linked to Theme ML
@mehdiabbasi @odontaster
