### ISSUE TITLE
Adoption of machine learning processes causes enhanced quality checking

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#518]
Aspect| Description
-- | --
Opportunities |​Scope to extended quality checks based on much larger/wider patterns or historic data in a manner that is often tedious or difficult to craft for individual parameters in large datasets. Also potential for faster QC making data available for advice and processing quicker.
Action required | Communication of best practice
Ownership | No specific owner

[legacy entry ](https://community.ices.dk/Committees/DIG/Lists/DIG%20future%20challenges%20and%20opportunities/DispForm.aspx?ID=5&Source=https%3A%2F%2Fcommunity%2Eices%2Edk%2FCommittees%2FDIG%2FLists%2FDIG%2520future%2520challenges%2520and%2520opportunities%2FAllItems%2Easpx&ContentTypeId=0x0103007DB8903096FFDD4BA4F2198AC9382C28)

**Comment by jensr** [comment]
Updated to be opportunity. Likelihood and impact set to medium as some ML QC is likely to be increasingly embedded in short to medium term, with medium impact in terms of reducing workload (could be lower or higher depending on the exact data sources that may be QC'ed like this)

**Comment by jensr** [comment]
Potential consideration within the context of WKFAQ?

**Comment by OliverWilliamsDataManager** [comment]
Link to the challenge #515

**Comment by OliverWilliamsDataManager** [comment]
Closed this one to roll this item into #581
