### ISSUE TITLE
MAGG Discontinuing the Marine Aggregates

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#539]
WGEXT has changed their way of collecting and processing data since their request to ICES DC to host a marine aggregates database. Therefore, our project never kicked off, and can be archived.
The dataset is using some shared and unique reference lists, the latter can be deprecated or at least made invisible in the Vocab.
shared:
ISO_3166
EDMO
YesNoFields
AreaType

unique (right?):
https://vocab.ices.dk/?ref=1520 Magg license type
https://vocab.ices.dk/?ref=1523 Value_Type
https://vocab.ices.dk/?ref=1521 AlwaysNeverFields
https://vocab.ices.dk/?ref=1519 GrainSize

**Comment by MariaMakri** [comment]
@Osanna123 To contact WGEXT to ask whether the codes are used. 
If not, then deprecate.

**Comment by MariaMakri** [comment]
@Osanna123 Have you heard from WGEXT?

**Comment by Osanna123** [comment]
Reply from Keith Cooper, WGEXT Chair:
'...We’re not using the reference lists, so I would agree that they can be deprecated...'

**Comment by Osanna123** [comment]
CodeType can not be deprecated. Made invisible with the comment 'No longer in use, discontinued in 2024 by agreement with WGEXT'
