### ISSUE TITLE
CNTRY codelist now has DENMARK in capital as the only country

### ISSUE THREAD

**Issue by HansMJ** [ices-eg/DIG#54]
The [CNTRY codelist](https://vocab.ices.dk/?ref=22) was modified in January to have the code for Denmark changed to capital (DENMARK). This now get included in output products and it looks strange that Denmark is the only country where this is the case. 

I suggest the code to be changed back to Denmark again.

**Comment by Osanna123** [comment]
@Kadji, could you please let us know what was the reason for editing this code on the 2021-01-29? Reference Management Group did not receive any information on this edit.
