### ISSUE TITLE
STAGE revision

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#541]
CodeType STAGE https://vocab.ices.dk/?codetypeguid=76fab5ff-5f3e-4488-8167-17d360f47c35
is primarily used for DOME. In 2012 some stages were added for E&L (descriptions starting with 'E&L surveys:'). 
But since 2017 DevScale and DevStage were created specifically for E&L instead.
Are the old codes in use? (old e&l datasets)
Can we deprecate them as not recommended for use?

**Comment by odontaster** [comment]
Hi @Osanna123  this was asked to the governance group and yes, they can be deprecated

**Comment by odontaster** [comment]
Hi @Osanna123 I confirm these can be deprecated, not in use in ELDB
