### ISSUE TITLE
ICES method/stock categories for use in SiD and SAG 2024

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#542]
Secretariat task: Clean up 'StockCategory' vocab: https://vocab.ices.dk/?codetypeguid=a8bafcff-9720-4349-8e81-09b160e59bf7 

Add the new method categories below
Will need to keep old ones for legacy ("Category 3 - method not in use), but ok to make them invisible (to be removed from the template).

Code             Description
2.1                Category 2 method using SPiCT
2.31              Category 2 method using SPiCT for short-lived stocks
3.21              Category 3 method - rfb rule with MSY advice
3.22              Category 3 method - chr rule with MSY advice
3.23              Category 3 method - rb rule with PA advice
3.32              Category 3 method - chr rule for short-lived stocks with MSY advice
3.33              Category 3 method - 1 over 2 rule for short-lived stocks with PA advice

Need to deprecate codes that are no longer in use

have not received the list of codes yet from Anne, but these are codes for methods that have been used before, but are no longer in use and the option to use them should be removed (SAG/SID)

**Comment by cekv** [comment]
Improve descriptions for the codetype and for the codes. Codes for categories of stocks (i.e 1-6) should be deprecated from the list - and linked to ICES_stock_category. Add link to documentation (ask Anne).

**Comment by pcrjoana** [comment]
Where are we with this? It's been sitting in "under evaluation" for a while.

**Comment by Osanna123** [comment]
@cekv 
make the deprecated codes invisible
add extended info on rules to the long descriptions
link codetypes StockCategory and ICES_Stock_Category and their respective codes
