### ISSUE TITLE
a test for you ladies...

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#544]
first one to spot the error

![image](https://github.com/ices-eg/DIG/assets/23527005/addb688b-7923-4cf9-b7af-27d43b9b62b6)

**Comment by pcrjoana** [comment]
9. a instead of 9.a?

**Comment by pcrjoana** [comment]
Also an issue here:

<img width="341" alt="image" src="https://github.com/ices-eg/DIG/assets/49305340/3deb0d55-8c65-4ec3-a306-f0b86fecd6d3">

**Comment by pcrjoana** [comment]
I also found a typo on ICES area:
<img width="742" alt="image" src="https://github.com/ices-eg/DIG/assets/49305340/23026982-fb07-4edb-b6f8-96019af9c2c8">

**Comment by pcrjoana** [comment]
Fixed both 9. a to 9.a and the typo in "Portugese" (that was actually present in a couple of other codes). @neil-ices-dk to confirm if there is any other error we need to find.

**Comment by neil-ices-dk** [comment]
thanks @pcrjoana 👍
