### ISSUE TITLE
ENV2023-11-02 CRMCO request

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#547]
DE request for a new CRMCO code
https://vocab.ices.dk/?codetypeguid=bd91ded1-6729-425a-b864-d49224a9f6b6
Question is whether it is SRM or CRM

**Comment by Osanna123** [comment]
[Biota-344.pdf](https://github.com/ices-eg/DIG/files/13278303/Biota-344.pdf)

**Comment by cekv** [comment]
SampleRoundID could go into the description :)

**Comment by Osanna123** [comment]
Q-BT-244
