### ISSUE TITLE
Stomach content: Midwater trawl code request for SMTYP 

### ISSUE THREAD

**Issue by MariaMakri** [ices-eg/DIG#549]
After a submitter tried to upload data using OTM (Midwater Otter Trawl) as gear, we noticed that Midwater Trawl is missing from the SMTYP code type;

http://vocab.ices.dk/?ref=152

There is this code instead, I am not sure if there is a difference with OTM (Midwater Otter Trawl)  and if we should create a new code 

<img width="406" alt="image" src="https://github.com/ices-eg/DIG/assets/63644594/e09175b5-69ac-483d-8345-7ff0d3c24590">

**Comment by pcrjoana** [comment]
Please do not forget to link to dataset.
