### ISSUE TITLE
New codes for METOA

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#55]
French DOME data submitter is requesting new codes for METOA (https://vocab.ices.dk/?ref=173)

//Cancelled: 
High content semi-automated screening count (HCS). existing MIC-LM will be used instead
Assessment of lysosomal structural alterations (LSC) by image and stereology analysis and calculation.
Histochemical evaluation of intracellular accumulation of neutral lipids//

**Comment by cekv** [comment]
@Osanna123 Please provide a more detailed description.

**Comment by Osanna123** [comment]
Request cancelled by the requeter
