### ISSUE TITLE
Open code improves ICES output

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#552]
<html><body>
<span id="part1">

Aspect| Description
-- | --
Opportunities | More "eyes" can mean errors in code are more likely to be found. A formal process will increase the quality of code.
Enabling strategies | ​Quality management framework.  Code testing. Code reviews. Standardised test datasets.  Benchmark process. TAF. Shiny App hosting procedure. Standardised tests

</span>
</body>
</html>

**Comment by sjurl** [comment]
Previous #379

**Comment by sjurl** [comment]
Likelihood: Currently aprox 10 % of software for stock assesment is managed through TAF, DIG is aware of other users of open code packages that improve  the overall workflow, but at this point in time it is not a fully matured process
Impact: Openness of code represents an opportunity to provide a good amount of quality assurance but isn't an automatic fix

**Comment by OliverWilliamsDataManager** [comment]
Linked to #579 as a duplicate and closed
