### ISSUE TITLE
to discuss reference code creation links on ices.dk

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#556]
We have two places, mentioning code request: Data Tools menu ‘Code request’ and Vocabularies menu ‘Requesting new codes’.
The first one, while looking generic, redirects to the platform/station requests. This leads to some confused requesters asking for a login to request some Intercatch codes.
The second needs a slight revision/update, and perhaps a link to our GitHub board (as a replacement of the old request form that is no longer available).

**Comment by pcrjoana** [comment]
Originally created by @neil-ices-dk. I just converted it to issue.

**Comment by Osanna123** [comment]
- [ ] Data Tools menu label ‘Code request’ should be renamed to ???
- [ ] https://www.ices.dk/data/vocabularies/Pages/default.aspx menu Code Request Application needs revision to ???
- [ ] in https://www.ices.dk/data/vocabularies/Pages/Requesting-new-codes.aspx we need a new call to action 'Request a new code' with link to https://github.com/ices-eg/DIG/projects/2
- [ ] in https://www.ices.dk/data/vocabularies/Pages/Requesting-new-codes.aspx the text needs to be reviewed to more generic, and less ENV.

**Comment by MariaMakri** [comment]
Create a new landing page for Code Requests that contains separate links for Platform, Station, and all other codes (microsoft form)

**Comment by pcrjoana** [comment]
Form created. Closing this issue, and we continue on #573
