### ISSUE TITLE
Update ESAS species table

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-eg/DIG#558]
Here is an overview of the latest commits in the (parallel) species table published at [https://esas-docs.ices.dk/species/](https://esas-docs.ices.dk/species/), that should be executed in the ESAS species table managed at ICES DC:
[https://github.com/ices-tools-dev/esas/compare/6564e0ff8aa3058d1b875f8dd90ee9ac48cd6dd3...f24180d7adb80e6464c2e1adccce737f0193624d](https://github.com/ices-tools-dev/esas/compare/6564e0ff8aa3058d1b875f8dd90ee9ac48cd6dd3...f24180d7adb80e6464c2e1adccce737f0193624d)

**Comment by nicolasvanermen** [comment]
Note the some of the highlighted changes may already be incorporated in the table managed at ICES DC. All of this was discussed with Carlos Pinto and Anny Osypchuk, and documented at [https://github.com/ices-tools-dev/esas/issues/141](https://github.com/ices-tools-dev/esas/issues/141)

**Comment by Osanna123** [comment]
done, also the EURING codes are adjusted to 5 digits. Some discrepancies between ESAS and EURING Latin names exist. EURING codes are not verified by ICES
