### ISSUE TITLE
New codes for METPT

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#56]
French DOME data submitter requested new codes for METPT (https://vocab.ices.dk/?ref=201)
Code Description
HIS-PR resin inclusion
  cross section - NA
HIS-PW Paraffin wax
ST-HE Hematoxylin/Eosin staining
ST-HES Hematoxylin/Eosin/Saffron staining
ST-DAPI Staining with DAPI     --according to Vincent-Hubert et al. (2011)
SEC-CRY Cryotome sectioning
FIX-BFC Baker’s formol calcium solution fixation
KGG Kaiser´s glycerol gelatine mounting medium
ST-ORO Staining with Oil Red O (ORO)
ED Enzymatic deconjugation
R-NaCl NaCl saline solution rinse
ALA-CB Acid labilisation (citrate buffer)

Postcoupling medium incubation
beta-glucuronidase substrate medium incubation
Cell incubation with acid phosphatase
Incubation with N-acetyl-β-hexosaminidase

**Comment by Osanna123** [comment]
For Resin inclusion and parrafin wax, there are HIS-PR and HIS-PW codes in METOA, but submitter insists on that they are pretreatment steps, while METOA should be MIC-LM, and recommends moving the definitions

**Comment by Osanna123** [comment]
Submitter prefers specifying 'çross section', although they do not expect using 'longitudinal section' in any near future.

**Comment by cekv** [comment]
@Osanna123 ask submitter not to specify cross section.

**Comment by pcrjoana** [comment]
Anna implemented most of the codes and is waiting for information on the remaining codes.

**Comment by Osanna123** [comment]
METPT ‘incubation with acid phosphatase’ and ‘Incubation with N-acetyl-β-hexosaminidase’ – provided documentation points to  the ‘cell incubation with acid phosphatase in hepatocyte lysosomes’ and the ‘cell incubation with N-acetyl-β-hexosaminidase in lysosomes of digestive cells’ instead. Requester however specified that the codes should not be species or tissue specific. Suggest keeping 'cell incubation', but removing 'in lysosomes'

**Comment by cekv** [comment]
Keep lysosomes, remove the hepatocytes and digestive cells. Ask requester if he is happy with this.

**Comment by Osanna123** [comment]
CI-AP-L
CI-HEX-L
