### ISSUE TITLE
SmartDots: new codes for SampleType

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#563]
A SmartDots user would like to use SmartDots to age mollusk shells and marine mammal teeth. This wouldn't change anything in the software, but it would require those two codes to be added to SampleType. See original email bellow. Julie forwarded this to us asking if we could add these codes to SampleType.

"Do you know instances where Smart Dots has been used for things like mollusk shells and marine mammal teeth used for age estimation? 

I gave a presentation on DFO Dots today and some people that use these structures were asking whether they could use the tool with their structures, and I saw no reasons why not. However, when I look at the ICES vocabulary for “Sample Type”, those type of structures do not appear:
http://vocab.ices.dk/?ref=1507"

**Comment by cekv** [comment]
Use Shell and Tooth, not species specific :)

**Comment by pcrjoana** [comment]
Implemented.
