### ISSUE TITLE
EDMO updates

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#566]
Happy new year Michala,
 
With regards to your question about the PO Box, the answer is that it is not valid.
With regards to the information that is shown below, the postal code is wrong - it is 100.
 
Also, I see that the information in the EDMO database for 3084 (attached picture) and 1780 are still not correct. 
 
All the correct information can be seen in the attached word file where edits are made with "track changes" on. Thus, in the word file, everything with no line through it is correct, and everything that is "Striketthrough" should be deleted.
 
So please, can you have another look at it??
 
Thanks in advance,
 
Solva Eliasen

**Comment by odontaster** [comment]
[Modified copy of EDMO 3084 og 1780.docx](https://github.com/ices-eg/DIG/files/13818058/Modified.copy.of.EDMO.3084.og.1780.docx)
![Capture](https://github.com/ices-eg/DIG/assets/18613829/31e2f4a9-02c5-4ed0-bd8c-74e39abce231)

**Comment by cekv** [comment]
The requester can be given a contact, we do not manage EDMO codes.
