### ISSUE TITLE
Datasets names and descriptions in AIMS

### ISSUE THREAD

**Issue by MariaMakri** [ices-eg/DIG#574]
Link to Adriana's document: https://icesit-my.sharepoint.com/:x:/g/personal/adriana_villamor_ices_dk/EYFghZqHQR1Ji5WhYkcmVFABitM98lu4RKTxxsJCRAxsFg?e=1wWbTy

Agreed to change case category codes in AIMS to theme code-dataset code if applicable.

**Comment by odontaster** [comment]
I am afraid I created a new file with almost the same name.
https://icesit-my.sharepoint.com/:x:/g/personal/adriana_villamor_ices_dk/Ef2qGcv1FYNKrP0_WmoVdCwByURyjJry0YGO9DWM2FzwGg?e=RdauIe

Did my data flows and I have to say that I am not loving the resulting codes.

**Comment by Osanna123** [comment]
I'm happy with my datasets now

**Comment by odontaster** [comment]
Made some peace with the Theme-Dataset codes. We should try to stick to those (with exceptions), in the long run will make theme codes more useful.
