### ISSUE TITLE
InterCatch: New stock codes 

### ISSUE THREAD

**Issue by MariaMakri** [ices-eg/DIG#577]
The following pseudo stocks (not official ICES stocks) were added as requested by WGDEEP. This was for submitters to be able to also submit data for these stocks where they exists together with existing sole and argentine stocks. 

-Code: oal.27.8c9a,      Description:   Senegalese sole (Solea spp.) in divisions 8.c and 9.a (Cantabrian Sea and Atlantic Iberian waters)
-Code: sos.27.8c9a,      Description: Sand sole (Pegusa lascaris) in divisions 8.c and 9.a (Cantabrian Sea and Atlantic Iberian waters)
-Code: soo.27.8c9a,     Description: Sole (Solea spp.) in divisions 8.c and 9.a (Cantabrian Sea and Atlantic Iberian waters)
-Code: ary.27.nea,       Description: Argentine (Argentina sphyraena) in the northeast Atlantic
-Code: arg.27.nea,      Description: Argentina spp. in the Northeast Atlantic

Long description:  Not an official ICES Stock

**Comment by Osanna123** [comment]
IC_Stock, already created
Deprecated from ICES_Stock - please delete.
Check OAL vs SOO and descriptions

**Comment by MariaMakri** [comment]
There was a mistake in the description, OAL is Solea senegalensis, not solea spp. I have corrected it. Codes were deleted from ICES_Stockcode

**Comment by MariaMakri** [comment]
2 new, not official ICES stocks were added in IC_Stock:

ofj.27.nea	Neon flying squid (Ommastrephes bartramii) in the North East Atlantic	
squ.27.nea	Various squids nei (Loliginidae, Onnastrephidae) in the North East Atlantic

**Comment by MariaMakri** [comment]
@MariaMakri to change North East to northeast
