### ISSUE TITLE
New landing page for DATSU

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#585]
New landing page for DATSU under development 

https://www.ices.dk/data/tools/Pages/datsu.aspx

Review text document - for main description
[Datsu for web.docx](https://github.com/ices-eg/DIG/files/14176777/Datsu.for.web.docx)

**Comment by MariaMakri** [comment]
Shorten the description of the different datasets. Also more datasets have separate access points (not only Intercatch).

**Comment by neil-ices-dk** [comment]
> Shorten the description of the different datasets. Also more datasets have separate access points (not only Intercatch).

@cekv I have updated the text and made a change to the link description, is it ready to publish?

**Comment by Osanna123** [comment]
Add DATSU to the sub-menu of 'Data tools' on the left-hand side under the Data Tools menu

**Comment by neil-ices-dk** [comment]
> Add DATSU to the sub-menu of 'Data tools' on the left-hand side under the Data Tools menu

@neil-ices-dk to action
