### ISSUE TITLE
FAO Global Record of Stocks and Fisheries: UUID

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#59]
not urgent, just warming you up 😄 response to FAO below on global unique ID's for stocks

Dear Aureliano and the FAO team,

We heard from Ruth that there are some follow-up questions related to the below and to the GRSF GUID. Here are some answers, happy to have a chat if we have confused rather than clarified 😊

**DOI**
-	So far, we have only used DOI’s for the specific instance of a stock assessment (usually Year + Stock), so it is related in a 1:1 way with the Assessment Key in the Stock Assessment Database (SAG)
-	We wanted the DOI solution for a globally recognised URI that would accompany the DOI of the published stock advice and allow us to have a more transparent and citable system;
-	For the clients of advice, the linking backwards and forwards between the current and past stock instances was an important feature
-	We are using suffix namespaces (advice, data, pub) to denote the type of object resource the DOI is pointing to
-	We have not implemented this against the more ‘fixed part’ – the stock key which is related to the Stock Information Database (SID) and controlled in the ICES Vocab http://vocab.ices.dk/?ref=357 

**GRSF**
-	We simply hadn’t thought to include the GRSF against the stock key, but we all agree that this is a good idea and it would be easy for us to implement against our vocab and then to expose it via SAG and SID 
-	We had a look at the API and couldn’t get it to work for us i.e. http://updater.grsf.d4science.org/grsf-api/resources/stocks?from_year=2018 doesn’t return any results; 
-	Could you provide us with a table of all the GRSF UUID’s for ICES stocks so we can set this up in our vocab – is there any issue with publishing this subset of ICES related GRSF UUID’s in vocab.ices.dk for you?

Best, and hope you are all seeing signs Spring and the home haircuts aren’t as disastrous as here in the ICES Secretariat.

Neil

**Comment by cekv** [comment]
Waiting for list with links between ICES stocks and GRSF

**Comment by neil-ices-dk** [comment]
see SAG board issue for follow-up:
[globalID's](https://github.com/ices-tools-prod/icesSAG/issues/215)

**Comment by pcrjoana** [comment]
@cmspinto is this something Laure can help with?

**Comment by cekv** [comment]
> @cmspinto is this something Laure can help with?

@Milldaz

**Comment by pcrjoana** [comment]
@cmspinto and @Milldaz can you answer us, please?

**Comment by cekv** [comment]
@cmspinto and @Milldaz - Provided the list we can accommodate references in the stock vocabulary (most likely as an attribute)

**Comment by neil-ices-dk** [comment]
@cekv @cmspinto @Osanna123  can someone show me where this is implemented, i can't see it?

**Comment by odontaster** [comment]
Hi @neil-ices-dk I think this is still open in #400 , at the moment I sent some feedback on FAO list of codes and I am waiting for them to get back with the final list of uniqur identifiers

**Comment by neil-ices-dk** [comment]
thanks @odontaster - i suspected it might be, just lost track of issues on this one; will comment on #400
