### ISSUE TITLE
RECO data schematic

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#593]
I'm wrapping up the RECO data schematic for publication. Getting the dependency tables for this one wasn't easy, so could you all take a look at the tables in section 1, to make sure I didn't miss anything, please?
I'd appreciate it if you could give me feedback latest before the next RMG meeting, on 20 February.

You can find the document here:
https://community.ices.dk/Publications/dataflows/Shared%20Documents/13.%202023_RECO/RECO%20Dataflow.docx

**Comment by MariaMakri** [comment]
@pcrjoana to remove Oceanography, Historical Plankton and replace RDB by RDBES. Add VMS, OSPAR Birds and Seals, Preliminary Catches, VME, Stock Information Database (SID), Advice scenario database (ASD),
