### ISSUE TITLE
ICES_StockCode: rjh.27.4bc7d

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#598]
rjh.27.4c7d
“Blonde ray (Raja brachyura) in divisions 4.c and 7.d (southern North Sea and eastern English Channel)”

is now:

rjh.27.4bc7d
“Blonde ray (Raja brachyura) in divisions 4.b, 4.c and 7.d (central and southern North Sea and eastern English Channel)”

There is already advice on this new stock but the code was not requested.

**Comment by odontaster** [comment]
requested by @martinezinigo. Email sent to accessions

**Comment by MariaMakri** [comment]
Inform advice regarding the process. @pcrjoana  to write a document on changes in SID, SAG, and everything related to stock changes. @odontaster to create a new stock code.

**Comment by odontaster** [comment]
Created codes in ICES_StockCode and in IC_Stock.
@MariaMakri to inform InterCatch team on the change.
@odontaster to inform @martinezinigo

**Comment by odontaster** [comment]
will use the same UUID and link with the previous stock code
