### ISSUE TITLE
IROC Datasets

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#601]
Please Add the code 'IROC', description 'ICES Report on Ocean Climate' to the code type 'Datasets' asap in order to use this for the data portal and AIMS.

**Comment by pcrjoana** [comment]
Done, and also linked to "OCEAN" theme.

**Comment by odontaster** [comment]
There is no need to artificially link to Ocean theme, as IROC i not in the Data Portal and even if its a best fit it might e confussing.

**Comment by MariaMakri** [comment]
@HjalteParner We can change 'Ocean Hydrochemistry' theme to 'Ocean and Climate' or 'Ocean datasets'. If in the future new datasets come for climate we can consider creating a new theme.

**Comment by HjalteParner** [comment]
I think you misunderstand. I need a vocabulary for the ocean hydrochemistry datasets for the users of the oceanographic data submission format i.e. which code can they use, and IROC is not an option!

**Comment by HjalteParner** [comment]
Currently the the vocab shows the following but users cannot use the dataset "IROC" when submitting data to the oceanographic database.

![Image](https://github.com/user-attachments/assets/8346ff06-cc3b-44f2-b629-64f132560389)

**Comment by MariaMakri** [comment]
We'll create a new Theme Ocean Climate and re-map IROC to it.

**Comment by HjalteParner** [comment]
Please let me know when the IROC dataset link has been removed from the the Ocean Hydrochemistry theme, thanks.

FYI and just for record, after talking to Mehdi, I have found out, that it is in fact already possible to have a link only to the codes for a given codetype under a given theme, which bassically is the feature I'm after for in my format(s) description to guide the uses only to the relevant codes they should choose from.

Using the Ocean hydrochemistry theme as an example, then search for "theme" in https://vocab.ices.dk, choose the code type "theme" and then select "OCEAN" i.e. "Ocean hydrochemistry", and then select the code type "Datasets". This will give you all the relevant dataset codes for the Ocean hydrochemistry theme - except the current misplaced "IROC" datasets of course ;-) but that will be solve as soon as this dataset has been unlinked.

More important (as we cannot expect a user to go through all above steps to find relevant codes) the link to code provided https://vocab.ices.dk/?codeguid=75dcb17c-c593-4e9e-bd46-256c8c4709ae, will now point you directly to the dataset codes - however, only by chance, as the dataset is on top and not all codetypes relevant to ocean hydrochemistry is shown.

Perhaps a meeting with Mehdi could make finding codes for a given theme more direct or intuitive? I will let this be up to your group to discuss or not.

My few cents.

**Comment by MariaMakri** [comment]
@HjalteParner I created the new Theme code and unlinked IROC to OCEAN theme.
