### ISSUE TITLE
RDBES: New code type/list called Population with a list of codes

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#603]
Hi, the Core Group suggest to create a new code type/list called Population, see below:

Code type     Description
Population    Group of fish of one species which shares common ecological and genetic features. Use for populations (biological units) for specific species e.g. herring populations defined by WKSIDAC2.

The following codes and descriptions are suggested from Table 2 From WKSIDAC2 (2023):

Code	        Description
her_balN_sp	Central and Northern Baltic Spring spawning
her_balE_au	Eastern Baltic Autumn spawning
her_balS_sp	Southern Baltic Spring spawning
her_rug_sp	Rügen Spring spawning
her_balW_au	Western Baltic Autumn spawning
her_balW_sp	Western Baltic Spring spawning
her_idw_sp	Inner Danish waters Spring spawning
her_skag_sp	Skagerrak Spring spawning
her_lndv_sp	Landvik Spring spawning
her_ns_au	North Sea Autumn spawning
her_ns_sp	North Sea Spring spawning
her_down_wi	Southern North Sea Winter spawning
her_wos_sp	West of Scotland Spring spawning
her_irlNW_wi_sp	Northwest of Ireland Winter/Spring spawning
her_irs_au	Irish Sea Autumn spawning
her_celt_wi	Celtic Sea Winter spawning
her_bc_au_wi	Bristol Channel Autumn/Winter spawning
her_bc_sp	Bristol Channel Spring spawning
her_wch_wi	Western English Channel Winter spawning
her_mlfh_sp	Milford Haven Spring spawning
her_nea_au	Northeast Atlantic Autumn spawning
her_nor_sp	Norwegian Spring spawning
her_norfj_sp	Norwegian North Sea fjords
her_pachy_sp	Hybrids of Atlantic and Pacific herring
her_sykk_au	Sykkylven Autumn spawning
her_thf_sp	Trondheimsfjord Spring spawning

Cheers

**Comment by MariaMakri** [comment]
https://www.ices.dk/community/groups/Pages/WKSIDAC2.aspx

**Comment by MariaMakri** [comment]
#478

**Comment by MariaMakri** [comment]
The RDBES core group discussed, and will be using the codes already decided in issue #478

**Comment by MariaMakri** [comment]
Code type GeneticPopulation is created. https://vocab.ices.dk/?codetypeguid=a350e6dc-b5c3-41db-91bc-db0736eb743d
 @MariaMakri to link it to RDBES and talk to the team about adding the new field.
