### ISSUE TITLE
Draft DIG Agenda May 2024

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#606]
This is where the draft agenda for the DIG 2024 May meeting will be developed.  The meeting will take place from 10:00 21st May - 17:00 23rd May at ICES Secretariat, Copenhagen and online.

**Tuesday 21st May (10:00 - 17:30 CEST)**
AM: 
- Introduction, house-keeping, round-table
- Governance Groups presentations and discussions

PM: 
- Guidelines on Reference Management Best Practices
- Data Guidelines.  Updates on work done.
- Challenges & Opportunities.  Present the work done.
- Data embargoing (WGJCDP request).  Present the proposal and ask for feedback from DIG
- National presentations

**Wednesday 22nd May (9:00 - 17:30 CEST)**
AM: 
- Data Centre updates: 
  - Core Trust Seal accreditation status
  - ICES Spatial Facility Update
  - Data Validation
  - Present data comparison tool for DATRAS to DIG (Resubmission Alert App to Governance Groups)
  - ...
- Data Profiling Tool
  - Guidance document
  - The way forward
- Shiny hosting review
- Updates from SCICOM meeting
  - Ethical use of AI/ML tools in marine science
  - DEI (Diversity, Equality, and Inclusion)

PM: 
- Sub-group work: 
  - Challenges & Opportunities
  - Governance evaluations – new direction
  - Data policy review/ Data license review

Evening: 
- Social Dinner for in-person participants

**Thursday 23rd May (9:00 - 17:00 CEST)**
AM: 
- Agree dates for autumn and spring online meetings, and the 2025 meeting.
- Recommendations to DIG:
  - State of WKDSG and WKENSURE recommendations
  - WKSIDAC2 and WGSINS recommendations to DIG
- DIG - the next 3 years
- Updates from ICES on current projects
- Other actions raised during the meeting

PM: 
- Recommendations from DIG
  - Recommendation to SCICOM on Data embargoing (WGJCDP request)
  - ... 
- Mini-workshop from ICES Data Centre
  - TAF demonstration
  - AdviceXplorer
- Report text

There are a number of topics which will be covered during the meeting. 

**Challenges & Opportunities**
The work done to re-organise the Challenges & Opportunities tracker should be presented and reviewed by DIG.  This incorporates the following issues: 
* #600 
* #450 
* #465 

**Data Guidelines**
There are a number of ongoing actions related to Data Guidelines:
* #475 
* https://github.com/ices-eg/DIG/issues/6
* #278 
* #460 
* #458 
* #457 
* #117 

**Governance Groups**
We have invited the chairs of the governance groups to take part in first morning session of the DIG meeting.  To start with we’ll give the floor to each of the governance groups and ask them to make a short presentation (~10 mins), then in the second part we’ll have an open discussion where we can pick up on common topics and themes.
* #461 
* #313 

**Reviews**
There are a number of reviews which have been identified:
* #454 
* #527 
* #528 
* #455 

**Other actions**
Other topics to be discussed include:
* #529 
* #311 
* #309 
* #554 

**Data Centre Updates**
The Data Centre will give updates on a number of topics including:
* Core Trust Seal accreditation status
* #371 
* Present data comparison tool for DATRAS to DIG (Resubmission Alert App to Governance Groups)
* #632

**Comment by neil-ices-dk** [comment]
@davidcurrie2001 i've added the AI challenge/opportunity in 'other actions'; the presentation from SCICOM/ACOM could go nicely here to bring DIG up to speed https://community.ices.dk/Committees/SCICOM/2024%20March/03.%20Presentations/17.2-AI-SCICOM-13MARCH2024.pptx

**Comment by davidcurrie2001** [comment]
@neil-ices-dk is there anything else from the SCICOM meeting that we need to look at?

**Comment by neil-ices-dk** [comment]
> @neil-ices-dk is there anything else from the SCICOM meeting that we need to look at?

emailed you 📧
