### ISSUE TITLE
Create data flow code type

### ISSUE THREAD

**Issue by MariaMakri** [ices-eg/DIG#610]

**Comment by MariaMakri** [comment]
@MariaMakri @cekv @Osanna123 @odontaster to review by the next RMG

**Comment by MariaMakri** [comment]
[Uploading Dataflows (1).xlsx…]()

**Comment by pcrjoana** [comment]
[Dataflows.xlsx](https://github.com/ices-eg/DIG/files/14740476/Dataflows.xlsx)

**Comment by Osanna123** [comment]
Looks good, @pcrjoana remembers small changes needed.

**Comment by pcrjoana** [comment]
[Dataflows.xlsx](https://github.com/ices-eg/DIG/files/14834456/Dataflows.xlsx)
