### ISSUE TITLE
ENV new code type for AIMS DTYPEext

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#611]
We have a code type DTYPE that is mainly used for the ENV data and acting as one of the keys in AIMS https://vocab.ices.dk/?codetypeguid=639495e5-28b7-41de-9bd7-56f1ebbb38d2
But we also have the extended data types not covered by this code type, and they are needed to for building DOME data summaries and in the submission/resubmission logic.
Therefore, we need a new code type DTYPEext (extended data types).
To start with, the codes in it will be: CF, DF. EF, CW, EW, CS, ES, LT, PP, PB, ZP, ZB. it makes sense to link the codes to the ones in DTYPE.

**Comment by MariaMakri** [comment]
@Osanna123 to make a spreadsheet describing the linkages and logic between the codes

**Comment by Osanna123** [comment]
https://icesit-my.sharepoint.com/:x:/g/personal/anna_osypchuk_ices_dk/EeVJg5p_iz9KrZd68vvYdiYBuGwAGDGgQ70ijDcIuA9BhA?e=GJifls
mapping

**Comment by Osanna123** [comment]
DTYPEext is created, code PH is added for the Phaeocystis.
DTYPE descriptions remain unchanged for now
