### ISSUE TITLE
ISO_3166: ES-PV

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#614]
Some data for Eggs and Larvae are submitted with Country ES-PV. This might have had some reason in the past but currently the organization is part of the key, so there is no need for this code. Is this an official ISO code? I can only find it referred to the different spanish regions.

**Comment by pcrjoana** [comment]
What is the status of this? Can we close this issue?

**Comment by odontaster** [comment]
We will change in ELDB from ES-PV to ES.
Already changed in AIMS code, but remains in the description, I think it is good to keep some record of this, and the key is already ES.
