### ISSUE TITLE
New codes/codetype for VMS

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#616]
WGSFDGOV requested habitat codes for the VMS dataset. These are related to the MSFD, so there might be an external vocabulary we can use.

https://dd.eionet.europa.eu/vocabulary/msfd/broadHabitatTypes/view

**Comment by pcrjoana** [comment]
![image](https://github.com/ices-eg/DIG/assets/49305340/12670c5e-84e1-42e9-9fa5-d9f37a771929)

**Comment by MariaMakri** [comment]
@pcrjoana to add the new code type and link it to external codes code type.
Each code to be linked to external URI.
