### ISSUE TITLE
ELDB: Review of descriptions for NetClogging

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#618]
WGALES sent a recommendation to WGELFADG to clarify the different values:

0: No mesh clogging visible. Ratio of internal to external flowmeter revolutions >1.1
1: Mild clogging (5-25% of net). Ratio of internal to external flowmeter revolutions between 1.0 and 1.1
2: Moderate clogging (25-75% of net retaining biological material). Ratio of internal to external flowmeter revolutions between 0.75 and 1.0
3: Severe clogging (75-100% of net retaining biological material). Ratio of internal to external flowmeter revolutions <0.75
NA: Information not available

https://vocab.ices.dk/?codetypeguid=908b9da0-c5a5-4388-9c78-206c23396d0d

I think we could also improve the CodeType description:

NetClogging: Qualitative estimate of net clogging. The ratios refer to the flowmeters on Gulf 7 type samplers, any other samplers please refer to the percentages.

**Comment by Osanna123** [comment]
Add ratios to the long descriptions, making sure they are depicting info for Gulf 7, but not limiting use of the existing codes for other gears.
