### ISSUE TITLE
New litter categories

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#62]
DOME litter submitters requested
new PARAM LT-codes  https://vocab.ices.dk/?ref=37 for:

- [ ] < 5 mm non-plastic fragments and particles

- [ ] < 5 mm plastic fragments and particles

For macro-category:

- [ ] Fibres

and both micro and macro-categories for:

- [ ] (industrial) plastic pellets (nurdles) - we already have LT11, but need a new code to map to pargroup LT-MC https://vocab.ices.dk/?CodeTypeRelID=37&CodeID=196087

- [ ] Beads 

- [ ] Polystyrene (this would normally belong to TYPPL (https://vocab.ices.dk/?ref=1385), so maybe it should be covered by a more generic term in the PARAM? LT71 covers macro-version)

- [ ] Film (LT5 for macro-version?)

- [ ] Paint flakes 

//For info, <5mm is the identifier for microlitter
See also TSG-ML list https://vocab.ices.dk/?ref=1405

**Comment by Osanna123** [comment]
@MarilynnatICES is LT61 for Plastic barrels?
Can we add long description to LT60 that it is storage spacers?
LT67 - is acustic tag spelled correctly?

**Comment by MarilynnatICES** [comment]
Hi Anna,

The codes were added by Liv and I never had the chance to correct her work. There is a parked task (TFS 281) for these LT codes in ENV. They were to be checked and linked to the other lists.

The LT codes were supposed to be based on the TSG-ML list but, where they were unclear, they were often separated or clarified by creating more specific codes. For example, barrel would become plastic barrel and another code should be added for wooden barrel.

@MarilynnatICES<https://github.com/MarilynnatICES> is LT61 for Plastic barrels? Yes and I corrected  the spelling

Can we add long description to LT60 that it is storage spacers? Yes, go ahead but keep in mind the linking to the TSG-ML list (if that is relevant now-a-days).
LT67 - is acustic tag spelled correctly? No and I corrected the spelling.
Mvh,
Marilynn

**Comment by Osanna123** [comment]
Ask for references to the official definitions
 ...definition of 'Fiber'. Is filament/monofilament a good alternative?

**Comment by Osanna123** [comment]
for the first part of the initial request, information from the requester:
'...As for microlitter, there is no international harmonization on methods how to collect or analyze the samples. The work is still in progress. Overall in literature and usually in monitoring fibers or filaments are not included in the amount of fragments or particles. They are categorized separately. 
To my knowledge, there is no international database or guidelines how to report microlitter data or how to divide the found microlitter. ...'

'...Filaments/fibers are elongated thread-like microlitter in the size of <5 mm. It can be threads from clothes, ropes or fish nets etc.
Particles/fragments are any other type of microlitter with different shape or size <5 mm. It may be little particles from bigger objects or rounded pellets, metal or rust from ships, paint flakes etc. Paint is counted usually as plastic...
'
'...For EMODnet, I am using: 
H0100008 (non-plastic filaments)
H0100007 (non-plastic particles)
H0100004 (microplastic filaments)
H0100002 (microplastic fragments)

As we do not specify microlitter particle/fragment type in monitoring data, as described in EMODnet (I do not like the term “item” when we are speaking of microlitter. This seems not really correct if we are speaking of particles/fragments in the size of <5 mm). What I mean is, we just categorize filaments/fibers or particles/fragments – as in two main types. Next categorization with these two types is plastic or non-plastic. If possible, non-plastic particles/fragments are specified further: unknown, metal, rust, ash, glass etc. For EMODnet, we group all these non-plastic materials to H0100002 (microplastic fragments). 

For monitoring we use only microscopic method, as in visual analysing, so it is difficult to further categorize or even not very reliable to do that. Our monitoring does not include specifying microlitter shape or polymer type. Polymer type analysis is extremely expensive and time consuming.
Furthermore, in Estonian, we have only one way of saying particle/fragment. There is only one general term for that ...'

**Comment by Osanna123** [comment]
fibers=filaments, improve the descriptions
consider better description for 'particles', suggest the requester to use this category.
Jakob Strand - might have definitions

**Comment by Osanna123** [comment]
The requester will get back with a new request when needed
