### ISSUE TITLE
RDBES: New code 'MixHuCInd' in code type LandingCategory 

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#630]
Some countries have a mix of human consumption and industrial landings and therefore need the following code in the code type LandingCategory:

Code               Description
‘MixHuCInd’   ‘Mix of human consumption and industrial landing in unknown proportions.’

Cheers

**Comment by MariaMakri** [comment]
https://vocab.ices.dk/?codetypeguid=4b4e2987-0867-4ec4-82f3-2cde4f7bcb5b

**Comment by MariaMakri** [comment]
@MariaMakri to ask Henrik whether other options other than Human consumption and Industrial might occur, otherwise we can use the code 'Mix'

**Comment by MariaMakri** [comment]
RMG discussed  that the code should be 'HuCInd', thus a combination of the other two codes, removing the 'Mix' for simplicity.

**Comment by HenrikK-N** [comment]
Hi RMG. I will talk with the Core Group and return.

**Comment by HenrikK-N** [comment]
The Core Group reply: To be explicit regarding what the code for mix covers, it is only be a ‘Mix of human consumption and industrial landing’. Mix may change over time and therefore it make sense to specify what the mix covers ‘MixHuCInd’.

**Comment by MariaMakri** [comment]
I will be joining the RDBES core group on Wednesday to suggest the code 'HuCInd' instead of 'MixHuCInd'.

**Comment by MariaMakri** [comment]
The code HuCInd was added in RECO.
