### ISSUE TITLE
RDBES: MetierLevel6 new codes

### ISSUE THREAD

**Issue by MariaMakri** [ices-eg/DIG#634]
Norway requested from the RCG ISSG for metiers two new codes, that got accepted, so now they asked us to add them in RECO: 

RCG    Metier level 6 code 	Description 	
LDF	   OTM_CRU_>0_0_0	Midwater otter trawl, Crustaceans, see the code reg. mesh size and selectivity device	
LDF	   OTM_CRU_16-31_0_0	Midwater otter trawl, Crustaceans, see the code reg. mesh size and selectivity device

**Comment by pcrjoana** [comment]
@MariaMakri did you add these to RECO? If yes please close the issue.

**Comment by MariaMakri** [comment]
The two metiers have been created.
