### ISSUE TITLE
DepthRange vocab for VMS

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#636]
WGSFDGOV requested a DepthRange vocab, as they have standardizes depth ranges for data submissions.

These are the depth ranges they need:

>0m       
0-200m   
200-400m
400-600m 
600-800m
800-1000m
1000-1200m
1200-1400m
1400m+

I suggest giving numerical codes, either sequential or 0, 02, 24, 46, etc.

**Comment by odontaster** [comment]
Hi @pcrjoana . It would be good to find some reference for other depth ranges used. I can see there is one code in IC for depth ranges:
https://vocab.ices.dk/?codetypeguid=8505f028-86a3-4d03-9668-04b050706555
and it has only less or more than 500m, and that for instance would cover 2 different categories in VMS data.
We should double checkck in FDI data call and RDBES that they do not use overlapping ranges.
Also, the ranges should be like 0-200, 201-400 etc
Just some thought on this.

**Comment by neil-ices-dk** [comment]
Also check WGDEC as they use depth ranges, perhaps not as a vocab.

I think the codes need to be clearer than your initial suggestion

**Comment by neilcampbelll** [comment]
Hi all, just to confirm, there is method in the madness here. The 200m intervals down to 1400m are based on what was used in last years advice to NEAFC on OECMs, and lines up with the 400-800m band used in the VME advice, which comes from the depth at which the deep sea access regulations apply, and beyond which bottom fishing in EU waters is prohibited, and also with the 600m limit for static gears.

**Comment by pcrjoana** [comment]
Thank you for your input @odontaster, @neil-ices-dk and @neilcampbelll.

Both DATRAS and Intercatch have depth vocabs, but neither of those fit. VME doesn't have any depth vocab. 
I'm happy to have clearer codes and to have it 0-200; 201-400.
Should we have the codes as "0-200"; "201-400", etc and the descriptions as "sample depth between 0 and 200 m", etc? I just want to avoid having the same code and description.

**Comment by Osanna123** [comment]
Hi @pcrjoana, I wonder if WGSFDGOV would mind against the A,B,C-codes?
Also, it might feel a tad more fair to all categories to keep zeroes on the start number, so 0-199, 200-399, 400-599...

**Comment by neilcampbelll** [comment]
It might be best to use a categorical A, B, C, etc. The polygons are the area between, for example, the 200m and 400m isobaths, so saying a band starts at X01m or finishes at X99m isn't quite right. In cases where a point is exactly on a line i.e. a "true" X00m, will depend on the software they submitter are using, but if they're following the workflow and using R, the default is to assign based on polygon order in the shapefile when it is loaded. I have them arranged shallow to deep, so I think it would assign to the shallower side, in which case the correct way of terming it would be ">X00m - Y00m". It might just be a lot clearer to use a letter and explain what it means in the description.

**Comment by pcrjoana** [comment]
This would work @neilcampbelll!
What do you all think, @neil-ices-dk, @odontaster, @Osanna123?

**Comment by neil-ices-dk** [comment]
it's fine, it reminds me of the old days though when codes were defined based on what a computer could handle in terms of memory - i thought we'd gotten over that 😁

**Comment by neilcampbelll** [comment]
great - I will update the shapefile and upload to the workflow github

**Comment by pcrjoana** [comment]
Implemented
