### ISSUE TITLE
RDBES: Add code 'NotApplicable' to code type 'DurationSource'

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#639]
In some cases the field FOdurationSource, which uses 'DurationSource' codes is not applicable, therefore please add
the following code to to code type 'DurationSource':

Code                    Description
'NotApplicable'   'NotApplicable'

Cheers

**Comment by pcrjoana** [comment]
Would making the field optional instead or maybe conditional mandatory be an alternative to have a code for not applicable?

**Comment by HenrikK-N** [comment]
I am glad to hear, and as a reply to Joana/RMG, we have experienced before, when fields are optional, then there is a tendency to not fill in the fields, therefore it is not a good option to turn a mandatory field into an optional field. : )

**Comment by MariaMakri** [comment]
@HenrikK-N  the code NotApplicable has been added with description 'Not applicable'
