### ISSUE TITLE
Add species to AC_SaCategory

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#64]
Species to be added to acoustic species category for surveys to be uploaded in april-may
--
Species | Acoustic | Biotic
Argentina silus | ARU | 126715
Meganyctiphanes norvegica | NKR | 110690
Benthosema glaciale | BTG | 126580
Myctophids | LXX | 125498
Stomiidae | RQX | 125604

**Comment by pcrjoana** [comment]
Please also add the missing AphiaIDs to SpecWoRMS. :-)
