### ISSUE TITLE
RDBES: New code 'HP-MIC-LM-TM' added to code type 'METOA'

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#649]
The Core Group request the following code to be added to code type 'METOA':
Code                      Description
HP-MIC-LM-TM   Histological processing-Microscope-based, transmitted light

**Comment by MariaMakri** [comment]
[new_METOA_request.docx](https://github.com/user-attachments/files/16499384/new_METOA_request.docx)

**Comment by MariaMakri** [comment]
https://ices.topdesk.net/tas/secure/mango/window/0?t=1722863109474

**Comment by MariaMakri** [comment]
[new_METOA_request.docx](https://github.com/user-attachments/files/16595984/new_METOA_request.docx)

**Comment by pcrjoana** [comment]
[new_METOA_request.docx](https://github.com/user-attachments/files/16596146/new_METOA_request.docx)

**Comment by pcrjoana** [comment]
The RMG proposes solving this within the format, as METOA is a method only vocabulary, and not a equipment or sample type vocabulary. BVmeasurementequipment can use the METOA vocab, though we point out that METOA is a vocab for method of analysis. SMTYP is a better vocab for samplers. There are also NERC concepts avaiable.
RMG suggests creating a field for sample, and using using BVmethod with the vocab PreparationMethod. For a detailed view on RMGs solution, please see the document in the comment above.
