### ISSUE TITLE
Add MEESO as a survey code in AC_Survey

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#65]
IMR need a seperate survey code for the MEESO project in Acoustic database.

Their reasoning:
The data are in general collected during specific mesopelagic research cruises that are not part of another time/cruise-series, so it would make sense to me to have a separate MEESO project survey code.

Resolution?
To add MEESO as a survey code in AC_Survey
The description: Ecologically and economically sustainable mesopelagic fisheries

**Comment by Osanna123** [comment]
ok, but revise the description

**Comment by cekv** [comment]
MEAS - Mesopelagic Acoustic Survey
IMEA or IMEAS - International Mesopelagic Acoustic Survey 

Will probably not active after MEESO ends (unless it is renewed in MEESO part 2 ;) )

**Comment by HjalteParner** [comment]
The MEESO code request is a way for acoustic trawl data to be tagged in the acoustic database. The data might be part of another survey or solely collected for the MEESO project. As such the MEESO code is a work around for tagging data and not a survey as such. By created a IMEAS survey you will imply it's an actual survey. Then you also need to be able to point to the survey manual, area etc. and in the end to an advice. Please reconsider you decision.

**Comment by cekv** [comment]
@HjalteParner a decision was made to change the code from IMEAS to  to MEESO and the description to "Mesopelagic Acoustic Sampling - for the MEESO project".
Please review this before we make it public
