### ISSUE TITLE
New stock codes for blue ling

### ISSUE THREAD

**Issue by Milldaz** [ices-eg/DIG#652]
At WGDEEP, based on a review by the SIMWG, it was decided to split the bli.27.nea stock.
•	Subareas 8 and 9 are removed entirely (no blue ling there)
•	Subarea 12 will move to the bli.27.5b67 stock
•	The remaining areas will form a new stock: bli.27.123a4. Note that this stock includes all of 4, not just 4.a (i.e. 4.b and 4.c have been added).

This results in two 'new' stocks, both linked to the previous bli.27.nea stock:

bli.27.123a4 - Blue ling (Molva dypterygia) in subareas 1, 2, and 4 and in Division 3.a (Northeast Arctic, North Sea, Skagerrak, and Kattegat)

bli.27.5b6712 - Blue ling (Molva dypterygia) in subareas 6–7 and 12 and in Division 5.b (Celtic Seas, Faroes grounds, and western Hatton Bank)

Can you set these up?

**Comment by MariaMakri** [comment]
@odontaster to have a chat with publications about putting the name of the area after each number in the description. Ask @Milldaz to create stocks in SID, after @odontaster puts them in RECO.

**Comment by odontaster** [comment]
From Emma Firestone: 
bli.27.5b6712: Blue ling in subareas 6, 7, and 12 and in Division 5.b (Celtic Seas, western Hatton Bank, and Faroes grounds)
bli.27.123a4 - Blue ling (Molva dypterygia) in subareas 1, 2, and 4 and in Division 3.a (Northeast Arctic, North Sea, Skagerrak, and Kattegat)

**Comment by MariaMakri** [comment]
Stocks added also in IC_stock.
