### ISSUE TITLE
Erroneous Description for CodeType: GearType

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#66]
![image](https://user-images.githubusercontent.com/23527005/111603044-3fe94200-87d4-11eb-9e60-3a8b78d5297c.png)

**Comment by Osanna123** [comment]
The description is courtesy to the creativity of the RDBES programmers.
The codetype is also mentioned in the issue #45 as a copy of the existing Metier-4 with bad description

**Comment by cekv** [comment]
I have made it "not visible" for now and this is one of the ones that will be erased or modified when I get more feedback.
