### ISSUE TITLE
ENV2024-07-26 request for a new SMTYP

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#663]
German requester:
We need a code for "WASHYDFF5 HYDROBIOS Free Flow water sampler", capacity of 5,0 l. This one is used from our data suppliers to deliver nutrient data.

**Comment by Osanna123** [comment]
https://hydrobios.de/en/product?product_id=109
requester suggests code WASHYDFF5

**Comment by pcrjoana** [comment]
Use an English based code instead.

**Comment by Osanna123** [comment]
FFWS-5
