### ISSUE TITLE
Add P01, P06, L05, L22 from NERC Vocabulary Server (NVS) to RECO as external list

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#67]
Oceanography will start to use several of the vocabulary collection from the NERC Vocabulary Server (NVS). In order to stay inline with having all vocabularies used in ICES datasets, these vocabularies should be added to RECO as well.

Currently we are definitely talking P01 - BODC Parameter Usage Vocabulary and P06 - BODC Data Storage Units + possible L05 - SeaDataNet Device Categories and L22 -  SeaVoX Device Catalogue i.e. Instruments.

**Comment by Osanna123** [comment]
ok for P06, L05, L22,
P01 needs to be a subset.
@cekv create relevant CodeTypes, Mehdi will do the rest

**Comment by neil-ices-dk** [comment]
@cekv abd @mehdiabbasi can you give a status on this please as we need to release the Ocean format in the next few weeks. Thanks

**Comment by mehdiabbasi** [comment]
@cekv pls create CodeType for this P06, L05, L22 and I will add to the list of full list sync. For P01 I don't know how we should bring a subset?

**Comment by HjalteParner** [comment]
@mehdiabbasi @cekv @neil-ices-dk - https://github.com/ices-eg/DIG/issues/113#issuecomment-861352665 to recap that a 1:1 synchronisation will be the optimal solution also for P01

**Comment by cekv** [comment]
The CodeTypes have been created, we just need to figure out the subset of P01 - what should be included.
@Osanna123, @neil-ices-dk, @pcrjoana  any suggestions?

**Comment by Osanna123** [comment]
@HjalteParner  please suggest the subset you need to start with for P01

**Comment by HjalteParner** [comment]
@Osanna123 as stated in https://github.com/ices-eg/DIG/issues/113#issuecomment-861352665 it should be 1:1 i.e. all codes

**Comment by Osanna123** [comment]
> ok for P06, L05, L22,
> P01 needs to be a subset.
> @cekv create relevant CodeTypes, Mehdi will do the rest

@HjalteParner as agreed at our focus meeting 21 days ago, P01 at ICES would be a subset with 1to1 relation to the NERC P01.

**Comment by HjalteParner** [comment]
@Osanna123 I wouldn't know how to do a subset.

**Comment by neil-ices-dk** [comment]
> 
> 
> @Osanna123 I wouldn't know how to do a subset.

ok, the P01 discussion we will have to take after the summer, if we proceed with the others that would be good progress and mean at least the new Ocean format can refer to these directly from vocab.ices.dk which is a good thing. thanks all

**Comment by mehdiabbasi** [comment]
@HjalteParner @cekv @neil-ices-dk P06, L05, L22 are now available on vocab.ices.dk as an external list

**Comment by HjalteParner** [comment]
@mehdiabbasi thank you! It seems like the code is repeated in the description. Can you please correct this?

**Comment by mehdiabbasi** [comment]
@HjalteParner thanks for spotting this. This was logic for the platform class. it is fixed now for these three code lists.

**Comment by Osanna123** [comment]
@HjalteParner do you want to join the next RMG meeting? To discuss the P01 subset.
Or is the issue resolved?

**Comment by HjalteParner** [comment]
@Osanna123  yes I can do this if you invite me to join

**Comment by odontaster** [comment]
Create **P01Excerpt** CodeType , BODC Parameter Usage Vocabulary P01 in use at ICES datasets.
This should be made invisible and notify Mehdi when its done. @Osanna123.

**Comment by Osanna123** [comment]
NH suggested P01Subset. Ok from HP

**Comment by Osanna123** [comment]
@mehdiabbasi new CodeType P01Subset is created in RECO
