### ISSUE TITLE
ICES_StockCode and Year links

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#670]
Acoustic DB added a check for StockCode and submission year and is getting lots of issues with Year 2016. I can see only a few stocks linked to that year, probably due to the change in stocks. 
I would ask RMG permission to link several old and new codes with 2016, to minimize inconsistency reports in that transition to new codes.
Ex: her-47d3

**Comment by odontaster** [comment]
Linked her-47d3 to 2016 as it was in SID 2016

**Comment by Osanna123** [comment]
@odontaster check against SAG (and SID)

**Comment by odontaster** [comment]
Linked Year 2016 with all Stock codes in SID 2016 plus those in SAG 2016 which were not in SID 2016.
