### ISSUE TITLE
Role vocab please check and update

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#672]
Please check the descriptions at https://vocab.nerc.ac.uk/collection/G04/current/

In Oceanography we are using Distributor, Custodian and Originator. Distributor is missing from the list

**Comment by pcrjoana** [comment]
This relates to issue #646. We updated the descriptions to the current descriptions to align with the data management best practices.

**Comment by HjalteParner** [comment]
@pcrjoana the descriptions in vocab.ices.dk are not the same as in the ICES handbook, and furthermore the descriptions in the handbook are not the same as in the ISO standard where this vocabulary originate from and which also is being used in the NERC vocabulary, which we use as the external link i.e. https://vocab.nerc.ac.uk/collection/G04/current/

**Comment by pcrjoana** [comment]
Aren't they the same as in the handbook?? The owner description was incomplete in our vocab, but I fixed that. It'll be visible tomorrow.
In any case, we'll discuss this on Tuesday.

From the handbook:
![Image](https://github.com/user-attachments/assets/cdebb321-5a24-456a-b8cc-38b70e1af35f)

**Comment by Osanna123** [comment]
https://vocab.ices.dk/?codetypeguid=82ad7124-5482-4319-8870-bc97293dafca link to role vocab

**Comment by Osanna123** [comment]
make the Distributor visible
In the Long Description mention the Handbook #646

**Comment by Osanna123** [comment]
Look at the mapping of our vocab with the NERC one

**Comment by HjalteParner** [comment]
@Osanna123 could you please make the distributor visiblea? I'm not able to use this vocabulary without for oceanographic data submission.

Btw can you please explain why the long description in the Hanbook doesn't follow the ISO standard. Why do we need to divert and why do we need to intepretate the ISO standard description?

**Comment by pcrjoana** [comment]
@HjalteParner The codetype was reviewed by DIG and the terms are based on several international standards, including ISO. Distributor is now visible. I'm sorry for the delay on this.
