### ISSUE TITLE
RDBES user request to reuse existing vocabularies

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#68]
Background: due to a vocab request by WGBIOP, Julie Davies contacted other working groups which also use the vocabs in WGBIOP's request. 

Following Julie's contact, David Curie answered with the following:

Hi Julie,

We have a discussion open in the RDBES about whether we could use the SampleType https://vocab.ices.dk/?ref=1507 instead of RS_MethodForMeasurement https://vocab.ices.dk/?ref=1643 
(GitHub issue link https://github.com/ices-tools-dev/RDBES/issues/86 )

This would be used in our biological parameters table which will be recording data on parameters in addition to age (e.g. length, weight, sex, maturity).  Would it be possible to add extra values to the SampleType list that could relate to these other parameters but not be relevant for ageing?  

Thanks,
Dave

It's relevant that we discuss using existing vocabularies in the RDBES, since this is the second submitter who has brought an issue of this nature up.

@Henrik do you want to join our meeting on 7 April?

**Comment by henrik** [comment]
Wrong Henrik.

**Comment by Osanna123** [comment]
our apologies @henrik , the invite is sent out to the correct @HenrikK-N

**Comment by Osanna123** [comment]
@davidcurrie2001 @HenrikK-N 
There is no problem to use the SampleType, and Julie has confirmed that the additional values can be added. So we can implement this change in the Vocab, and the RDBES team would need to update their references.
Can you provide a definitive list of the proposed additions?

**Comment by Osanna123** [comment]
This task has evolved into development of the RMG best practices.
