### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#687]
### Please fill in all relevant information:
***Check which applies***
- [ ] ACOM has approved (only relevant when creating new stock codes)
- [ ] It is an existing code where the description needs modification
- [ ] A new stock code that needs to be created 
- [ ] It is an existing code where the description needs modification
- [ ] It is an existing stock code that needs to be split into 2 or more components 

### *The contact Professional Officer for the request*

When the Reference Management Group (RMG) receives the request, it will be reviewed and accepted or denied depending on the information given in this template. 

***Checklist for RMG***
- [ ] The request has been accepted
- [ ] The request has been denied
- [ ] The new stock code is created
- [ ] The stock description has been changed
- [ ] The old stock has been deprecated, and reference made to the new stock code(s)

### The background of the denial of a request from the RMG

If the request is accepted the stock code will be created by the relevant data manager in the vocabulary, whereafter the Professional Officer needs to create a stock list record in SID by linking the stock code to the year(s) for which it is valid.

**Comment by odontaster** [comment]
@Osanna123 , @MariaMakri , @cekv here is my go to it. Disregard formatting. Thanks

**Comment by MariaMakri** [comment]
@MariaMakri Remove 'The reason for this request' 
Change the 'Please select the most relevant case' to 'Please select one of the following cases'

**Comment by Osanna123** [comment]
@cekv @odontaster @MariaMakri @pcrjoana above is the version from me. The RMG part is changed a lot, as the previous steps looked more like a DM's procedure than an actual check-list for the request. 
Still, I feel that the 'Request processed by the RMG' is normally covered by our labels (i.e. approvedAsIs, rejected, etc), so not sure if it's redundant and should be removed.
