### ISSUE TITLE
New stock codes for Platichthys genus, Icelandic Wolffish and Plaice.

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#69]
Adriana was told it was BWQ, last year (may 2020)
New list has it as BZQ

Already in, ICES stock, IC_Stock, Spec ASFIS and Spec Worms

**Comment by cekv** [comment]
Advice wants to have the codes changed in RECO for the Platichthys genus, before advice is published.
bzq.27.2628 and bzq.27.2425


Also, two new stock codes for Atlantic wolffish and Plaice in Icelandic waters (caa.27.5a and ple.27.5a respecively) needt to be added, but more on this later after WGDEEP meeting.

**Comment by pcrjoana** [comment]
Changing the code has implications beyond Intercatch, as it also affects SID and SAG. Before a decision is made, we need to have a meeting with @mikeydrew, @cmspinto, @Milldaz, @HenrikK-N, and @RuthFG.

**Comment by RuthFG** [comment]
Joana, please send an invitation. The advie for the baltic flounder will be published at the end of next month so we should start moving things.

**Comment by neil-ices-dk** [comment]
### Conclusion
data have been delivered in the incorrect code, and advice/stock graphs have been published and DOI'd with the incorrect (BWQ) reference. These cannot be simply replaced by the new code, so we will need to deprecate (make it invalid but not delete) and then create new code and make linkages

### Actions
stock defintions codes: [stock defintions codes](http://vocab.ices.dk/?ref=357)
InterCatch stock codes: [InterCatch stock codes](http://vocab.ices.dk/?ref=260) 

BWQ will be **deprecated** in vocab.ices.dk
BZQ will be created in vocab.ices.dk and linked as "same as" to BWQ

@HenrikK-N InterCatch: new code will be used; existing BWQ will remain; will need to have a check for deprecated flag against BWQ to ensure no new data are delivered using this code; 
@mikeydrew In SID, 2020 will remain against old label BWQ and for 2021 will be updated to new id (BZQ)
@cmspinto SAG: link the old code instance to the new instance (BWQ -> BZQ)

**Comment by cekv** [comment]
> Also, two new stock codes for Atlantic wolffish and Plaice in Icelandic waters (caa.27.5a and ple.27.5a respecively) needt to be added, but more on this later after WGDEEP meeting.

@Milldaz can you confirm that WGDEEP agreed that these two stocks need to be implemented?

**Comment by Milldaz** [comment]
Hi,

I can confirm that Iceland will be specifically requesting work for these stocks in the coming years (wolffish in WGDEEP and plaice in NWWG) so they both have to be added to our vocab/SID/etc. In future I will be dealing with wolffish and Ruth will be dealing with the plaice, so you can contact us if you have questions setting them up.

Cheers,
David

**Comment by RuthFG** [comment]
Hello, What is the status of this issue? I need to send the draft advice for the stocks BZQ.27.2425 and BZQ.27.2628 to ACOM for review by Wednesday 19th and I woudl like to use the NEW stock codes. Is it all set? Thanks

**Comment by cekv** [comment]
@RuthFG I set the new codes up in RECO - with the new bzq, with a comment on it being related to bwq in the long description- and deprecating the bwq. We have not done anything with InterCatch yet, that will happen later.

**Comment by cekv** [comment]
@Milldaz I have set up the stock codes for Atlantic wolffish and Plaice in Icelandic waters in RECO.

**Comment by Milldaz** [comment]
@cekv I can only see a North Sea wolffish stock in RECO: 
caa.27.3a47de | Atlantic wolffish (Anarhichas lupus) in in Subarea 4 and divisions 3.a, 7d-e (North Sea, Skagerrak and Kattegat, English Channel)

I also can't find a plaice stock in 5a.

**Comment by pcrjoana** [comment]
@Milldaz RECO synchs overnight. The changes should be visible tomorrow.

**Comment by mikeydrew** [comment]
BZQ codes are now added in SID for 2021 -> 

![image](https://user-images.githubusercontent.com/10516840/118604498-8992e080-b7b5-11eb-816f-238e752bbcd1.png)

New stock codes are available; records can be added through the new stock menu option ->

![image](https://user-images.githubusercontent.com/10516840/118605149-3d946b80-b7b6-11eb-90eb-6f365a16ece6.png)

![image](https://user-images.githubusercontent.com/10516840/118605268-5c92fd80-b7b6-11eb-8c20-43a2e6a8b7ce.png)
