### ISSUE TITLE
ROLE vocab - proposed changes and additions

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#691]
Hi RMG,

DIG have now reviewed the terminology and have proposed the below which makes good sense. Please review as per normal RMG process.

https://vocab.ices.dk/?codetypeguid=82ad7124-5482-4319-8870-bc97293dafca

Thanks, Neil

We had a meeting on 9/10/24, looked through the different terms and agreed to update the ICES Code list first.  Once this is done we'll then update the Data Policy and Handbook in line with the terms.

We decided to base the definitions on MEDIN/ISO/Inspire with some small editorial changes.  We decided not to use the full set of terms available since this might confuse users - we kept the following sub-set:

|Term	|Description	|Long Description|
-----------|----------------|-------------------|
|Data Custodian|Person or organisation that accepts accountability and responsibility for the data and ensures appropriate care and maintenance of the resource.	|Person or organisation that accepts accountability and responsibility for the data and ensures appropriate care and maintenance of the resource. **The custodian also ensures access to the resource.**||
|Data Originator|Person or organisation who created the resource.|Person or organisation who created the resource.|
|Data Owner|Person or organisation that owns the resource.|Person or organisation that owns the resource.|
|Data Provider|Person or organisation that provides the resource.|Person or organisation that provides the resource.|
|Data Publisher|Person or organisation who publishes the resource.|Person or organisation who publishes the resource.|
|Data User|Person or organisation who uses the resource.|Person or organisation who uses the resource.|
|Data Steward|exactMatch Data Custodian||	
|Data Resource Provider|exactMatch Data Provider||

_Originally posted by @davidcurrie2001 in https://github.com/ices-eg/DIG/issues/527#issuecomment-2401911129_

**Comment by neil-ices-dk** [comment]
for reference, the evaluation that led to the synthesis table 
https://community.ices.dk/Committees/DIG/Master%20documents/Data-Policy-and-licences/DefinitionCheck_2024/DataPolicy_Definitions_20241009.xlsx

**Comment by MariaMakri** [comment]
Code type description: Function performed by the responsible party for the resource. 

Long description: Reviewed and approved by DIG in 2024 based on international standards.
