### ISSUE TITLE
ShinyApp: NEAFC Catch Explorer 

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/DIG#692]
Checklist against https://doi.org/10.17895/ices.pub.22695898.v1

### Step 1 licensing
App is open, and data are anonymised: complies with CC BY 4.0
Code has CC0 license
https://github.com/ices-tools-prod/NEAFC_Spatial_Catch_Explorer

### Step 2 Data Profile
Initial profiling done, which sparked the process to bring up to standard described in ShinyApp guidance

### Step 3 Ownership
Defined in Meta data record
2 year product (maximum allowed)
no dependencies

-----------------------

### Step 4 ACOM approval
This app is part of the advice request: 
ICES (2024). NEAFC request on discarding in the NEAFC regulatory areas. ICES Advice: Special Requests. Report. https://doi.org/10.17895/ices.advice.26947132.v1

----------------------
### Post approval: Step 1 code published
Published https://github.com/ices-tools-prod/NEAFC_Spatial_Catch_Explorer

### Post approval: Step 2 metadata
drafted, needs a small adjustment @colinpmillar and then can be pushed to Periklis for approval

### Post approval: Step 3 ICES website anchor
https://www.ices.dk/advice/NEAFC-catch-explorer/Pages/NEAFC%20catch%20explorer.aspx 
- remove menu item on top advice menu (Neil)
- redo the text (Cecilia)
- add link to DOI of advice https://doi.org/10.17895/ices.advice.26947132.v1
- add link to meta data record

### Post approval: Step 4 test and review
@colinpmillar has reviewed the code and tested
@neilcampbelll to change the 3 species codes to descriptive names/reference vocab
@neilcampbelll to add link back from app (https://ices-taf.shinyapps.io/neafc-catch-explorer/) to the landing page on ICES sharepoint website https://www.ices.dk/advice/NEAFC-catch-explorer/Pages/NEAFC%20catch%20explorer.aspx

**Comment by neil-ices-dk** [comment]
@neilcampbelll are the loose ends addressed, can you confirm and close ticket if all is squared away - thanks

**Comment by neil-ices-dk** [comment]
@neilcampbelll the species codes need updating still; btw - is this working?
![image](https://github.com/user-attachments/assets/a2d09f33-cf7d-49f8-ac69-d794b6161d68)

**Comment by neil-ices-dk** [comment]
@neilcampbelll i've discussed with @colinpmillar and we agree that you need a pop-up prompting users to zoom as it is not intuitive that there are no data points rendered and you have to guess where to zoom to see the rendering of data

**Comment by neilcampbelll** [comment]
Thanks Neil - will speak to @colinpmillar when I am back in the office and make these changes next week

**Comment by neilcampbelll** [comment]
![image](https://github.com/user-attachments/assets/a5e0be5c-a584-4167-8ede-6a51928e573c)

Changes proposed by @neil-ices-dk  implemented.

* FAO species codes replaced with latin names from ASFIS codes in vocab
* Now defaults to herring/mackerel or cod in two/single species view, rather than the first in alphabetical order
* Text to prompt zooming added along with buttons to focus on RAs 1 - 3
*  Link back to landing page added, along with recommended citation.

@colinpmillar do you need to work some magic at your end?

**Comment by neilcampbelll** [comment]
![image](https://github.com/user-attachments/assets/934b808d-bbd2-4470-aadd-05590af932e3)

**Comment by neil-ices-dk** [comment]
@neilcampbelll @colinpmillar  the Geonetwork meta data record is not published nor linked to the landing page. Is the meta data record complete and up-to-date?

Can you check and inform @PeriklisICES if it can be published, thanks

**Comment by colinpmillar** [comment]
[like]  Colin Millar reacted to your message:
________________________________

**Comment by colinpmillar** [comment]
Metadata fixed and
@PeriklisICES published the metadata record

**Comment by neil-ices-dk** [comment]
thank you, now linked on anchor page on ices.dk
