### ISSUE TITLE
New stock: her.27.7ef

### ISSUE THREAD

**Issue by sarahlmillar** [ices-eg/DIG#693]
We have been asked to provide advice in 2025 for herring in 7ef.
There was a workshop in December 2024 to agree stock definition: https://ices-library.figshare.com/articles/report/Workshop_on_a_Research_Roadmap_for_Bristol_and_Western_Channel_Herring_WKRRBWCH_outputs_from_2023_meeting_/25868119?file=46479811
This was posted to ACOM for approval this year, and received it.

HAWG would like to start working on this stock now.

Proposed stock name: Her.27.7ef, Herring (Clupea harengus) in divisions 7.e–f (western English Channel and Bristol Channel).
Area definition: Western English Channel (ICES Division 7.e) and Bristol Channel (ICES Division 7.f).

**Comment by odontaster** [comment]
asked editorial office for review

**Comment by odontaster** [comment]
Emma Firestone replied:
We prefer "divisions 7.e and 7.f".

**Comment by MariaMakri** [comment]
Ask Sarah if this can wait to test the template. If not we can create a code. @odontaster to double check if there was a code that existed before for that stock.

**Comment by odontaster** [comment]
All set, only pending link between IC_Stock and IC_Year 2025 @MariaMakri

**Comment by odontaster** [comment]
done now
