### ISSUE TITLE
Data Portal - theme links review

### ISSUE THREAD

**Issue by pcrjoana** [ices-eg/DIG#695]
Mehdi asked to link the Biodiversity theme to an advice tag. 
https://vocab.ices.dk/?codetypeguid=c1887911-3ea7-4ad9-a844-ba989e6b5b9c
Currently it is linked to Sea birds and Marine mammals in State, but it could need more links.
https://vocab.ices.dk/?codetypeguid=6410af4e-cbf3-4770-b229-939fb763edb2

https://vocab.ices.dk/?codetypeguid=ed99774f-e15f-46d2-8220-2fe1bb30c4e9

https://vocab.ices.dk/?codetypeguid=26971431-ad56-4962-ae59-59bfb5902328

**Comment by pcrjoana** [comment]
@pcrjoana to link BD to research and tourism in humanactivity, mil, fisher, shp, power2, power1, telecom .
Link noise to  Power1, power2, SHP, aggex, mil, telecom, research.
Link all themes to research.

**Comment by Osanna123** [comment]
Add new links as follows:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/anna/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/anna/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Theme | Human   Activity | Pressures | State
-- | -- | -- | --
AS |   |   | Food, PHab
BD |   |   |  
BIO |   | NOE | Food
BM | RES |   | Fish,Phab,Bhab
CAT | RECR, consider COLL |   | all
CON |   |   | Fish
FTS |   |   | Food,Phab
ICS |   | SES | Food
ML | RES |   | BHAB
NOISE |   |   |  
OCEAN |   | NOE | BHAB
SA | RES |   | Fish
SD | Fisher |   |  
VME |   |   |  



</body>

</html>

**Comment by Osanna123** [comment]
done collectively by the RMG
