### ISSUE TITLE
herring.27.7ef [11.11.2024, herring, 7 e and 7f]

### ISSUE THREAD

**Issue by sarahlmillar** [ices-eg/DIG#697]
## 1. Please select **only one** of the following cases:

- [x] A new stock code needs to be created (not linked to any existing stock).
- [ ] An existing stock code needs to be split into 2 or more components.
- [ ] Two (or more) existing stock codes need to be merged into a single stock.
- [ ] One or more existing stocks need to be modified.

## **2. Please Provide information regarding the request below:** 

__*List the previously existing code(s) and description(s), if applicable:*__

__*Describe your request in detail, with the new/updated stock code(s) and description(s), and the proposed changes:*__
New stock, agreed at the WKRRBWCH meeting. Requested by EU/UK for 2025 in the GAs.
Report approved by HAWG and ACOM this year. See ACOM forum post here:
https://community.ices.dk/Committees/ACOMForum/Lists/Posts/Post.aspx?ID=1448

Proposed stock name: Her.27.7ef, Herring (Clupea harengus) in divisions 7.e and 7.f (western English Channel and Bristol Channel).
Area definition: Western English Channel (ICES Division 7.e) and Bristol Channel (ICES Division 7.f).

__*Which Benchmark, Expert Group or Workshop has requested a new stock code?*__
(Link to the report and section within it if relevant)
HAWG
https://ices-library.figshare.com/articles/report/Workshop_on_a_Research_Roadmap_for_Bristol_and_Western_Channel_Herring_WKRRBWCH_outputs_from_2023_meeting_/25868119?file=46479811

__*Name of the contact ICES Professional Officer for the request*__
@sarahlmillar [sarah millar]

## 3.  Please confirm:

- [x] The request has been approved by ACOM.
__*Please provide a link to the minutes, notes etc. where the approval is found.*__

- [x]  The codes and descriptions have been reviewed for grammar and style by the editorial office

### To be filled by RMG
<details>
<summary>Checklist for RMG (click arrow to expand)</summary>

- [x] Request is processed by RMG
- [ ] ICES Vocabulary updated
- [ ] The requester PO has been informed

</details>

If the request is accepted, the RMG will create the stock code in the ICES Vocabulary, whereafter the Professional Officer needs to create a stock list record in SID by linking the stock code to the year(s) that it is valid for.

**Comment by sarahlmillar** [comment]
@odontaster  @cekv  hopefully this is what you need

**Comment by odontaster** [comment]
need to create year 2025 before closing this task

**Comment by odontaster** [comment]
done now
