### ISSUE TITLE
ane.27.9a - split [21/11/24, Anchovy, 9a]

### ISSUE THREAD

**Issue by Milldaz** [ices-eg/DIG#703]
## 1. Please select **only one** of the following cases:

- [ ] A new stock code needs to be created (not linked to any existing stock).
- [x] An existing stock code needs to be split into 2 or more components.
- [ ] Two (or more) existing stock codes need to be merged into a single stock.
- [ ] One or more existing stocks need to be modified.

## **2. Please Provide information regarding the request below:** 

__*List the previously existing code(s) and description(s), if applicable:*__
Stock Code: ane.27.9a
Description: Anchovy (_Engraulis encrasicolus_) in Division 9.a (Atlantic Iberian waters)

__*Describe your request in detail, with the new/updated stock code(s) and description(s), and the proposed changes:*__
The stock is being split into Western and Southern components based on the outcomes of WKBANSP.

Proposed names and codes
Name: Anchovy (_Engraulis encrasicolus_) in Subdivision 9.a.South (Gulf of Cadiz)
Stock code: ane.27.9aS
Name: Anchovy (_Engraulis encrasicolus_) in subdivisions 9.a.North, 9.a.Central North, and 9.a.Central South (western Iberian waters)
Stock Code: ane.27.9aW
- WGHANSA 2019 TORc proposed 9.a W as an area comprising subdivisions 9.a.North, 9.a.Central North, and 9.a.Central South. If this was accepted, we can call this stock anchovy 9a W. i.e. **can we define a new super-subdivision 9.a.W?**

__*Which Benchmark, Expert Group or Workshop has requested a new stock code?*__
(Link to the report and section within it if relevant)
WGHANSA and WKBANSP

__*Name of the contact ICES Professional Officer for the request*__
David Miller and Sarah Miller (WKBANSP)

## 3.  Please confirm:

- [x] The request has been approved by ACOM.
__*Please provide a link to the minutes, notes etc. where the approval is found.*__
Final decision due early next week (but already have indications that ACOM will support it). Working group is next week, so getting an early start on this process.
https://community.ices.dk/Committees/ACOMForum/Lists/Posts/Post.aspx?Paged=TRUE&p_ID=5823&PageFirstRow=11&View=3d0aa4ff-beb5-40b3-becc-4ccf96a0f393&ID=1496

- [x]  The codes and descriptions have been reviewed for grammar and style by the editorial office

### To be filled by RMG
<details>
<summary>Checklist for RMG (click arrow to expand)</summary>

- [ ] Request is processed by RMG
- [ ] ICES Vocabulary updated
- [ ] The requester PO has been informed

</details>

If the request is accepted, the RMG will create the stock code in the ICES Vocabulary, whereafter the Professional Officer needs to create a stock list record in SID by linking the stock code to the year(s) that it is valid for.

**Comment by Milldaz** [comment]
Will have final confirmation from ACOM and editorial checks next week.

**Comment by Milldaz** [comment]
We have ACOM approval and pubs have checked the stock names. 

@odontaster when could the new codes/vocabs be ready?

**Comment by odontaster** [comment]
@Milldaz and @odontaster agreed on:

-ane.27.9.a.s: Anchovy (Engraulis encrasicolus) in the southern part of Division 9.a (Gulf of Cadiz and southern coast of Portugal)

-Create a new AreaNonFao 
https://vocab.ices.dk/?codetypeguid=d94d4dca-c8d1-40ea-8b82-ff93ae3a7dcf
27.9.a.w: Division 9.a between  43º 00 ‘ N and an oblique line from (37°01.8’N, 9°00’W) to (36° 48.3’N, 9°16.9’W).

-ane.27.9.a.w: Anchovy (Engraulis encrasicolus) in the western part of Division 9.a.

**Comment by odontaster** [comment]
Implemented in ICES_StockCode.
Pending in IC_Stock

**Comment by odontaster** [comment]
Implemented in IC_Stock
