### ISSUE TITLE
Making 'data types' mandatory for stations

### ISSUE THREAD

**Issue by HansMJ** [ices-eg/DIG#704]
Stations are used to group data together for OSPAR, HELCOM and AMAP hazardous substances assessments. Data type is used in for the matching of stations with data and data series might fall out of assessment if the station 'data type' do match with data. Because station 'data type' is critical in the assessment processing, perhaps it should be **mandatory to have at least one 'data type' added for a station?**

This was suggested by Germany that finds it 'strange' using an optional field to decide to take data for an assessment or not (only station matched data are used in the OSPAR MIME assessment)

**Comment by Osanna123** [comment]
Respective task is created in Stations section in DevOps
