### ISSUE TITLE
Citation of ICES vocabs

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#707]
Already raised by Gwen when reviewing the Reference Management Best Practices document but reminded in several instances.

**Comment by odontaster** [comment]
linked to #702

**Comment by odontaster** [comment]
Use standard citation format for Data Portals, and add part for specific CodeType, URL

ICES Vocabulary Server. [Date Accessed]. ICES, Copenhagen, Denmark. https://vocab.ices.dk/

ICES Vocabulary Server, [CodeType]. [Date Accessed]. ICES, Copenhagen, Denmark. [Link to CodeType]

**Comment by Osanna123** [comment]
Added to the https://www.ices.dk/data/tools/Pages/code-request.aspx
