### ISSUE TITLE
Surveys: error in descriptions

### ISSUE THREAD

**Issue by odontaster** [ices-eg/DIG#712]
For the BITS cruises, the vocab description is wrong, as the relevant cruise codes for BITS is described as an Acoustic survey, and not bottom trawl survey.

 
![Image](https://github.com/user-attachments/assets/49d8edda-b688-44d3-857c-5f65d6873e61)

**Comment by cekv** [comment]
@odontaster, thanks for noticing, probably a copy-paste error :)
