### ISSUE TITLE
Monitoring method

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/DIG#72]
Monitoring method: need to add a “self-sampling/reporting” option to the vocabulary

Reason: last year due to the pandemic, many surveys were not able to be conducted with a observer on board, so it was requested to the fishermen to do the bycatch monitoring themselves.

**Comment by pcrjoana** [comment]
@cmspinto can you fill the request form, please? https://forms.office.com/Pages/ResponsePage.aspx?id=ziCy4DVXaESR3wXK5f8f3BWA1fNSx4tPsQVXsp2REGRUQkZWSTBTVVZDVVVSWUxMNVBXSkUxSk1NWCQlQCN0PWcu
We'll then discuss this at the next meeting. :-)

**Comment by Osanna123** [comment]
https://vocab.ices.dk/?ref=1533
Suggested description: Vessel crew observer

**Comment by pcrjoana** [comment]
Because the link to the codetype was not in the issue already, this is it: http://vocab.ices.dk/?ref=1533
