### ISSUE TITLE
Two new stock codes for split cod stock (cod.27.1-2coast)

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#73]
During a benchmark this year, one of the stocks was split into two separate stocks: cod.27.1-2coast Cod (Gadus morhua) in subareas 1 and 2 (Norwegian coastal waters cod).

It is now split in two north and south of 67°N. 
The proposed names for the new stocks are:
cod.27.1-2.coastN :  Cod (Gadus morhua) in subareas 1 and 2 North of 67°N (Norwegian coastal cod North)
cod.27.2.coastS:  Cod (Gadus morhua) in Subarea 2 between 62°N and 67°N (Norwegian coastal cod South)

Thanks,
David

**Comment by Osanna123** [comment]
Please try to include the area definitions to the description, as for other stocks.

**Comment by pcrjoana** [comment]
Comment by David Miller:
"It does however seem that the descriptions are different in SID compared to the vocabulary"

@mikeydrew can you double check all the stock descriptions in SID against the descriptions in vocab, please?

**Comment by pcrjoana** [comment]
@mikeydrew  @Milldaz would like to have this speeded up, because of a WG meeting next week. Can you prioritise this issue, please?

**Comment by mikeydrew** [comment]
@pcrjoana code descriptions are now in sync ->
![image](https://user-images.githubusercontent.com/10516840/116864181-bcf73c00-ac07-11eb-8085-cebdec43b902.png)

**Comment by Milldaz** [comment]
Thanks for sorting this out!
