### ISSUE TITLE
Change the visibility of DP_ vocabs

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#74]
Should the DP_ vocabs be made visible (for presentation at DIG and for DP-users)?

![image](https://user-images.githubusercontent.com/17157764/115388870-b49d0b00-a1dc-11eb-902f-0d3422476e52.png)

**Comment by Osanna123** [comment]
@mehdiabbasi, Could you please explain the use case for visibility of label code types?
@pcrjoana, reinvent the descriptions for the CodeTypes
Remove the DP_ prefix

**Comment by mehdiabbasi** [comment]
@Osanna123  These code types have been used in dataportal and we are going to use them in Vocab web as an official theme. By making them visible users can see the list of thems and relation to the datasets and topics

**Comment by mehdiabbasi** [comment]
@Osanna123 if you decide to remove Dp_ prefix, please notify me.

**Comment by neil-ices-dk** [comment]
@martinezinigo you mentioned changes to ecosystem overview categorisations, do you have an updated list you can share with us please

**Comment by martinezinigo** [comment]
[ICES technical guidelines on ecosystem overviews_20021.docx](https://github.com/ices-eg/DIG/files/6398237/ICES.technical.guidelines.on.ecosystem.overviews_20021.docx)

yes i am sharing the new EOs guidelines above. On the document you can find list and definition for:

- Table A1        Glossary of main human activities in ICES ecoregions
- Table A2	Glossary of main human pressures in ICES ecoregions
- Table A3	Glossary of core ecosystem state components. 

thank you for follow up on this,
i.

**Comment by cekv** [comment]
@pcrjoana please implement changes and revise the EO categories.
@mehdiabbasi

**Comment by pcrjoana** [comment]
The changes to the code types and titles are implemented, but we need to agree within the management group how to implement the new EO categories, as it is not very straightforward.
This should be a priority issue for this week, as it would be good to have the changes implemented before DIG.

**Comment by pcrjoana** [comment]
Actually a non-problem. Some information went unseen by me. To be implemented before DIG.

**Comment by pcrjoana** [comment]
The changes have been implemented in RECO. Not all EO categories were added, as it was agreed with Mehdi some time ago that we'd add as needed. 
Some descriptions and codes had to be changed, to accommodate the changes to EO. 
The name of the codetypes was also changes, as suggested by @Osanna123 in the last RMG meeting.

**Comment by neil-ices-dk** [comment]
@HjalteParner please indicate any additional relations that you think should be implemented thanks

**Comment by Osanna123** [comment]
> @HjalteParner please indicate any additional relations that you think should be implemented thanks

We want to close this issue. Please comment.

**Comment by pcrjoana** [comment]
Have we gotten a comment back from @HjalteParner? Can we close this issue?
