### ISSUE TITLE
ICES Statistical rectangles missing and some are wrong

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/DIG#76]
I have been receiving complains from people that screen the VMS files that there are rectangles missing. 
I have just checked it with a simple quesry and it looks like this needs a look.

There are 1418 Statistical rectangles missing and 401 that are in the list but do not exist,

here is the list of rectangles that are not in the list: 

Statistical Rectangle:
01E5
01E6
01E7
01E8
01E9
01F0
01F1
01G0
01G1
01G2
01G3
01G4
01G5
01G6
01G7
01G8
01G9
01H0
01H1
01H2
01H3
01H4
01H5
01H6
01H7
01H8
01H9
01J0
01J1
01J2
01J3
01J4
01J5
01J6
02E5
02E6
02E7
02E8
02G0
02G1
02G2
02G3
02G4
02G5
02G6
02G7
02G8
02G9
02H0
02H1
02H2
02H3
02H4
02H5
02H6
02H7
02H8
02H9
02J0
02J1
02J2
02J4
02J5
02J6
03E8
03G0
03G1
03G2
03G3
03G4
03G5
03G6
03G7
03G8
03G9
03H0
03H1
03H2
03H3
03H4
03H5
03H6
03H7
03H8
04E8
04E9
04G0
04G1
04G2
04G3
04G5
04G6
04G7
04G8
04G9
04H0
04H1
04H2
04H3
04H4
04H5
04H6
04H7
05E9
05G0
05G1
05G2
05G3
05G4
05G5
05G6
05G7
05G8
05G9
05H0
05H1
05H2
05H3
05H4
05H5
05H6
05H7
06E1
06E9
06F0
06F1
06F8
06F9
06G0
06G1
06G2
06G3
06G4
06G5
06G6
06G7
06G8
06G9
06H0
06H1
06H2
06H3
06H4
06H5
06H6
06H7
07E9
07F1
07F2
07F3
07F8
07F9
07G0
07G1
07G2
07G3
07G4
07G5
07G6
07G7
07G8
07G9
07H0
07H1
07H2
07H3
07H4
07H5
07H6
08E9
08F0
08F2
08F3
08F4
08F8
08F9
08G0
08G1
08G2
08G3
08G4
08G5
08G6
08G7
08G8
08G9
08H0
08H2
08H3
08H4
08H5
08H6
09F0
09F1
09F2
09F3
09F4
09F5
09F6
09F7
09F8
09F9
09G0
09G1
09G2
09G3
09G4
09G5
09G6
09G7
09G8
09G9
09H2
09H3
09H4
09H5
09H6
09H7
09H8
09H9
10F0
10F8
10F9
10G0
10G1
10G2
10G3
10G4
10G7
10G8
10G9
10H2
10H3
10H4
10H5
10H6
10H7
10H8
10H9
10J7
10J8
10J9
10K0
11F0
11F1
11F2
11F8
11F9
11G0
11G1
11G2
11G3
11G5
11G6
11G7
11G8
11G9
11H5
11H7
11H8
11H9
11J0
11J1
11J6
11J7
11J8
11J9
11K0
11K1
12F2
12F3
12F8
12F9
12G0
12G1
12G2
12G6
12G7
12G8
12G9
12H7
12H8
12H9
12J0
12J1
12J2
12J3
12J4
12J5
12J6
12J7
12J8
12J9
12K0
12K1
13F3
13F8
13F9
13G0
13G1
13G6
13G7
13G8
13G9
13H7
13H8
13H9
13J0
13J1
13J2
13J3
13J4
13J5
13J6
13J7
13J8
13J9
13K0
13K1
14F2
14F3
14F6
14F8
14F9
14G0
14G1
14G5
14G6
14G7
14G8
14H7
14H8
14H9
14J0
14J1
14J2
14J3
14J4
14J5
14J6
14J7
14J8
14J9
14K0
14K1
15F3
15F4
15F5
15F6
15F9
15G0
15G5
15G6
15G7
15H7
15H8
15H9
15J0
15J1
15J2
15J3
15J4
15J5
15J6
15J7
15J8
15J9
15K0
16F3
16F4
16F6
16F7
16F8
16G0
16G5
16G6
16H8
16H9
16J0
16J1
16J2
16J3
16J4
16J5
16J6
16J7
16J8
16J9
17F8
17F9
17G0
17G5
17H8
17H9
17J0
17J1
17J2
17J3
17J4
17J5
17J6
17J7
17J8
17J9
18E2
18G4
18G5
18H8
18H9
18J0
18J1
18J2
18J3
18J4
18J5
18J6
18J7
18J8
19G4
19H8
19H9
19J0
19J1
19J2
19J3
19J4
19J5
19J6
19J7
20G2
20H9
20J0
20J1
20J2
20J3
20J4
20J5
20J6
20J7
20J8
21J0
21J1
21J2
21J3
21J4
21J5
21J6
21J7
21J8
22J0
22J1
22J2
22J5
22J6
22J7
22J8
22J9
23J7
23J8
23J9
25E7
31D7
34E9
36G3
42H3
55G7
59C9
60C9
60D0
60D1
60D2
60K4
61C9
61D0
61D1
61D2
61D3
62C9
62D0
62D1
62D2
62D3
63J1
66J3
67C4
67C5
67C6
67C7
67C8
67C9
90C5
90C6
90C8
90C9
90D0
90D1
90D2
90D3
90D4
90D5
90D6
90D7
90D8
90D9
90E0
90E1
90E2
90E3
90E4
90E5
90E6
90E7
90E8
90E9
90F0
90F1
90F2
90F3
90F4
90F5
90F6
90F7
90F8
90F9
90G0
90G1
90G2
90G3
90G4
90G5
90G6
90G7
90G8
90G9
90H0
90H1
90H2
90H3
90H4
90H5
90H6
90H7
90H8
90H9
90J0
90J1
90J2
90J3
90J4
90J5
90J6
90J7
90J8
90J9
90K0
90K1
90K2
90K3
90K4
90K5
90K6
90K7
90K8
90K9
90L0
90L1
90L2
90L3
90L4
90L5
90L6
90L7
90L8
90L9
90M0
90M1
90M2
90M3
90M4
90M5
90M6
90M7
90M8
91C1
91C2
91C6
91C7
91C8
91C9
91D0
91D1
91D4
91D5
91D6
91D7
91D8
91D9
91E0
91E1
91E2
91E3
91E4
91E5
91E6
91E7
91E8
91E9
91F0
91F1
91F2
91F3
91F4
91F5
91F6
91F7
91F8
91F9
91G0
91G1
91G2
91G3
91G4
91G5
91G6
91G7
91G8
91G9
91H0
91H1
91H2
91H3
91H4
91H5
91H6
91H7
91H8
91H9
91J0
91J1
91J2
91J3
91J4
91J5
91J6
91J7
91J8
91J9
91K0
91K1
91K2
91K3
91K4
91K5
91K6
91K7
91K8
91K9
91L0
91L1
91L2
91L3
91L4
91L5
91L6
91L7
91L8
91L9
91M0
91M1
91M2
91M3
91M4
91M5
91M6
91M7
91M8
92B5
92B6
92B7
92B8
92B9
92C0
92C1
92C2
92C3
92C4
92C5
92C7
92C8
92C9
92D0
92D1
92D2
92D3
92D4
92D5
92D6
92D7
92D8
92D9
92E0
92E1
92E2
92E3
92E4
92E5
92E6
92E7
92E8
92E9
92F0
92F1
92F2
92F3
92F4
92F5
92F6
92F7
92F8
92F9
92G0
92G1
92G2
92G3
92G4
92G5
92G6
92G7
92G8
92G9
92H0
92H1
92H2
92H3
92H4
92H5
92H6
92H7
92H8
92H9
92J0
92J1
92J2
92J3
92J4
92J5
92J6
92J7
92J8
92J9
92K0
92K1
92K2
92K3
92K4
92K5
92K6
92K7
92K8
92K9
92L0
92L1
92L2
92L3
92L4
92L5
92L6
92L7
92L8
92L9
92M0
92M1
92M2
92M3
92M4
92M5
92M6
92M7
92M8
93B7
93B8
93B9
93C0
93C1
93C2
93C3
93C4
93C5
93C6
93C7
93C8
93C9
93D0
93D1
93D2
93D3
93D4
93D5
93D6
93D7
93D8
93D9
93E0
93E1
93E2
93E3
93E4
93E5
93E6
93E7
93E8
93E9
93F0
93F1
93F2
93F3
93F4
93F5
93F6
93F7
93F8
93F9
93G0
93G1
93G2
93G3
93G4
93G5
93G6
93G7
93G8
93G9
93H0
93H1
93H2
93H3
93H4
93H5
93H6
93H7
93H8
93H9
93J0
93J1
93J2
93J3
93J4
93J5
93J6
93J7
93J8
93J9
93K0
93K1
93K2
93K3
93K4
93K5
93K6
93K7
93K8
93K9
93L0
93L1
93L2
93L3
93L4
93L5
93L6
93L7
93L8
93L9
93M0
93M1
93M2
93M3
93M4
93M5
93M6
93M7
93M8
94B0
94B1
94B3
94B4
94B5
94B6
94C3
94C4
94C5
94C6
94C7
94C8
94C9
94D0
94D1
94D2
94D3
94D4
94D5
94D6
94D7
94D8
94D9
94E0
94E1
94E2
94E3
94E4
94E5
94E6
94E7
94E8
94E9
94F0
94F1
94F2
94F3
94F4
94F5
94F6
94F7
94F8
94F9
94G0
94G1
94G2
94G3
94G4
94G5
94G6
94G7
94G8
94G9
94H0
94H1
94H2
94H3
94H4
94H5
94H6
94H7
94H8
94H9
94J0
94J1
94J2
94J3
94J4
94J5
94J6
94J7
94J8
94J9
94K0
94K1
94K2
94K3
94K4
94K5
94K6
94K7
94K8
94K9
94L0
94L1
94L2
94L3
94L4
94L5
94L6
94L7
94L8
94L9
94M0
94M1
94M2
94M3
94M4
94M5
94M6
94M7
94M8
95B0
95B1
95B2
95B4
95B5
95B6
95B7
95B8
95B9
95C0
95C1
95C2
95C3
95C4
95C5
95C6
95C7
95C8
95C9
95D0
95D1
95D2
95D3
95D4
95D5
95D6
95D7
95D8
95D9
95E0
95E1
95E2
95E3
95E4
95E5
95E6
95E7
95E8
95E9
95F0
95F1
95F2
95F3
95F4
95F5
95F6
95F7
95F8
95F9
95G0
95G1
95G2
95G3
95G4
95G5
95G6
95G7
95G8
95G9
95H0
95H1
95H2
95H3
95H4
95H5
95H6
95H7
95H8
95H9
95J0
95J1
95J2
95J3
95J4
95J5
95J6
95J7
95J8
95J9
95K0
95K1
95K2
95K3
95K4
95K5
95K6
95K7
95K8
95K9
95L0
95L1
95L2
95L3
95L4
95L5
95L6
95L7
95L8
95L9
95M0
95M1
95M2
95M3
95M4
95M5
95M6
95M7
95M8
96B0
96B1
96B2
96B3
96B4
96B5
96B6
96B7
96B8
96B9
96C0
96C1
96C2
96C3
96C4
96C5
96C6
96C7
96C8
96C9
96D0
96D1
96D2
96D3
96D4
96D5
96D6
96D7
96D8
96D9
96E0
96E1
96E2
96E3
96E4
96E5
96E6
96E7
96E8
96E9
96F0
96F1
96F2
96F3
96F4
96F5
96F6
96F7
96F8
96F9
96G0
96G1
96G2
96G3
96G4
96G5
96G6
96G7
96G8
96G9
96H0
96H1
96H2
96H3
96H4
96H5
96H6
96H7
96H8
96H9
96J0
96J1
96J2
96J3
96J4
96J5
96J6
96J7
96J8
96J9
96K0
96K1
96K2
96K3
96K4
96K5
96K6
96K7
96K8
96K9
96L0
96L1
96L2
96L3
96L4
96L5
96L6
96L7
96L8
96L9
96M0
96M1
96M2
96M3
96M4
96M5
96M6
96M7
96M8
97B0
97B1
97B2
97B3
97B4
97B5
97B6
97B7
97B8
97B9
97C0
97C1
97C2
97C3
97C4
97C5
97C6
97C7
97C8
97C9
97D0
97D1
97D2
97D3
97D4
97D5
97D6
97D7
97D8
97D9
97E0
97E1
97E2
97E3
97E4
97E5
97E6
97E7
97E8
97E9
97F0
97F1
97F2
97F3
97F4
97F5
97F6
97F7
97F8
97F9
97G0
97G1
97G2
97G3
97G4
97G5
97G6
97G7
97G8
97G9
97H0
97H1
97H2
97H3
97H4
97H5
97H6
97H7
97H8
97H9
97J0
97J1
97J2
97J3
97J4
97J5
97J6
97J7
97J8
97J9
97K0
97K1
97K2
97K3
97K4
97K5
97K6
97K7
97K8
97K9
97L0
97L1
97L2
97L3
97L4
97L5
97L6
97L7
97L8
97L9
97M0
97M1
97M2
97M3
97M4
97M5
97M6
97M7
97M8
98B0
98B1
98B2
98B3
98B4
98B5
98B6
98B7
98B8
98B9
98C0
98C1
98C2
98C3
98C4
98C5
98C6
98C7
98C8
98C9
98D0
98D1
98D2
98D3
98D4
98D5
98D6
98D7
98D8
98D9
98E0
98E1
98E2
98E3
98E4
98E5
98E6
98E7
98E8
98E9
98F0
98F1
98F2
98F3
98F4
98F5
98F6
98F7
98F8
98F9
98G0
98G1
98G2
98G3
98G4
98G5
98G6
98G7
98G8
98G9
98H0
98H1
98H2
98H3
98H4
98H5
98H6
98H7
98H8
98H9
98J0
98J1
98J2
98J3
98J4
98J5
98J6
98J7
98J8
98J9
98K0
98K1
98K2
98K3
98K4
98K5
98K6
98K7
98K8
98K9
98L0
98L1
98L2
98L3
98L4
98L5
98L6
98L7
98L8
98L9
98M0
98M1
98M2
98M3
98M4
98M5
98M6
98M7
98M8

**Comment by Osanna123** [comment]
@cmspinto 
*ICES StatRecs are meant to be used only for the ICES areas, whereas 01E5-23J9 from the list are in Mediterranean&Black&Azov Seas. Can't they use C-square there?
*please confirm that you conceptually need the statrecs on land - perhaps river fishing and ice hunting? (25E7, 34E9, 36G3, 55G7, 60K4, 63J1, 66J3, 90C5,90C8,91C1,91C2,91C6,91D4,91D5,92B5,92B6,92C2,92C7...)
*Some of the codes you requested have already existed on the list (under investigation)
*in 2017, when we expanded the list, rim of the ICES world was at 89C7-89M8, so it is a good idea to add 90-99 statrecs now :)

**Comment by cmspinto** [comment]
I can confirm that I need the statrecs that are mostly on land, here is an example of a submitter that could not submit data in a valid Statistical Rectangle:
![image](https://user-images.githubusercontent.com/8705477/115669113-38273b00-a348-11eb-8b5d-276aeaccd0af.png)

**Comment by Osanna123** [comment]
@cmspinto it is a good idea to have two resources in sync, but ICES StatRecs are still not meant for use in the Mediterranean and Black Sea area, and unless use of other definitions (like C-squares) is impossible, should not be used there.
@cekv , could you please check if BTS-GSA17 is relying on ICES statrecs for the Mediterranean data?
@PeriklisICES do you know why we have StatRecs in the Mediterranean region in the SF?

**Comment by cekv** [comment]
They have only submitted StatRecs for 2020, 2016-19 is without (-9). Would not say that it is imperative for them to submit them, but then again, there is nothing in the checks that prevent them from submitting them. 
@Osanna123 Is this something I need to communicate to the IT data submitter, please do not submit statrecs?

**Comment by Osanna123** [comment]
We need to look at the original document described here: https://www.ices.dk/data/maps/Pages/ICES-statistical-rectangles.aspx
@HansMJ , @Osanna123 to find it

**Comment by Osanna123** [comment]
agreed to extend the ICES StatRec definitions to the Mediterranean area, and add the missing codes to the vocab.
@cekv @pcrjoana to share the list with @mehdiabbasi to add to the Vocab.
Talk to @PeriklisICES about missing codes in GDB

**Comment by neil-ices-dk** [comment]
> 
> 
> agreed to extend the ICES StatRec definitions to the Mediterranean area, and add the missing codes to the vocab.
> @cekv @pcrjoana to share the list with @mehdiabbasi to add to the Vocab.
> Talk to @PeriklisICES about missing codes in GDB

to be done by @pcrjoana and @cekv

**Comment by pcrjoana** [comment]
Mehdi has added these to the vocab.

**Comment by neil-ices-dk** [comment]
@pcrjoana is it closed, what about the action above for Periklis?

**Comment by PeriklisICES** [comment]
I am not sure what the action is. Do we want to extend the grid on the spatial facility @Osanna123?

**Comment by Osanna123** [comment]
@PeriklisICES Carlos found a number of ICES StatRecs missing from the GDB (and the SF map respectively):
USE RECO
SELECT        ST.ICESNAME, RST.Code
FROM            (SELECT        tblCodeID, tblCodeTypeID, Code, Description, [User], Created, Modified, Visibility, Deprecated, LongDescription
                          FROM            dbo.tblCode
                          WHERE        (tblCodeTypeID = 107)) AS RST LEFT OUTER JOIN
                         GDB.sde.ICES_STATISTICAL_RECTANGLES AS ST ON RTRIM(LTRIM(RST.Code)) = RTRIM(LTRIM(ST.ICESNAME))
WHERE        (ST.ICESNAME IS NULL)

That's what needed to be checked with you.

**Comment by PeriklisICES** [comment]
That table has only the rectangles that fall within the ICES Ecoregions. The full table can be found in the GDB_Prod which should be used for things like this as it is cleaner and has better naming for the layers:
GDB_Prod.sde.ICES_STATREC
