### ISSUE TITLE
AC_SaCategory deletions

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/DIG#77]
Following AC_SaCategory codes were **deleted** from RECO, without logging on this board or contacting RMG:

D8	Sardine echoes
D7	Anchovy fish echoes
D6	Mixed fish echoes
D5	Shelbreak fish echoes
D4	Fish echoes located above 30 m depth
D3	First layer of non-clupeiform fish echoes, located above the seabed
D2	Clupeiform fish echoes, located between 20 and 50 m above the seabed
D12	Sound scattering layers located below 30 m depth
D11	Sound scattering layers located above 30 m depth
D10	Noise, multiple seabed echoes, non-fish echoes
D1	First layer of non-clupeiform fish echoes, located at less than 20 m above the seabed

**Comment by Osanna123** [comment]
@HjalteParner , you're the first one to give chocolates/beers

**Comment by HjalteParner** [comment]
@Osanna123 that was before we agreed on the chocolates/beers agreement! But sorry! I thought it would slip through your radar but apparently not. Anyhow these codes was created by mistake and shouldn't be used anybody anymore. So this deletion was to prevent the use again FYI.

**Comment by Osanna123** [comment]
@HjalteParner hoping that deletions will slip under our radar is not a good data management practice. So I must insist on beers/chocolates and on you using this board for documenting similar cases in the future.
