### ISSUE TITLE
7 - Updated list of data guideline review status

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#8]
Complete an updated list of Data Guidelines review status, including ones that cannot be reviewed or maintained. Update information on Data Guidelines metadata accordingly

**Comment by neil-ices-dk** [comment]
[updated list here](https://community.ices.dk/Committees/DIG/DIG%202020/04.%20Working%20documents/DataGuideLines.xlsx)

**Comment by cfpo** [comment]
No further updates to data guideline review status. Data guideline metadata will be updated accordingly as guidelines get updated.

**Comment by sjurl** [comment]
Meeting planned for march to progess work on this task.

**Comment by sjurl** [comment]
@sjurl check progress with @cfpo
