### ISSUE TITLE
Additions and description changes for Areas_HELCOM_L4

### ISSUE THREAD

**Issue by HansMJ** [ices-eg/DIG#81]
The list of HELCOM L4 areas is missing 103 new codes (compared with [latest version of the layer at HELCOM](http://metadata.helcom.fi/geonetwork/srv/eng/catalog.search#/metadata/67d653b1-aad1-4af4-920e-0683af3c4a48))

93 of the existing descriptions need to be updated.

Both inserts and updates are detailed in Excel:
[Inserts and updates to Areas_HELCOM_L4 codelist in RECO.xlsx](https://github.com/ices-eg/DIG/files/6434959/Inserts.and.updates.to.Areas_HELCOM_L4.codelist.in.RECO.xlsx)

The Areas_HELCOM_L4 layer is used for DOME views and assessment product generation.

The change should not impact other usages as far as I can tell

**Comment by pcrjoana** [comment]
Anna and Hans agreed to ask HELCOM for more information about the areas.
HELCOM contact: Andzej.Milos@helcom.fi

**Comment by cekv** [comment]
HELCOM has proposed to wait with these changes until the autumn, because there are more to come.

**Comment by Osanna123** [comment]
@Osanna123 @HansMJ check with HELCOM on this task

**Comment by jkaitaranta** [comment]
We will have final decision on changes in December after HOD meeting. After that we will process new L1-L4 datasets and share to ICES in January 2022.

**Comment by Osanna123** [comment]
https://maps.helcom.fi/website/mapservice/?datasetID=67d653b1-aad1-4af4-920e-0683af3c4a48

New definitions are now available
Level 1. HELCOM Marine area 2022. No division: the whole Baltic Sea encompassing the entire HELCOM area,
Level 2. HELCOM Subbasins 2022. Division of the Baltic Sea into 17 sub-basins.
Level 3. HELCOM Subbasins with coastal and offshore division 2022. Division of the Baltic Sea into 17 sub-basins and further division into coastal and off-shore areas, 
Level 4a. HELCOM Subbasins with coastal WFD water types of water bodies 2022. Division of the Baltic Sea into 17 sub-basins and further division into coastal and off-shore areas and division of the coastal areas by WFD water types or water bodies.
Level 4b. HELCOM Subbasins with coastal WFD water types of water bodies 2022 for eutrophication. Division of the Baltic Sea into 19 sub-basins and further division into coastal and off-shore areas and division of the coastal areas similarly as in Level 4a by WFD water types or water bodies with specific subdivisions for eutrophication.

**Comment by Osanna123** [comment]
Create a new CodeType Areas_HELCOM_L4a, ask HELCOM for a list in another format
https://vocab.ices.dk/?ref=1494 will be deprecated
Add L2 to description of https://vocab.ices.dk/?ref=350

**Comment by Osanna123** [comment]
New CT 1727 created
CT 1494 made invisible. Deprecation does not work on CT level
L2 descr. changed, but see issue #288

**Comment by odontaster** [comment]
Make visible and deprecate all codes in it @Osanna123
