### ISSUE TITLE
RDBES replacing the generic Metier6_FishingActivity and Metier5_FishingActivity with the new metier list from RCG Metier subgroup

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#82]
The RCG NA NSEA Baltic and WGRDBESGOV have agreed to use the new metier list developed by the RCG Metier subgroup, therefore it should also be used in the RDBES. The RDBES data model will be changed/updated therefore all data, which have used the metier codes in the Metier6_FishingActivity will be deleted, which makes it easier to update to the new agreed metier list. The existing Metier6_FishingActivity consist of 1218 metier codes, the new metier list consist of 1410 metier codes. The most efficient and safest way to do this replace is to delete all codes in the list, since I do not know of other systems using the Metier6_FishingActivity and Metier5_FishingActivity lists, then we can make a bulk insert.

**Comment by cekv** [comment]
@HenrikK-N bibliographic reference needed and full metier list is needed beforehand.

**Comment by HenrikK-N** [comment]
The new metier list is now attached
[New Metier list for RDBES.xlsx](https://github.com/ices-eg/DIG/files/6585624/New.Metier.list.for.RDBES.xlsx)
We need this done preferably be for the data call goes out, because we refer to the new metier list and request data submitters to use the new metier list.

**Comment by HenrikK-N** [comment]
The RCG Intersessional subgroup Metier list have worked on it, please contact the chair Josefine Egekvist jsv@aqua.dtu.dk for details, and it has been approved at the Liaison Meeting and WGRDBESGOV.

**Comment by cekv** [comment]
REF: https://github.com/ices-eg/RCGs/tree/master/Metiers, https://community.ices.dk/ExpertGroups/WGRDBESGOV/2020%20Meeting%20Docs/03.%20Report%202020/WGRDBESGOV_draft_report_final.docx

**Comment by cekv** [comment]
Implementation by @cekv , @EjazAtIces  and @mehdiabbasi

**Comment by HenrikK-N** [comment]
Attached is a speadsheet with both the Metier 5 and 6 new codes (one on each sheet) and with descriptions.
[New Metier list for level 5 and 6 with descriptions.xlsx](https://github.com/ices-eg/DIG/files/6699748/New.Metier.list.for.level.5.and.6.with.descriptions.xlsx)
