### ISSUE TITLE
RDBES: Rename 'RS_ValueType' to 'RS_ValueUnitOrScale'

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#83]
The Core Group agreed that 'RS_ValueUnitOrScale' is more correct and informative than 'RS_ValueType'.

**Comment by neil-ices-dk** [comment]
> 
> 
> The Core Group agreed that 'RS_ValueUnitOrScale' is more correct and informative than 'RS_ValueType'.

this is not a new issue, see #41
