### ISSUE TITLE
RDBES: Insert/update descriptions for RS_SelectionDevice

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#84]
RS_SelectionDevice update descriptions (from blank) with the following and add '4':

Code | Description
0       | No selection device
1       | Selection panel
2       | Grid
3       | T90. The codend  and extension piece are produced from knotted diamond mesh netting turned 900.
4       | There is both selection device and escape window.

**Comment by cekv** [comment]
Drop Prefix RS_
@HenrikK-N to add bibliographic references to the selection devices.

**Comment by cekv** [comment]
https://www.ices.dk/sites/pub/Publication%20Reports/Expert%20Group%20Report/ftc/2006/WGFTFB06.pdf
