### ISSUE TITLE
RDBES: Update descriptions for RS_CatchCategory

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#85]
The description for RS_CatchCategory should be updated to the following (Spelling error in desc. for RegDis: Registered):
Code	Description
BMS 	Below Minimum Size landing
Catch 	Catch (when landing and discard is mixed)
Dis 	Discard
Lan 	Landing
RegDis 	Logbook Registered Discard

**Comment by pcrjoana** [comment]
@cekv to implement

**Comment by cekv** [comment]
Implemented on 28/05/2021 by Cecilia
