### ISSUE TITLE
RDBES: Add code 'Unsorted' to RS_CommercialSizeCategoryScale

### ISSUE THREAD

**Issue by HenrikK-N** [ices-eg/DIG#86]
Add code 'Unsorted' to RS_CommercialSizeCategoryScale
Code          Description
Unsorted	  Unsorted, when catch is not sorted in size categories

**Comment by pcrjoana** [comment]
The code will be added. The code descriptions will be revised for clarity.
The code type name should be reviewed. @cekv to discuss this with the core group.
