### ISSUE TITLE
Add code to SEXCO

### ISSUE THREAD

**Issue by cekv** [ices-eg/DIG#89]
Adding 'T' (Transitional) to SEXCO 
https://vocab.ices.dk/?ref=45

**Comment by HenrikK-N** [comment]
It is not needed to add 'T' (Transitional) to SEXCO (SEXCO | Sex Codes (Environment) //vocab.ices.dk/?ref=45 ). Instead additional text can maybe be added to SEXCO.
Suggest code description updates for 3 of the code descriptions:
Code Description
H       Hermaphrodite and/or transitional
U       Undetermined (no attempt made)
I        Immature (attempt made but sex could not be destinguished) 

Current:
Code Description
H       Hermaphrodite 
U       Undetermined 
I        Immature

**Comment by AnnelieH** [comment]
WGBIOP agrees with the previous comment that Hermaphrodite and transitional can be in the same code = H

**Comment by cekv** [comment]
A Transitional code (T) will be added and the description for code U and I will have the clarified descriptions added

**Comment by cekv** [comment]
implemented the 9/6-21
