### ISSUE TITLE
8 - Betatest ICES data portal

### ISSUE THREAD

**Issue by sjurl** [ices-eg/DIG#9]
DIG to provide beta testers for testing developments on new ICES data portal

**Comment by neil-ices-dk** [comment]
Mehdi hasuploaded Data.ices.dk [mini workshop plan ](https://community.ices.dk/Committees/DIG/DIG%202021/05.%20Presentations/Data%20Portal%20workshop.docx)

And will use [Github board](https://github.com/ices-tools-dev/ICES_DataPortal) to collect feedback.

**Comment by MalinWerner** [comment]
If you want a person that is interested in data but does not have very much data portal knowledge as a test person I can volunteer. Malin W

**Comment by mehdiabbasi** [comment]
Many thanks, @MalinWerner. We need your expertise in data. Looking forward to seeing you in DIG and Data Portal workshop

**Comment by neil-ices-dk** [comment]
will be in breakout session on Thursday morning 20th May

**Comment by Ingeborg1312** [comment]
Hi @mehdiabbasi, I've been working on the user expectations for Data Criteria behaviour. My starting point was 'what do people in general expect when they select multiple data'. The 'AND' and 'OR' are technical 'AND' and 'OR', so from a programmer's perspective. Where 'AND-OR', both options should be allowed, when only one option is mentioned, this is basically the only option. Could you check if you get more or less my point: http://community.ices.dk/Committees/DIG/DIG%202021/02.%20Background%20documents/user_expectation_dataportal_20210521.xlsx

**Comment by mehdiabbasi** [comment]
Finally, we get rid of the Beta label on [https://data.ices.dk/](https://data.ices.dk/) and it is officially released on production on 31st August 2021. Thank you for all the DIG member feedbacks. We will use the board to follow up on the issues [https://github.com/ices-tools-dev/ICES_DataPortal/issues](https://github.com/ices-tools-dev/ICES_DataPortal/issues).  We will work to improve the ICES Data portal and also will start the development of an extended phase next year.
