### ISSUE TITLE
ISO 19115 CI_RoleCode added to vocab.ices.dk

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/DIG#93]
I would like the ISO 19155 CI_RoleCode added to vocab.ices.dk for use in oceanography and beyong.

Codetype: CI_RoleCode
Codetype description: Function performed by the responsible party

Items within the list can be found at

https://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.html
https://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml
http://vocab.nerc.ac.uk/collection/G04/current/

**Comment by cekv** [comment]
@HjalteParner what was the decision from DIG?

**Comment by HjalteParner** [comment]
@cekv which decision?

**Comment by Osanna123** [comment]
https://vocab.ices.dk/?ref=1434
Update the Description of the CodeType
Link to the valid references

**Comment by HjalteParner** [comment]
@Osanna123 will you also add the missing items? Oceanography at least need the Distributor role as well for now

**Comment by Osanna123** [comment]
Description in https://vocab.ices.dk/?ref=1434 is improved, missing concepts are added.
@HjalteParner note only Custodian, originator and owner are visible. Others can be made visible on demand.

**Comment by HjalteParner** [comment]
@Osanna123 I will also need Distributor to be visible.

Thanks for your effort
