### ISSUE TITLE
Change in stock name

### ISSUE THREAD

**Issue by Milldaz** [ices-eg/DIG#98]
There has been a proposal from WGDEEP to change the stock name and code for lin.27.3a4a6-91214. This has been approved by the ADG. For this stock, landings in divisions 4.b and 4.c are presently considered in the assessment and advice (these landings in 4bc are actually larger than landings in 8, 9,12, 14 altogether). Further, ling may occur at low level in 3.b as well. So the proposal is to include all of subareas 3 and 4 in the stock definition/name/code. 

OLD values
Stock Code: lin.27.3a4a6-91214
Description: Ling (Molva molva) in Subareas 6-9, 12, and 14, and Divisions 3.a and 4.a (Northeast Atlantic and Arctic Ocean)

NEW values:
Stock Code: lin.27.346-91214
Description: Ling (_Molva molva_) in subareas 3,4, 6–9, 12, and 14 (Northeast Atlantic and Arctic Ocean)

The associated ecoregions do not have to change.

Could somebody please create the new stock name/code in vocab at least a few days before the advice is released on 10 June?

**Comment by colinpmillar** [comment]
Hi,
probably a bit late, but is there a convention for including the baltic in stock codes?  Many stocks the cover the whole baltic are coded as 22-32 , ie.  spr.27.22-32, Sprat (Sprattus sprattus) in Subdivisions 22-32 (Baltic Sea).

There are only examples of stocks using 3a.  But none so far have used just 3.

**Comment by colinpmillar** [comment]
Sorry, ignore that, the subdivisions (22-32) are only used for exclusively baltic stocks, so the proposed name is consistent with other codes.

**Comment by Milldaz** [comment]
Thanks for checking that.

**Comment by pcrjoana** [comment]
@Milldaz for us to review new issues, they need to be added to the project board, otherwise we don't see them. :-)
![image](https://user-images.githubusercontent.com/49305340/119661291-6eb51180-be30-11eb-8c41-5c86bb9e0a4d.png)

@cekv to add the new code, and the old code needs to be deprecated in Intercatch. FYI @HenrikK-N

**Comment by Milldaz** [comment]
Hi,

Thanks very much for sorting out the new vocab. Not being in the data department, I don't know how you system works and who exactly is charge of certain tasks (though apparently there is no one contact point). This is why I didn't know where I had to put this initial request for review. Now that the vocabs are changed, the new code and stock name needs to be updated in various places. Again, this is a data task, so I don't know all the places where changes need to be made. I do know SID and SAG have to be updated at least. By speaking directly to Carlos SAG has been updated, but SID is not yet. So I guess I have to speak with Mike too. 

What I was hoping for, was one contact person or one board where I could highlight that a stock needed a name change, and then somebody (or some project board) in the data department would make sure all the parts were done. Because this it is a data task making sure that all our databases etc. are using the same vocabs. So I still think that it would be best if there was a single place/person that people from outside the data department could go to when they need a data task done. Both for quality assurance reasons and ease of work across the Secretariat.

Cheers,
David

**Comment by mikeydrew** [comment]
The code is already in SID, this is done automatically with the synch job from Vocab. Use the manage module, select the new stock option and then you can add the details -> 
![image](https://user-images.githubusercontent.com/10516840/121001889-09e0ac00-c78c-11eb-88d3-becb2c6413fb.png)
To remove the old stock,  uncheck the publish checkbox

**Comment by Milldaz** [comment]
OK, thanks. The reason I didn't think it was in SAG is that the old stock name is still there. 

This is not a new stock as such, we have just changed the name of an existing one. So it should still be linked to previous years with the old stock name/code. Does that still require me to create a new stock in SID? How do I link it with its past?

**Comment by mikeydrew** [comment]
@Milldaz no further action is required from your end. I made the changes.
